### ISSUE TITLE
Upload button is not aligned with "Create.." buttons

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1057]
### Steps to reproduce
1. click " + NEW"

### Expected behaviour
buttons aligned

### Actual behaviour
![image](https://user-images.githubusercontent.com/2425577/57072138-63986180-6cfc-11e9-8171-37a6db238749.png)

### Client configuration
**Browser:**
tested on FF and Chrome

**Operating system:**
Ubuntu 18.04

**Comment by DeepDiver1975** [comment]
has been fixed with #1058 -> closing
