### ISSUE TITLE
UX - file and folder actions

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1112]
## Description
Current file and folder actions are a little bit limiting. You can't really at the moment interact with files when you have selected more of them, they take quite a lot of space on smaller monitors and it's not exactly clear how the user can access the sidebar with file/folder details and versions.

## Current state of actions
At the moment actions are displayed inside of list of files. User has following options how he can interact with the file/folder:
- By clicking on checkbox open right sidebar where he can find file details, versions and sharing
- By clicking on files name open action menu on bottom of the screen
- By clicking on actions buttons he can either rename file, download file, delete file or open sidebar with sharing already selected
- If some action is not allowed for some file/folder, actions button is a little bit faded and disabled

![image](https://user-images.githubusercontent.com/25989331/57618252-31e88b80-7583-11e9-8460-f45780af8776.png)

![image](https://user-images.githubusercontent.com/25989331/57618363-74aa6380-7583-11e9-8416-8871bb9995f0.png)

![image](https://user-images.githubusercontent.com/25989331/57618481-ce129280-7583-11e9-9cf6-5e016bf6bb36.png)

## Proposal
We had chance to work on this two times with Andreas Wuensche (not sure when will be next time he'll be available to work on Phoenix) and he again provided us with some quick prototypes. The change we discussed was moving actions from file list into the app topbar. If the user would click on the file or folder it would immediately select the file and open right sidebar. If the user would use double click on the file, default action for it would be triggered (open pdf-viewer, text editor, etc), if he would double click folder, he would be navigated inside of that folder. Actions on top would be always displayed only when they are possible with current selection. If they would be disabled, they wouldn't be even visible not to confuse the user. This approach is very similar to the one Google drive is using so you can have also look there if you would be interested how it works there.

![image](https://user-images.githubusercontent.com/25989331/57619255-c48a2a00-7585-11e9-80a8-201226fd25cb.png)

![image](https://user-images.githubusercontent.com/25989331/57619149-8ab92380-7585-11e9-8709-9acfb50a9bb3.png)

![image](https://user-images.githubusercontent.com/25989331/57619201-a4f30180-7585-11e9-8d64-8a707a23e4d2.png)

![image](https://user-images.githubusercontent.com/25989331/57619214-ad4b3c80-7585-11e9-883b-b8cf814cd375.png)

![image](https://user-images.githubusercontent.com/25989331/57619295-dff53500-7585-11e9-825e-f146afc6b5d5.png)

It would be great to also hear your opinions about this - @michaelstingl @pmaier1 @DeepDiver1975 @felixboehm

**Comment by michaelstingl** [comment]
Yeah, like the simplified approach 👍

**Comment by DeepDiver1975** [comment]
>  If the user would use double click on the file, default action for it would be triggered (open pdf-viewer, text editor, etc)

I'm totally against the idea of a default action for files. Why?
1. choose download as default action - a user could easily trigger download of a multi GB big file which consumes network, client and server resources
2. choose an action based on registered plugins (e.g. pdf viewer for pdfs) - this can easily create a mess as we have it today with owncloud and various office integrations - click on a word doc opens it in libreoffice but opening it in only office is not easily possible. 

Because of this mess in mind I explicitly decided to use no default action for files.

Moving away from the actions in file list forces users to perform more then one action to get to the desired functionality. I know that there are some strong requests to have some fast access to e.g. sharing ....

For the rest of this: :+1:

**Comment by LukasHirt** [comment]
1. We could add here one "safety layer" that download as default action would be possible only in case that there is no application that could open that file defined and before it would happen, user could get a dialog saying some warning about it together with name of selected file and its size. (quick sketch down below).

![image](https://user-images.githubusercontent.com/25989331/57628775-d7f3c000-759a-11e9-8e19-1ee8074a81a3.png)

2. Not sure if I fully understand this problem.

The fast access is a good point. I'm also scared about moving away from that but on the other hand I think it could bring a little bit more clarification on how is the user supposed to interact with the file and the difference between single file action and multiple files action. Also I was thinking that we could implement right click that would trigger dropdown menu when done on file. But this is something that would also need to be somehow "shown" to the user or "taught" them somehow that it's possible. In regards to sharing, this needs to be anyway discussed separately because we need a clear way to indicate the file is shared or not - I honestly don't think that the small icon of share inside of file icon

**Comment by PVince81** [comment]
As far as I saw today, I can select multiple files and some file actions will appear in the top bar.
For the files app it's mostly "Delete".
In the trashbin there's "restore" and "delete immediately". (why isn't this called "delete permanently" ?)

@LukasHirt please update the ticket accordingly if there is anything left to do.

Not sure if we have a proper extension point for apps to provide bulk actions like we have for regular actions ?

**Comment by LukasHirt** [comment]
@PVince81 

> please update the ticket accordingly if there is anything left to do.

This issue was kind of pushed into the background and haven't been done any progress. Needs to be revived. In general this issue is not only about actions for multiple selected items but about actions in general. We are trying to find an alternative to buttons in rows.

> Not sure if we have a proper extension point for apps to provide bulk actions like we have for regular actions ?

There isn't currently.

> In the trashbin there's "restore" and "delete immediately". (why isn't this called "delete permanently" ?)

I took this from trash bin in macOS. Can be renamed.

**Comment by PVince81** [comment]
to be processed with @wuenschedesign
