### ISSUE TITLE
Evaluate migration to vue-cli 3

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#1123]
see https://cli.vuejs.org/

vue cli seems to come with a pretty good default project setup (babel, browserlist, transpiling dependencies and so on) which could boost our development efforts.

**Comment by DeepDiver1975** [comment]
https://cli.vuejs.org/guide/browser-compatibility.html#browserslist

**Comment by DeepDiver1975** [comment]
deployment scenarios are already handled as well - e.g. like building docker https://cli.vuejs.org/guide/deployment.html#docker-nginx

**Comment by DeepDiver1975** [comment]
>  transpiling dependencies

https://cli.vuejs.org/config/#transpiledependencies

**Comment by LukasHirt** [comment]
@DeepDiver1975 Can we put this into 2nd milestone? Longer we wait, harder it will be to move what we have into vue-cli.

**Comment by PVince81** [comment]
also seen: https://medium.com/jinweijie/migrate-from-vue-cli-2-to-3-16f14e7febdc

from my understanding there shouldn't be much work needed for the migration as most of the changes are under the hood.

**Comment by DeepDiver1975** [comment]
please schedule this as necessary or not. pointless to keep such an issue open for that long
