### ISSUE TITLE
Handling existing files

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1150]
## Requirements
- [x] [Scenario: Creating a resource with an existing name](https://github.com/owncloud/enterprise/blob/master/product/oc10/resources.md#feature-creating-a-resource)
- [ ] [Scenario: Uploading a folder/file with an existing name](https://github.com/owncloud/enterprise/blob/master/product/oc10/resources.md#feature-uploading-a-resource)
  - [x] Scenario: Uploading a folder with an existing name
  - [ ] Scenario: Uploading a single file with an existing name (versioning enabled)
  - [ ] Scenario: Uploading multiple files with an existing name (versioning enabled)
  - [ ] Scenario: Uploading a single file with an existing name (versioning disabled)
  - [ ] Scenario: Uploading multiple files with an existing name (versioning disabled)

- [ ] [Scenario: Moving a resource to a location with an existing resource that has the same name](https://github.com/owncloud/enterprise/blob/master/product/oc10/resources.md#feature-moving-a-resource)

- [ ] [Scenario: Copying a resource within the same folder](https://github.com/owncloud/enterprise/blob/master/product/oc10/resources.md#feature-copying-a-resource)

- [x] [Scenario: Renaming a resource to an existing name](https://github.com/owncloud/enterprise/blob/master/product/oc10/resources.md#feature-renaming-a-resource)

## Open tasks:
- [ ] Acceptance tests
- [ ] Mockups
- [ ] Review tests and mockups
- [ ] Implement into Phoenix

**Comment by DeepDiver1975** [comment]
from my pov all what is possible for milestone 1 has been implemented - mainly handling on move and copy is missing - but we did not yet implement move and copy in phoenix -> milestone2
