### ISSUE TITLE
Extensions framework

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1151]
## Open tasks:
- [ ] Requirements
- [ ] Acceptance tests?
- [ ] Implement in Phoenix

**Comment by DeepDiver1975** [comment]
What is the scope of this ticket? We already have a working plugin mechanism in place.
Is this about the raised issues in #875 ?

Please put more information in here - THX

**Comment by LukasHirt** [comment]
This is an issue to figure out how to properly load apps from backend which are not directly stored in the Phoenix project dir. There is a few issues now opened that are just a preparation without a content. I'm creating them from the first milestone tasks from Phoenix Parity Roadmap. They will be filled with more info as soon as we get some requirements to them. For now it's only that we have some overview about what's needed to be prepared also.

**Comment by DeepDiver1975** [comment]
I suggest to move this to the next milestone. Users don't really care about this ;-)

**Comment by LukasHirt** [comment]
We discussed it with @pmaier1 and he agrees this could be moved. I'll go ahead and remove it from this one and as soon as we have here created the next one, I'll move it there.
