### ISSUE TITLE
Documentation (product and admins) on "web frontend"

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1152]
## Description:
Create documentation sections for Phoenix - how to deploy, etc.

**Comment by DeepDiver1975** [comment]
move to docs repo so that the doc team can work on this?

**Comment by LukasHirt** [comment]
Discussed with @pmaier1 - Doesn't need to be done in first milestone. We just need to make sure it's properly documented in readme how to run, build, etc. (Maybe needs to be added what keys can be used in config.json?) /cc @DeepDiver1975
