### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1153]
## Open topics:
- [ ] Do we need a custom error page? If there is no case where this would be needed we can cover that with alerts and error messages on login screen - right?

**Comment by pmaier1** [comment]
Is there a way to list the events that trigger an error page in the current frontend?

**Comment by LukasHirt** [comment]
> Is there a way to list the events that trigger an error page in the current frontend?

@DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
> Is there a way to list the events that trigger an error page in the current frontend?

not really

**Comment by DeepDiver1975** [comment]
I think we can close this - error pages will be shown where needed -> close
