### ISSUE TITLE
error message when creating a file with a name that already exist in the folder is too technical

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1164]
### Steps to reproduce
1. create a file called "file1"
2. create a second file with the same name

### Expected behaviour
nice error message saying what is wrong

### Actual behaviour
```
 Creating file failed…
An If-None-Match header was specified, but the ETag matched (or * was specified). 
```

**Comment by DeepDiver1975** [comment]
Second part of the message is coming from the server. This is a technical message from the webdav layer.

No idea what to do here

@LukasHirt any idea on how to hide this? THX

**Comment by LukasHirt** [comment]
We could check the name the same way as the / is being checked but I'm not sure if this is not a overkill for performance to list all files in current folder every time the user enters some new character... But I don't have any other idea. What do you think? @DeepDiver1975

**Comment by DeepDiver1975** [comment]
well - even if we do this way - this will not help in all cases.

E.g. file with the same name is created via another client.

Maybe we can do something on error handling looking at the http status code ...

**Comment by LukasHirt** [comment]
I created the check for existing files in PR #1580 but it solves it only the part inside of Phoenix and not the client one so keeping the issue opened so we can reference it later due to e. g. possible issues with creating in client and then in Phoenix without refreshing.

**Comment by DeepDiver1975** [comment]
There is not much we can do - the alternative would be to not show the server side messages at all - which is not great either ....
