### ISSUE TITLE
action button on smaller screens has no functionality

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#1185]
@felixheidecke as discussed

**Comment by individual-it** [comment]
what about tests on different resolutions? In selenium we can set the resolutions

**Comment by DeepDiver1975** [comment]
> what about tests on different resolutions? In selenium we can set the resolutions

we will need this - yes. Can you show us how to implement this? THX a lot

**Comment by DeepDiver1975** [comment]
close in favor of #1237 which has screenshots ;-)
