### ISSUE TITLE
Cannot rename file/folder back to its initial name

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/phoenix#1192]
## Description
Renaming the file/folder to its initial name gives 
`File or folder with name "<name>" already exists.` error message.

## Steps to reproduce
1) click rename on any file/folder
2) click `OK`

## Actual Behaviour
![image](https://user-images.githubusercontent.com/20378877/58469557-6f424100-815f-11e9-8ba7-514167e60de2.png)

## Expected behavior
File/folder should not be renamed and the UI should not give any error

**Comment by DeepDiver1975** [comment]
Hmmm ..... Disable to Hit okay?

**Comment by Julian1998** [comment]
@DeepDiver1975 Well... I already fixed that using solution 2
https://github.com/owncloud/phoenix/pull/1272
