### ISSUE TITLE
Last share information does not resets in sharing sidebar

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/phoenix#1193]
## Description
After the user has shared a file/file and tries to share another file/folder,
the last share status doesn't go away

## Steps to reproduce
1) Click share button of some file `file1`
2) Share with user `user one`
3) Chick share button of another file `file2`

## Actual Behaviour
Last share details for `file1` shows up in sharing sidebar of `file2`
![image](https://user-images.githubusercontent.com/20378877/58469998-7cabfb00-8160-11e9-8d5d-54351a50666c.png)

## Expected Behaviour
Last share details should not show for other files.

**Comment by LukasHirt** [comment]
Fixed - closing.
