### ISSUE TITLE
user cannot see the parent folder of an item on the favorites page

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1194]
### Steps to reproduce
1. have a folder `F1/subfolder` and `F2/subfolder`
2. mark both subfolders as favorites
3. navigate to the favorites page

### Expected behaviour
somewhere should indicate which of the folders is which

### Actual behaviour
to the user both folders look exactly same

**Comment by individual-it** [comment]
reopening to implement acceptance tests for it

**Comment by skshetry** [comment]
Closing this as it's done in #1407
