### ISSUE TITLE
[IE11-QA] Alternative login is confusing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1226]
Starting with https://p******.*****.***/custom/phoenix/index.html#/

![grafik](https://user-images.githubusercontent.com/1108546/58940397-aa54fd80-8779-11e9-8d48-e0c8ab4dc0ab.png)

Clicking on the alternaive login, brings me back exactly to the same URL
https://p******.*****.***/custom/phoenix/index.html#/

User's may expect a real alternative if their login does not work.

**Comment by DeepDiver1975** [comment]
yes - we have to work on that

**Comment by scheinercc** [comment]
I was just about to file a ticket that the demo doesn't seem to work atm. Is that right or did I overlook something, like a demo user/pass?
