### ISSUE TITLE
[IE11-QA] New file gets opened as a folder

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/phoenix#1227]
IE 11

Steps to recreate:
1) Click + New button 
2) Click Create a new file
3) Enter a file name
4) Click OK
5) Click on the file to open it/download it

Expected result: User is presented with an option to download or markdown
Actual result: Folder view is opened

![image](https://user-images.githubusercontent.com/49001702/58941777-c6a66980-877c-11e9-9d5f-8b27a5a4dc1c.png)

**Comment by DeepDiver1975** [comment]
duplicate #1232
