### ISSUE TITLE
[IE11-QA] Line wrapping in Markdown Editor preview

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/phoenix#1229]
IE11

Steps to recreate:
1) Opened txt file for editing
2) Write a few words
3) Hit Enter
4) Enter a few words

Actual result: Preview differs from the actual result 
Expected result: Preview is the same as the actual result 

![image](https://user-images.githubusercontent.com/49001702/58942160-872c4d00-877d-11e9-989d-d4932e7f90de.png)

**Comment by HanaGemela** [comment]
Also the first line in preview is not visible

**Comment by DeepDiver1975** [comment]
> Also the first line in preview is not visible

this is valid

**Comment by DeepDiver1975** [comment]
> Actual result: Preview differs from the actual result

this is how markdown works -> not a bug

**Comment by DeepDiver1975** [comment]
@Julian1998 the visibility of components needs to be adjusted - THX

**Comment by jnweiger** [comment]
# Tested with IE11 on the acl test system
Cannot test. All files are only offered for download. No editor opens.
OKAYISH.

**Comment by DeepDiver1975** [comment]
Acl has No Editor installed. Use Phoenix.owncloud.com
