### ISSUE TITLE
[IE11-QA] creating new file fails with 'unknown error'

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1230]
Logged in as admin, in the toplevel folder hit the '+NEW' button.
enter 'fooo' as filename. An Unknown error occurs:

![grafik](https://user-images.githubusercontent.com/1108546/58942590-5698e300-877e-11e9-951a-5909e39d7741.png)

Not reproducable. It works on the second attempt.

**Comment by DeepDiver1975** [comment]
temporal shift in the matrix ....
