### ISSUE TITLE
[IE11-QA] click open a file without suffix opens a folder view

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1232]
![grafik](https://user-images.githubusercontent.com/1108546/58943226-99a78600-877f-11e9-973d-6f9e2fcfedad.png)

Click on the file name 'Aloah', A folder view opens, with the remark 'no upload permission'

![grafik](https://user-images.githubusercontent.com/1108546/58943323-c9ef2480-877f-11e9-9d46-81f182ee81ff.png)

Download should be offered instead. It is actually a text file with 55 Bytes.

**Comment by DeepDiver1975** [comment]
:fearful: :scream:

**Comment by jnweiger** [comment]
## Tested with IE11 on the acl test system
With or without suffix,  a download is offered. No more folder view.
OK.
