### ISSUE TITLE
[IE11-QA] 'File with this name already exists' message when renaming a file

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/phoenix#1233]
Steps to recreate:
1) Click the pencil icon to rename a file/folder
2) Click OK without any changes

Expected result: Window is closed, file name remains the same
Actual result: Error message that file/folder already exists

![image](https://user-images.githubusercontent.com/49001702/58943386-e4c19900-877f-11e9-9d7d-0ab8ae28f871.png)

**Comment by jnweiger** [comment]
## Tested with IE11 on the acl test system
Empty renames just do nothing now.
After adding whitespace and removing a character, user Joe suddenly lost access to the entire Supplier_Portal https://github.com/owncloud/phoenix/issues/1326
