### ISSUE TITLE
[IE11-QA] placeholder text 'file info sidebar' seen

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1238]
Click on the sharing icon of a file or folder.
Select the 'FILE DETAILS' tab.

![grafik](https://user-images.githubusercontent.com/1108546/58945463-310ed800-8784-11e9-8d49-6d6a4d0646cd.png)

There should be no placeholder text. There should be something about the file (or FOLDER) or nothing.

**Comment by HanaGemela** [comment]
Placeholder also in 
![image](https://user-images.githubusercontent.com/49001702/58946701-ca3eee00-8786-11e9-84e9-f275ef1861fd.png)

Steps to recreate:
1) Click the checkbox to select everything

**Comment by DeepDiver1975** [comment]
Valid reports. THX

**Comment by jnweiger** [comment]
## Tested with IE11 on the acl test system
Cannot test. Only the SHARING tab is shown now.
OKAYISH

**Comment by DeepDiver1975** [comment]
File Details Tab was removed 🤪
Thats the fix
