### ISSUE TITLE
[IE11-QA] Wrong modification date

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/phoenix#1239]
Steps to recreate:
1) Create a file or a folder
2) Check the modification time

Expected result: Now or 1 min ago
Actual result: 9 hours ago

![image](https://user-images.githubusercontent.com/49001702/58948481-85b55180-878a-11e9-9dc1-9ffc563851f7.png)

**Comment by DeepDiver1975** [comment]
What is your client timezone? (double check time settings in your windows vm)

Does this happen in another browser as well or is that IE specific? THX

**Comment by HanaGemela** [comment]
My timezone was wrong. Works as expected
