### ISSUE TITLE
[IE11-QA] Clicking on a folder inside a path opens root

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/phoenix#1240]
Steps to recreate: 
1) Create a folder called First
2) Inside First folder create another folder called Second
3) Inside Second folder create another folder called Third
4) Go inside Third folder
5) Click on the Second folder at the top in the path

Expected result: User has been redirected to Second folder
Actual result: User has been redirected to root folder

![image](https://user-images.githubusercontent.com/49001702/58947767-e9d71600-8788-11e9-9493-bc34767e78dc.png)

**Comment by DeepDiver1975** [comment]
Unrelated to IE - happens in Chrome as well - it is a routing issue.

**Comment by jnweiger** [comment]
## Tested with IE11 on the acl test system
The indicated folder opens correctly.
OK
