### ISSUE TITLE
[IE11-QA] Drag and drop from filsystem into web view looks promising, but fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1243]
I am dragging a zip file from my owncloud explorer 'Recent files' into the web interface.
A very promising user feedback appears
![grafik](https://user-images.githubusercontent.com/1108546/58948774-30c60b00-878b-11e9-804f-b8091c219961.png)

but it does not do anything.

**Comment by jnweiger** [comment]
Moving a zip file from my 'Recent files' list does not work. Silently. It should throw an error, if the move fails.

Moving the same zip file from Recent files to Desktop then move it to the web folder, a copy is uploaded to the server. (Copy instead of move, well)

**Comment by DeepDiver1975** [comment]
Works for me here - related to IE version on Windows 10 or Windows 7

My IE11 on Windows 10 is using Edge Mode :confused: 

![Screenshot from 2019-06-13 14-38-56](https://user-images.githubusercontent.com/1005065/59433156-3524a080-8de9-11e9-8785-6301c402981f.png)

**Comment by DeepDiver1975** [comment]
no further feedback -> closing for now - we need a new test cycle for ie anyway
