### ISSUE TITLE
[IE11-QA] changing sharing permissions shows a circle forever

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1246]
user admin shares a Folder (Photos-from-admin) with user demo.
The initial setting is 'co-owner'. When user admin clicks the pencil to change the settings,
he can choose e.g. '(*) Legacy'.
Pressing the SAVE button does not seem to do anything except adding a little circle to the left of the button.

![grafik](https://user-images.githubusercontent.com/1108546/58953825-d7b0a400-8797-11e9-8dd4-fc6bf788bf4c.png)

Click on the pencil again. And the selection jumps back to 'co-owner'. 
Were the changes actually saved?

**Comment by DeepDiver1975** [comment]
sharing is not yet finally finished - please ignore for now - THX

**Comment by jnweiger** [comment]
## tested with IE11 on the acl test system
chaning permissions works fine.
OK
