### ISSUE TITLE
[IE11-QA] Loading folder failed

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/phoenix#1247]
Steps to recreate:
1) Log in as demo user to the test url
2) Go to Favorites folder

Expected result: Favorites has been opened 
Actual result: Error

![image](https://user-images.githubusercontent.com/49001702/58954106-83f28a80-8798-11e9-9df7-5b0aaa909aab.png)

**Comment by DeepDiver1975** [comment]
Only in IE? Or also in any other browser? THX

**Comment by HanaGemela** [comment]
Also in Chrome

**Comment by jnweiger** [comment]
# Tested with IE11 on the acl test system
Favorites page loads fine now.
OK
