### ISSUE TITLE
[IE11-QA] rejected shares cannot be listed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1248]
User admin shares folder Foo with user demo.
User demo sees folder Foo and deletes the folder.
User admin checks sharing of folder Foo, it is still shared with user demo.

User demo now has no way to access the folder. A 'shared with you' listing is missing.

**Comment by DeepDiver1975** [comment]
not yet implemented

**Comment by DeepDiver1975** [comment]
closing this - sharing panel was completly reimplemented
