### ISSUE TITLE
[IE11-QA] changin sharing permissions sometimes does not close the dialog

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1249]
User admin shares a Folder with user demo.
User admin clicks on the pencil to change the permissions from (default) 'Co-owner' to 'Legacy'.
User admin presses the SAVE button.

A circle appears, and nothing happens. The dialog does not close.
![grafik](https://user-images.githubusercontent.com/1108546/58954656-16dff480-879a-11e9-8e68-bdc6c971b63d.png)

In other cases, (switching between Viewer, Editor, Co-owner) the SAVE button closes the dialog.

**Comment by DeepDiver1975** [comment]
as said - sharing is not yet finished -> closing

**Comment by jnweiger** [comment]
## Tested on IE11
* legacy no longer exists, 
* other switches work fine.
GOOD
