### ISSUE TITLE
[IE11-QA] download of older version is defunct

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1250]
After editing a file several times, the file has versions.

![grafik](https://user-images.githubusercontent.com/1108546/58955423-3b3cd080-879c-11e9-9fae-8511483c2ac9.png)

In the versions listing clicking on the clock icon resets the current version. GOOD.
in the versions listing,  clicking on the download? icon (cloud with down arrow) nothing happens. BAD.

**Comment by DeepDiver1975** [comment]
only in IE? mind quickly testing in another browser as well? THX

**Comment by jnweiger** [comment]
## Tested on IE11
Cannot test, the VERSIONS dialog is no longer shown. Only 'SHARING'.

**Comment by DeepDiver1975** [comment]
Use Phoenix.owncloud.com
