### ISSUE TITLE
[IE11-QA] share permissions not shown to share reciever

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1251]
User admin shares a folder with user demo.
User demo sees the folder, and sees herself as owner.
It is not visible that that is a recieved share. Should be indicated.

User admin changes share permissions to editor.
User demo checks the permissions and sees herself still listed as owner. Should show editor now.

**Comment by DeepDiver1975** [comment]
no implemented yet

**Comment by DeepDiver1975** [comment]
closing this - the sharing panel was completly reimplemented ....
