### ISSUE TITLE
[IE11-QA] sharing back with the original sharer does not do anything

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1252]
User admin shares a folder with user demo.
User demo clicks on sharing and is allowed to share the folder with user admin.
A) User admin should not be in the list of allowed receivers.
or:
B) There should be an error message when demo tries to share back to admin.

**Comment by DeepDiver1975** [comment]
error feedback is missing in the sharing panel

**Comment by DeepDiver1975** [comment]
there is currently only a console.log - https://github.com/owncloud/phoenix/blob/71786d90dd79174d1f83330dbf9574d369c5f1ed/apps/files/src/store/actions.js#L322

**Comment by Julian1998** [comment]
I guess the correct behavior would be ignoring the share owner while trying to find the user/group to share with @DeepDiver1975 

Your thoughts?

**Comment by DeepDiver1975** [comment]
Two things are to be done:
- filter the owner (any all already shared with)
- add error handling - there is none at the moment - just use showNotification
