### ISSUE TITLE
folder names in breadcrumbs overlayed by search bar on low resolution

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1269]
![image](https://user-images.githubusercontent.com/2425577/59078997-760c4900-8901-11e9-9ee0-4c4bbfd3b178.png)

**Comment by DeepDiver1975** [comment]
will be fixed with #1221

**Comment by felixheidecke** [comment]
> will be fixed with #1221
Well, not really as this can be tackled in different ways.

Space is really tight in the app-bar there. So I suggest the following:

![breadcrumb-in-tight-spaces](https://user-images.githubusercontent.com/12717530/59920228-21e98480-942a-11e9-8ad8-96916fd2cf08.png)

1. Navigate to the immediate parent folder
2. Current folder (ellipses if name it tooo long)
3. All extra functions will hide in this "more" button

@individual-it @DeepDiver1975 @LukasHirt thoughts?

If it's feasable … I would take a look on how the "more" could work.

**Comment by DeepDiver1975** [comment]
I'm moving this to next week already - we need to chat about this then ....

**Comment by DeepDiver1975** [comment]
![Screenshot from 2019-06-25 10-39-11](https://user-images.githubusercontent.com/1005065/60083212-97f53080-9735-11e9-9cd1-da21d860d2db.png)
![Screenshot from 2019-06-25 10-39-22](https://user-images.githubusercontent.com/1005065/60083211-97f53080-9735-11e9-892d-19a71d0debb1.png)
![Screenshot from 2019-06-25 10-39-34](https://user-images.githubusercontent.com/1005065/60083210-975c9a00-9735-11e9-9586-e8024accde5d.png)
![Screenshot from 2019-06-25 10-39-43](https://user-images.githubusercontent.com/1005065/60083209-975c9a00-9735-11e9-91de-1e88c39b5904.png)

**Comment by felixheidecke** [comment]
exactly :-)

**Comment by DeepDiver1975** [comment]
go for it :+1:

**Comment by LukasHirt** [comment]
@felixheidecke @DeepDiver1975 @michaelstingl  I wouldn't hide the search. We could try to copy a little bit the new iOS here.

![image](https://user-images.githubusercontent.com/25989331/60088324-c4617a80-973e-11e9-82df-d2de6f962f66.png)

Exchange back with home icon, in the middle the same behaviour - current folder with a dropdown in which you find all the previous folders - and instead of select filter and I think we are good to go. This should work nicely IMHO. Any thoughts about this?

**Comment by DeepDiver1975** [comment]
Nice alternative - yes. THX for the input

**Comment by felixheidecke** [comment]
I guess in the app, all that disappears on the scroll. Apps have no authority over the Phoenix top bar, so the height and layout will remain as is. All of that together would amount to block roughly 1/4 or 1/5 other the overall vertical space. We can also have the app bar disappear on scroll and reappear on scroll upwards. Not in general but in the filesAppBar case.

Is the search as important so that it needs to be in view @ all times?

**Comment by felixheidecke** [comment]
We must not forget, that the browser also brings its own address bar and app-info bar (or whatever term is)

![Screenshot_20190625-131524_Chrome](https://user-images.githubusercontent.com/12717530/60094102-6c7d4080-974b-11e9-8c72-7535e2302b97.jpg)

**Comment by wuenschedesign** [comment]
which actions are hided under the »more« options?

**Comment by felixheidecke** [comment]
Here we would have search, adding (Files and Folders) as well as the Filter option. All that is available in the wide-view so far.

**Comment by wuenschedesign** [comment]
I would not hide these options!

**Comment by wuenschedesign** [comment]
the »add new« can be positioned under the breadcrumb.

**Comment by wuenschedesign** [comment]
»add new« needs a primary colour. Currently it’s a nearly disabled colour.

**Comment by wuenschedesign** [comment]
In the current screen, there are two »hamburger menues«. That’s one too much.

**Comment by felixheidecke** [comment]
As mentioned above … there is not much vertical room to show all of that @ the same time. There is the address bar as well as all the other stuff. If you'd like … I can go ahead and create a visual clue on how this may look.

**Comment by felixheidecke** [comment]
> In the current screen, there are two »hamburger menues«. That’s one too much.

@wuenschedesign this is the current oc11 way. The second burger is not part of the breadcrumb and not part of the session ;-)

**Comment by felixheidecke** [comment]
A rough compilation of having the two rows of content here:

![FireShot-Capture-023---ownCloud-Phoenix---192 168 2 82](https://user-images.githubusercontent.com/12717530/60161918-b7a15d00-97f8-11e9-8c4a-2b611066d774.jpg)

On scrolling down, the adressbar disappears, on scrolling up it reapears roughly blocking 1/3 of the screen height.

**Comment by felixheidecke** [comment]
I propose the following, based on what @LukasHirt had in mind.

![FireShot-Capture-024---ownCloud-Phoenix---phoenix owncloud com](https://user-images.githubusercontent.com/12717530/60168021-875fbb80-9804-11e9-8671-e5e88e412821.png)

@wuenschedesign Using the small(er) approach on the right, we may be able to show more buttons. Such as search and add. The "rest" will be available inside of the more-button.

**Comment by wuenschedesign** [comment]
Why is the name of the folder in a pulldown menu?

**Comment by felixheidecke** [comment]
That stems from the current header implementation that @LukasHirt mentioned here: https://github.com/owncloud/phoenix/issues/1269#issuecomment-505371089
