### ISSUE TITLE
No create button visible on low resolutions

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1270]
![image](https://user-images.githubusercontent.com/2425577/59079114-df8c5780-8901-11e9-9063-b7742ce756ca.png)

**Comment by DeepDiver1975** [comment]
duplicate #1185

**Comment by DeepDiver1975** [comment]
test can  now be unskipped

**Comment by individual-it** [comment]
@DeepDiver1975 this is about the create `+` button

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 this is about the create `+ NEW` button

oh - I'm sorry - should be addressed in #1221
