### ISSUE TITLE
[QA] User with Quota 0 can create files and empty folders

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1273]
Outside of any sharing portal, in the filesystem root folder, users can create folders, and create empty files, even after the owncloud administrator reduced user's quota to 0B.

This should 
a) trigger an error in owncloud core
b) should be suppressed in the frontend code, e.g. by removing the '+NEW' button.

**Comment by jnweiger** [comment]
File upload appears to work, but then fails.
For a large file the users sees the progress counting to 100%, and only then the error message appears:

![grafik](https://user-images.githubusercontent.com/1108546/59103540-74597a00-892f-11e9-815c-048199fca369.png)

**Comment by DeepDiver1975** [comment]
ToDo:
- [ ] find api to get quota
