### ISSUE TITLE
Please help me,how to solve the problem: Please provide a valid owncloud instance

### ISSUE THREAD

**Issue by yaagee** [owncloud/phoenix#129]
I have installed owncloud in virtual machine, The content named config.php is the following:
[root@localhost config]# cat config.php
`<?php
$CONFIG = array (
  'instanceid' => 'oc5pxm45zzcq',
  'passwordsalt' => 'U724aD7L/QNWvyuPrUo6v6FoMI5Cto',
  'secret' => 'hK5Y3jH/5wpYt/bKcVlX9oOAMV/fN6dLW5oAfcVX/qCzdHD/',
  'trusted_domains' => 
)`

In client, I modified the file named config.json like this:
`{
	"servers" : [
		"http://192.168.201.201/owncloud"
	],
	"theme": "owncloud",
	"version": "10.0.8",
	"instanceid": "oc5pxm45zzcq",
	"apps" : [
		{ "id" : "files" }
	]
}`
when I call login function to login, I got a error: Please provide a valid owncloud instance.
where should I get instanceid from ?
Could anyone please help me to solve the issue?

**Comment by felixheidecke** [comment]
Did you try adding your frontend URL to the CORS Whitelist?
http://xyz/index.php/settings/personal?sectionid=security#cors

**Comment by individual-it** [comment]
adding `http://localhost:8300` to CORS in Settings->Security fixed it for me. Please reopen if the problem persist
