### ISSUE TITLE
[QA] Version or Build release cannot be found in the user interface

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1294]
The exact version number or build release number would be a great help for QA.
Currently we cannot make qualified reports aswe donot know against which version we are testing.

Suggest to e.g. put it on the bottom of the left hand side menu:

![image](https://user-images.githubusercontent.com/1108546/59287979-0a184080-8c73-11e9-99fc-60ca9054964a.png)

**Comment by DeepDiver1975** [comment]
Version number can be a bit tricky in fast deploying scenarios. Build date + git hash?

**Comment by jnweiger** [comment]
Build Date + git hash is just perfect for QA purposes.

**Comment by DeepDiver1975** [comment]
grab version from https://github.com/owncloud/phoenix/blob/62cf30b46305562fbe849f5a8f8a65a502cc153f/package.json#L5

git hash and build date can be injected via the environment
