### ISSUE TITLE
switching between files when sharing dialog is open does not refresh the view correctly

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1342]
### Steps to reproduce
1. share one file
2. do not close the sharing dialog
3. share a second file

### Expected behaviour
the second file should not have any shares listed

### Actual behaviour
the sharing information of the first file are still visible
also the file/folder icon does not change

![bug](https://user-images.githubusercontent.com/2425577/59908627-8e19b780-942d-11e9-9e1b-6db75fe7ccb7.gif)

**Comment by LukasHirt** [comment]
Fixed - closing.
