### ISSUE TITLE
Update notification

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1377]
## Description
Admins need to receive a notification in case there is available new update.

**Comment by DeepDiver1975** [comment]
The owncloud notification system can be used to distribute such notifications.
Oc10 Server already generates These notifications already.


Case closed unless i miss the Point 🤪

**Comment by LukasHirt** [comment]
Created to reference point in Phoenix parity issue:

**updatenotification: M1**
- FE: yellow banner -> use notification mechanism in phoenix
- BE: API, need a way to query from backend

**Comment by LukasHirt** [comment]
@DeepDiver1975 Should I then close this issue?

**Comment by DeepDiver1975** [comment]
yes
