### ISSUE TITLE
Home button in favorites page removes the path of the items

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1384]
### Steps to reproduce
1. set some files and folders in subfolders 
2. navigate to the favorites page
3. click :house: button

### Expected behaviour
nothing should change, as the user is already in a root folder

### Actual behaviour
- URL changes to `index.html#/files/list`
- no path of the files are shown

before clicking the :house: button
![image](https://user-images.githubusercontent.com/2425577/60417460-3be04f80-9c00-11e9-98fb-0c412e5b8e85.png)

after:
![image](https://user-images.githubusercontent.com/2425577/60417488-48fd3e80-9c00-11e9-973c-d4ee542792a3.png)

**Comment by LukasHirt** [comment]
Fixed - closing.
