### ISSUE TITLE
Home icon in trashbin results in white screen of death

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#1403]
![Screenshot from 2019-07-02 16-21-08](https://user-images.githubusercontent.com/1005065/60520290-6c4de980-9ce5-11e9-93e3-76af026f7831.png)

**Comment by LukasHirt** [comment]
I guess it's related to pointing to files/list instead of /?

**Comment by DeepDiver1975** [comment]
no more such icon -> close
