### ISSUE TITLE
One Vue Instance to rule them all

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#146]
The current state of Frontend/Phoenix application development is being questioned in the following:

## Separate Instances - They dance alone
[Sting - They Dance Alone](https://youtu.be/MS_bN5ECJTI)

As of now, Phoenix Apps are standalone instances of whatever JS technology the developer decides on. Communication between apps and to Phoenix happens via APIs _(OC.event)_ restricting apps NOT to know **all the data**, but instead receiving and requesting on a need-to-know basis.

E.g.: Apps that extend the files-app sidebar receive data about files/folders currently being selected. More data can be requested using the js-owncloud-client if needed.

Structural changes do not affect applications as long as the API stays the same, the latter can also live alongside a newer API until it reaches EOL.

### Pros:

- You are free to use and write whatever you feel comfortable with as long as you follow the extension and API guidelines.
- you can determine what plugins can and can't do. Yes, there is a way around that but it's cumbersome and unstable.
- You can easily port your existing app over to Phoenix since "few" changes are necessary to run your app.

### Cons:

- You will have to worry about offline-functionality for yourself as well as PWA support.
- You also have to create your own web pack config which can be a hassle if you are doing it for the first (and even 2nd and 3rd) time.
- Accessing *all the things* is hard to achieve if the necessary APIs don't exist.

## Single Instance - Let's Stay Together
[Al Green - Let's Stay Together](https://youtu.be/XXx6RDzR6eM)

Phoenix already is a running Vue instance that can easily be extended in certain places by registering a new Vue Component.
Store and Router are at your disposal and can be extended, thus having r/w access to everything everywhere. Databinding works in the global context making all the apps reactive to changes by default.

### Pros:

- A unified structure makes it easy for others to understand your app and extend an manipulate it in any possible way. It's the land of the free indeed!
- App bundles are smaller since you don't have to pack Vue and other frameworks do not apply anyways.
- You can keep certain data (kind of) private if you don't write it to the global store.

### Cons:

- You better learn Vue.js or else you can't play with us.
- A Vue.js bug got fixed or feature was added in v2.5.16 but OC.Vue is still @ v2.4.11? Bad luck buddy!
- Files_App decided to rename `filesList` to `fileList`? Your (and probably 20 other) app(s) are likely to break in the next Files_App release.

# What now?

The trend is leaning towards the unified approach as the pros outweigh the cons. The smallest changes have great effects, but professional deprecation management and RC releases give 3rd parties time to adapt.

Reviewing Apps by the OC Staff is easy since the structure and technology is known in-house.

Check out this demo of a [unified Vue instance](https://github.com/felixheidecke/oc-unified-vue-instance).

**Comment by felixboehm** [comment]
FYI https://vuejsdevelopers.com/2017/07/03/vue-js-code-splitting-webpack/

**Comment by DeepDiver1975** [comment]
Just to write down my absolute minimum requirement in terms of integrating other front ends in phoenix:
- add capability to add a new app in the phoenix app menu which allows to render any frontend in a given tag

**Comment by PVince81** [comment]
- [ ] raise PR with WIP changes

**Comment by PVince81** [comment]
PR was merged, closing

**Comment by PVince81** [comment]
@felixheidecke please close the tickets instead of moving to "Done", closing the ticket will do that automatically
