### ISSUE TITLE
codes like %regular% do not have any effect

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1475]
when creating users in tests the code `%regular%` is used. Currently that does not have any effect and the password will be set to the username

**Comment by phil-davis** [comment]
@skshetry someone can look into this. We should fix this sort of thing.
I added to backlog of next sprint. But if there is time in the next days, someone can look at it.

**Comment by skshetry** [comment]
Already looking by Jasmine. Assigning myself for now.
