### ISSUE TITLE
Implement remaining trash bin features

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#1488]
These feature files need to be implemented:
- [x] https://github.com/owncloud/phoenix/blob/master/tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
- [x] https://github.com/owncloud/phoenix/blob/master/tests/acceptance/features/webUITrashbin/trashbinRestore.feature

**Comment by dpakach** [comment]
Some tests for Batch action are remaining from this issue. Since code for batch action was being added in #1514. I didn't added it in this PR. @individual-it I am assigning you for that remaining work.

**Comment by phil-davis** [comment]
@individual-it is there more to do here?

**Comment by individual-it** [comment]
There is more work but I think for now most what is implemented is covered by tests
