### ISSUE TITLE
File actions API

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#149]
A Phoenix app must be able to register custom file actions with handlers.

See the FileActions JS class in core to get an idea:
- `FileActions`, the registry for all file acitons: https://github.com/owncloud/core/blob/master/apps/files/js/fileactions.js#L29
- `FileAction` the object to specify actions: https://github.com/owncloud/core/blob/master/apps/files/js/fileactions.js#L717

@felixheidecke we might want to chat about this at some point

**Comment by PVince81** [comment]
- [ ] make sure to support multiple actions per mime type, etc. For example to make it possible to open text files both with the text editor and Collabora

**Comment by PVince81** [comment]
some file actions will be about viewing and editing files, see https://github.com/owncloud/phoenix/issues/215

**Comment by felixheidecke** [comment]
As discussed with @pvincent:
Apps will be able to register a file-action for the default click (first come, first serve). We will also send the click action to the event-bus so other apps and plugins will be able to pick it up and do whatever as long as it doesn't interfere with the file-action itself.

Optionally, we can have multiple file-actions registered and let the user choose the default app as it's common in windows. _(The preferred app should be saved to the user setting)_

![select_and_ok](https://user-images.githubusercontent.com/12717530/44027184-cff4768c-9ef5-11e8-87fc-d67e7a1fb504.png)

All those file-actions will also be available in the context-menu (right-click and the dot-dot-dot-menu)

**Comment by PVince81** [comment]
The current core API is neither HTTP nor PHP. It's pure JS.
JS apps register actions and specify callbacks.

**Comment by DeepDiver1975** [comment]
> Apps will be able to register a file-action for the default click (first come, first serve).

I would not allow to change the behavior of the default action. I find this very confusing. Furthermore in case two apps register the default action: who wins? 

Furthermore: registered actions can be rather heavy weigthed: collabore, only office, office online.
The fire of full actions on the backend system - we better not trigger that accidentially.

**Comment by PVince81** [comment]
file actions are somehow tied to the file list: ex trashbin has different actions

**Comment by tempelgogo** [comment]
> As discussed with @pvincent:
> Apps will be able to register a file-action for the default click (first come, first serve). We will also send the click action to the event-bus so other apps and plugins will be able to pick it up and do whatever as long as it doesn't interfere with the file-action itself.
> 
> Optionally, we can have multiple file-actions registered and let the user choose the default app as it's common in windows. _(The preferred app should be saved to the user setting)_
> 
> ![select_and_ok](https://user-images.githubusercontent.com/12717530/44027184-cff4768c-9ef5-11e8-87fc-d67e7a1fb504.png)
> 
> All those file-actions will also be available in the context-menu (right-click and the dot-dot-dot-menu)

take a look at the screenshots from https://github.com/owncloud/phoenix/pull/324#issue-231488155

**Comment by PVince81** [comment]
yes. the above is only the "open with" action.
there are other actions like "share", "rename", etc.

**Comment by tempelgogo** [comment]
It is now possible to register multiple actions on a per-filetype basis.
Apps can even provide custom icons for different filetypes e.g. office apps could provide different icons for their registered file extensions.

The app can additionally enable editing feature for it's own filetypes, so they will appear in ActionLauncher if you edit a file instead of just showing it; The App could react accordingly.

As discussed while UX workshop, other actions like share, rename, delete, etc. are not globally available, and therefore not exposed via 'phoenix app registration API'

So it seems, that all requirements of this issue are fulfilled.
I therefore take the liberty of closing this issue; please reopen it at any time if necessary.
