### ISSUE TITLE
Run smoke tests on rootFolder being setup

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#1491]

**Comment by DeepDiver1975** [comment]
I did have a look at this ...

While this looked simple in the first place - it is rather intensive at the end:
- skeleton has to be copied into a subfolder
- all non-ui actions need to be adopted to operate within the subfolder

This requires a too intensive change all over the place - and this feature is very specific.

Closing this issue because of that ...

@LukasHirt

**Comment by LukasHirt** [comment]
I see. Thanks for info.
