### ISSUE TITLE
notifications: disable polling once logged off

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#1500]
Just discovered this today: as soon as the user is logged out - in my case because of token expiry - the notifications polling continues.

we shall not do so.

**Comment by Julian1998** [comment]
That's interesting as the oc topbar vue component should be destroyed. I will have a look

**Comment by DeepDiver1975** [comment]
In some browser this is really annoying - because the browsers auth dialog pops up.

we should also adjust the polling interval to a higher value - 1 sec is pretty DOS'ing .... 30 secs maybe
