### ISSUE TITLE
make sharing autocomplete tests for the case when there are more that 5 items in the list

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1512]
when there are more than 5 items in the autocomplete list our tests fail because the "x more results" button need to be clicked first

**Comment by dpakach** [comment]
Looks like this kinds of tests already exists. Should we close this @individual-it ?

**Comment by skshetry** [comment]
Closing as the tests as this is implemented in https://github.com/owncloud/phoenix/pull/2343
