### ISSUE TITLE
implement `Then all users and groups that contain ... should be listed ... except group "abc"`

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1524]
implement the test step:
`Then all users and groups that contain the string "fi" in their name should be listed in the autocomplete list on the webUI except group "finance1"`

so that more tests from https://github.com/owncloud/phoenix/blob/master/tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature would run

**Comment by jasson99** [comment]
This test step has been implemented in this PR https://github.com/owncloud/phoenix/pull/2343

**Comment by skshetry** [comment]
@jasson99, Closing then ...
