### ISSUE TITLE
user cannot see the parent folder of an item on the trashbin page

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1525]
## Steps to reproduce
similar to #1194 
1. create two files `folder1/lorem.txt` `folder2/lorem.txt` 
2. delete both files
3. navigate to the trashbin page

### Expected behaviour
something should indicate which of the files is which

### Actual behaviour
both items look exactly same

**Comment by Julian1998** [comment]
@DeepDiver1975 @individual-it What's a common way to indicate files in a trashbin?

**Comment by individual-it** [comment]
The old UI does it on hover
![image](https://user-images.githubusercontent.com/2425577/62752540-9aaea980-ba87-11e9-96e8-c0dfe752eff4.png)

what to do for mobile users?

**Comment by individual-it** [comment]
the favorites page in Phoenix shows the parent folder in the file-name row
![image](https://user-images.githubusercontent.com/2425577/62757964-b4a6b700-ba9c-11e9-91ca-59d2e769f825.png)
