### ISSUE TITLE
elements need unique identifier

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#153]
to make UI tests easy and robust we need unique identifiers for every element that a test will interact with (e.g. buttons, links, form elements, lists, etc.)
preferable that unique identifier is an id (that is **unique** in every state of the page - just mentioning is because in core ids are re-used https://github.com/owncloud/core/issues/27870)
If ids are not possible for any reasons we can use other attributes that are unique, e.g. name, data-attributes, css. 

If there are no easy to use identifiers we have to build long, ugly xpath to locate the correct item on the page. That will make the UI tests: 
1. unstable (we might have clicked the wrong button)
1. hard to maintain (the DOM changes and we have to change the xpath)

an article to read https://screenster.io/selenium-locators-best-practices/

**Comment by felixheidecke** [comment]
I am fond of the #id idea … I mean … that's what IDs are for ;-)
Let's talk about naming conventions, so we don't run into collisions, especially in reusable components. Here, we can take advantage of `v-bind:id` by vue.js

**Comment by individual-it** [comment]
Don't know what vue.js does, but don't frameworks generate IDs with magic numbers, if possible it would be good to avoid those

**Comment by felixheidecke** [comment]
Naaa … vue.js doesn't create some random ids. It's all in our hands ;-)

**Comment by PVince81** [comment]
`_.uniqueId()` ?

**Comment by individual-it** [comment]
@pvince81 I fear that would fail because of what I wrote above. How to guarantee that the id is the same in every run? How would the UI know which element to click if the IDs are generated on the fly?

**Comment by felixheidecke** [comment]
@individual-it and @PVince81 ... don't worry guys. I make sure to have persistent identifiers für DOM Elements. Once my PR is ready to review, I'll point out my ID proposal.

**Comment by DeepDiver1975** [comment]
ids are to be added while we implement features and their corresponding acceptance tests. Continuous requirement and doing ....
