### ISSUE TITLE
share autocompletion with username is not possible if user has a display name set

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1532]
### Steps to reproduce
1. Create a user (for eg, with username : ```owncloud1``` and display name ```user1```)
2. Share a file/folder by providing the username ```owncloud1``` in sharing dialog.
     Here, it's not possible to share with user ```owncloud1``` as the displayname is not displayed in the 
     autocomplete dropdown list.
3. Try, sharing by providing ```user1``` in sharing dialog. This time, sharing is possible as we are using the displayname to share.
Also, by typing ```own``` in sharing dialog ```user1``` is not displayed in autocomplete dropdown list.
### Expected behaviour

```displayname``` should be displayed in the share dialog autocomplete list when we type```username``` in the sharing dialog
### Actual behaviour
Sharing with user is only possible using the display name of user and not possible using the username.

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache
**Database:**
SQLite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
11.0.0.0

**Where did you install ownCloud from:**
git

#### Browser log
 The network log :
```network log while sharing using username```
Request URL: http://172.17.0.1/core/ocs/v2.php/apps/files_sharing/api/v1/sharees?search=owncloud1&itemType=folder&page=1&perPage=200&format=json

Response: {"ocs":{"meta":{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK","totalitems":"","itemsperpage":""},"data":{"exact":{"users":[{"label":"user1","value":{"shareType":0,"shareWith":"owncloud1"}}],"groups":[],"remotes":[]},"users":[],"groups":[],"remotes":[]}}}

```network log while sharing using displayname```
Request URL: http://172.17.0.1/core/ocs/v2.php/apps/files_sharing/api/v1/sharees?search=user1&itemType=folder&page=1&perPage=200&format=json

Response: {"ocs":{"meta":{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK","totalitems":"","itemsperpage":""},"data":{"exact":{"users":[{"label":"user1","value":{"shareType":0,"shareWith":"owncloud1"}}],"groups":[],"remotes":[]},"users":[],"groups":[],"remotes":[]}}}

**Comment by LukasHirt** [comment]
This is actually happening in the old UI as well. I'm not sure if this wouldn't maybe require some changes in server.
