### ISSUE TITLE
Drag and drop doesn't work

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1586]
### Steps to reproduce
1. Drag a file into Phoenix

### Expected behaviour
File gets uploaded

### Actual behaviour
Error gets displayed saying File upload failed.

### Setup
**Browser:** https://www.whatismybrowser.com/w/4RB4XG2
**OS:** macOS Mojave version 10.14.5
**Server version:** 10.2.0 (stable)
**Phoenix version:** 0.1.0-c44ed57 (1563784490490)

#### Browser log
```
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8080/remote.php/webdav///%2Fconfig.json
```

```
Access to XMLHttpRequest at 'http://localhost:8080/remote.php/webdav///%2Fconfig.json' from origin 'http://localhost:8300' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by DeepDiver1975** [comment]
>  404 (Not Found) http://localhost:8080/remote.php/webdav///%2Fconfig.json

this is the slashing and encoding issue @Julian1998

**Comment by DeepDiver1975** [comment]
@LukasHirt which browser + version on which OS? THX

**Comment by LukasHirt** [comment]
> @LukasHirt which browser + version on which OS? THX

Right - added.

**Comment by LukasHirt** [comment]
Getting the same errors while trying to upload folder - no matter if I try to do it with drag and drop or through new menu.

**Comment by DeepDiver1975** [comment]
needs retest
