### ISSUE TITLE
Download doesn't work on iOS

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1589]
### Steps to reproduce
1. Open Phoenix on device with iOS
2. Try to download a file

### Expected behaviour
Download gets triggered

### Actual behaviour
Browser gets redirected to new page with URL `blob:` and error saying "The operation couldn't be completed. (WebKitBlobResource error 1.)

**Comment by DeepDiver1975** [comment]
Blob is Not supported it seems 🤯

**Comment by DeepDiver1975** [comment]
@LukasHirt can you find out which version of ios/safari you tested this with?

According to https://caniuse.com/#search=blob it should be working ....

**Comment by LukasHirt** [comment]
@DeepDiver1975 It is actually not blob related. It's because of iOS not supporting download https://caniuse.com/#feat=download It will come in iOS 13 but from what I found only to iPad. I found two possible solutions - (1) using FileReader and (2) using the download link provided in server. With 1st solution, I'm having troubles that the name is untitled now.

**Comment by PVince81** [comment]
pre-signed download URLs ?

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/phoenix/issues/526.

better invest the time to make download work using pre-signed URL than finding workarounds to perpetuate the current approach
