### ISSUE TITLE
more collaborators tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1614]
scenarios copied from old webUI does not work, because the workflow changed see https://github.com/owncloud/enterprise/blob/master/product/oc10/index.md#collaborators
Some tests were implemented, but by far not enough.
missing e.g.
- resharing
- changing collaborators type - #2124
- allow / disallow resharing
- unshare as receiver/sender
- etc.

**Comment by phil-davis** [comment]
@dpakach and @skshetry are working on tests for these. They will make individual issues for each item they are working on, and link back to here as the "main" issue.
