### ISSUE TITLE
Sharing UI not guiding thru the process

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#1640]
This issue popped up while working on the Links. After selecting a user/group from the dropdown, I **genuinely thought it was done** (Especially coming from oc10). It only occurred to me that something was "wrong" while I was clicking on other files, while the sidebar was open and it still showed the supposed share.

### Problems:

- No Indication of the shared state (Am I done?)
- No clear indication on what to do next (What's next?)
- **All other elements on the page can interact with, which can cancel the share without telling me.**
- **I can select other files while sharing isn't done. Will share the selected file, not the one I started with.**

### Solutions:

- Indicate a clear start and end of the sharing process
1) Select user/group, 2) select role, 3) confirm and share
- Focus on sharing, hide/disable other functions

---

## Am I done, yes? no? … what's up?
![share 01](https://user-images.githubusercontent.com/12717530/62037098-6b7c7a80-b1f3-11e9-9445-f978fd225d1c.png)

## Ahaaaa … this is what's next
![share-02](https://user-images.githubusercontent.com/12717530/62037355-ed6ca380-b1f3-11e9-93e2-83251d21d3de.png)

---

As I designed this a while ago:

- Clear focusing on sharing process.
- Grey area is out of focus, as its not part of the current task.
- Sharing is **either done or has been canceled** when the modal closes/ is closed.

![sharing](https://user-images.githubusercontent.com/1005065/52936248-e21b6f00-335b-11e9-9829-8d14976ecfae.png)

---

@LukasHirt @DeepDiver1975 @pmaier1 @michaelstingl

**Comment by felixheidecke** [comment]
The problem becomes more prevalent on small devices. Half of the sharing process is way below without indication!

![FireShot Capture 031 - ownCloud Phoenix - 127 0 0 1](https://user-images.githubusercontent.com/12717530/62037860-e5f9ca00-b1f4-11e9-881d-725fbfa30107.png)

**Comment by DeepDiver1975** [comment]
This feedback needs to go into the next UW review and explicit actions need to be agreed on. Keeping open for the time being ...

**Comment by LukasHirt** [comment]
Since we separated the process into the tabs can we close this? @PVince81
