### ISSUE TITLE
"Pending Shares" breaks Phoenix

### ISSUE THREAD

**Issue by pmaier1** [owncloud/phoenix#1667]
... or is it just a "notification that requires an action" that breaks things?

**Steps to reproduce**
1. Have two users, `Alice` and `Bob`
2. Have the option `Automatically accept new incoming local user shares` in admin 'Sharing' settings set to `disabled` (aka "Pending Shares" enabled)
3. As `Alice` share a resource with `Bob`
4. Log in as `Bob`

**Expected behavior**
Bob can log in as usual, the file list and rest of the UI loads and he has an unread notification that tells him about the pending share and offers to accept or decline it.

**Actual behavior**
Loading freezes somewhere in between and the user can't do anything.

**Comment by LukasHirt** [comment]
Hmm, just tried that and seemed to work. No loading and notification displayed. But there is another issue anyway with it - missing accept or decline in the notification.

**Comment by DeepDiver1975** [comment]
I'm about to update the demo system to core 10.2.1 ... FYI
