### ISSUE TITLE
Manual QA testing of Phoenix

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1681]
## Description
We are coming closer to the first milestone so we are in need to do some manual testing to catch as much 🐛 possible. Try to do overall testing pls and try to break it :grin:

**Comment by DeepDiver1975** [comment]
Some IE11 and FireFox testing would be great - also some mobile testing might be reasonable.

**Comment by pmaier1** [comment]
- See my findings here https://github.com/owncloud/phoenix/issues/1186#issuecomment-516343439
- We need to gather our findings and make sure that the learnings go back into the requirements/product doc and low-level feature files where applicable.

**Comment by LukasHirt** [comment]
@individual-it Do you still plan to work on this? Can we close this and focus on fixing found bugs?

**Comment by individual-it** [comment]
I think we have tested the current state well enough. Lets focus on fixes and automated tests
