### ISSUE TITLE
Search files

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#172]
- [ ] filter files in current folder based on file name pattern
- [ ] search in files in multiple folders: integrate with https://github.com/owncloud/documentation/issues/4241 to provide the ability to search for files in multiple folders

It is not clear yet whether we still want to have a global search field at the top right which is supposed to search more than just files (also calendars, contacts) or have another field in the files app for files-only search.

**Comment by DeepDiver1975** [comment]
- needs change in js-owncloud-client

**Comment by DeepDiver1975** [comment]
>     * filter files in current folder based on file name pattern

filtering can be done pure client side since we hold the full file list of the current folder in the client



>     * search in files in multiple folders: integrate with https://github.com/owncloud/documentation/issues/4241 to provide the ability to search for files in multiple folders

this is to be done by using OwnCloud.files.search

**Comment by DeepDiver1975** [comment]
There will be two issues on their own. one for filter and one for search
