### ISSUE TITLE
restoring the first of multiple items with the same name from the trashbin shows the wrong item remaining in the trashbin

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1723]
similar to #1385

### Steps to reproduce
1. create a file `a1.txt`
2. delete the file
3. create a folder `a1.txt`
4. delete the folder
5. navigate to `DELETED FILES`
6. restore the file `a1.txt` (should be first in list)

### Expected behaviour
the file should not be listed in the trashbin

### Actual behaviour
the folder is not listed in the trashbin, the file is listed in the trashbin
the file was restored, so that is correct

**Comment by LukasHirt** [comment]
Tested now with Phoenix version `Version: 0.2.7-9fa84171 (1579092217051)` and works fine. Can you pls retest? @individual-it

**Comment by individual-it** [comment]
seems to work, need to add tests to prevent future regressions,
added QA-team label and added to the sprint

**Comment by swoichha** [comment]
After restoring the file a1.txt, when the user tries to restore the folder a1.txt,  "restoration failed" error is shown.

**Comment by individual-it** [comment]
@swoichha that is covered in #1730

**Comment by individual-it** [comment]
tests done, closing issue
