### ISSUE TITLE
a single file cannot be deleted from trashbin

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1724]
caused by https://github.com/owncloud/core/issues/35997

**Comment by DeepDiver1975** [comment]
@individual-it please retest - works for me with current owncloud/core master branch. Also works on demo system ...

**Comment by individual-it** [comment]
@DeepDiver1975 have you reloaded the page after deleting the file from trashbin?

![out](https://user-images.githubusercontent.com/2425577/63163081-17bbbf00-c044-11e9-9e15-41a443cb7a74.gif)

https://github.com/owncloud/core/issues/35997 is still open and the core of this problem
see my comment there https://github.com/owncloud/core/issues/35997#issuecomment-521974748

**Comment by LukasHirt** [comment]
@individual-it Tested now with master of core after https://github.com/owncloud/core/pull/36073 was merged. Seems to work fine now. Can you test again so we can see if we can close it or should do some more debugging?

**Comment by individual-it** [comment]
tested, and seems to work - need acceptance tests
adding QA-team label for that

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/phoenix/pull/2237
