### ISSUE TITLE
can't cancel the overwrite of file

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1732]
### Steps to reproduce
1. Create a file ( for eg: ```oc.txt```)
2. Upload a file with the same name ('```oc.txt```). 
3. Cancel the overwrite of the file

May be the ```Cancel``` button is not implemented. But ```Ok``` button works fine.
### Expected behaviour
Canceling of the overwrite should be possible

### Actual behaviour
It's not possible to cancel the overwrite of file.

**Comment by DeepDiver1975** [comment]
Fixed meanwhile - tested on demo system
