### ISSUE TITLE
Renaming of a file in favourites page to that of already existing file in files page overwrites that file

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1734]
### Steps to reproduce
1. Create two file .eg. ```oc1.txt``` and ```oc2.txt```
2. Add ```oc1.txt``` to favourites
3. Browse to favourites page and rename ```oc1.txt``` to ```oc2.txt```
4. Browse to the files page. Here only ```oc2.txt``` is listed and its content is that of ```oc1.txt``` i.e. original ```oc2.txt``` is overwritten

### Expected behaviour
It should not be possible to rename a file to already existing file name

### Actual behaviour
It's possible to overwrite already existing file from favourites page

**Comment by DeepDiver1975** [comment]
closing this - we disallow renaming on fav page - see #1750
