### ISSUE TITLE
Can't assign legacy option in Collaborators

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1747]
### Steps to reproduce
1. Share a file or folder to a user. By default sharee will be ```Co-owner``` of the shared file.
2. Try to change sharee from ```Co-owner``` to ```Legacy``` in Collaborators. You can't.
![legacy](https://user-images.githubusercontent.com/34328907/62753128-eb270680-ba89-11e9-814a-6c1b312b805e.png)

### Expected behaviour
It must be possible to change the role of sharee to ```Legacy```

### Actual behaviour
Sharing the role of sharee to ```Legacy``` is not possible

**Comment by LukasHirt** [comment]
Legacy role was replaced with custom role. Also the design in the screenshot is really old... Pls check if you have pulled newest changes.
