### ISSUE TITLE
Collaborators role falls back to Editor

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1757]
### Steps to reproduce
1. Assign collaborator for a file ```oc.txt``` to user ```user1``` as ```Viewer```
2. Even though the role assigned is ```Viewer``` it falls back to ```Editor``` and the sharee(```user1```) can edit the shared file.

### Expected behaviour
Role assigned as ```Viewer``` must be a ```Viewer``` not an ```Editor```

### Actual behaviour
```Viewer``` Role falls back to ```Editor```

**Comment by LukasHirt** [comment]
Check pls again. Should be fixed with #1718

**Comment by HariBhandari07** [comment]
@LukasHirt still not fixed.
