### ISSUE TITLE
Collaborators custom role permissions doesn't work

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1758]
### Steps to reproduce
1. Assign collaborator for a folder ```OC``` to user ```user1``` and set custom permissions as:
    - can share : no
    - can change: no
    - can create: no
    - can delete: no
2. As ```user1``` you can violate all the set permissions for folder ```OC```

### Expected behaviour
```user1``` should not be able to violate permissions set for ```folder1```

### Actual behaviour
```user1``` can violate set permissions for folder ```OC```

**Comment by DeepDiver1975** [comment]
> `user1` can violate set permissions for folder `OC`

@HariBhandari07 please clarify what you mean by this - THX a lot

**Comment by HariBhandari07** [comment]
I checked it again. Seems like it is fixed.
