### ISSUE TITLE
file names are not visible in trashbin page while browsing through mobile phone

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1760]
### Steps to reproduce
Using your mobile phone:-
1. Delete some files and browse to the trashbin page.
   Here file name is not displayed
 
![1](https://user-images.githubusercontent.com/34328907/62773826-ea5e9680-bac2-11e9-886e-ac6374a5ee1a.png)

2. Also you have to scroll right to get restore option, which is not a good design
  
![2](https://user-images.githubusercontent.com/34328907/62773899-1d088f00-bac3-11e9-97db-2c4bc7d8ab8f.png)

### Expected behaviour
File name must be displayed in trashbin

### Actual behaviour
File name is not properly displayed in trashbin

**Comment by LukasHirt** [comment]
Related to #1890
