### ISSUE TITLE
tests for collaborators permissions 

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1768]
we need more tests for issues like  #1718

**Comment by LukasHirt** [comment]
@individual-it Can be closed now since #1761 has been merged?

**Comment by individual-it** [comment]
I think I should add more tests next week

**Comment by LukasHirt** [comment]
Ok, thanks for info

**Comment by individual-it** [comment]
tests added in  #1885 & #1838

@HariBhandari07 anything left to tests?
