### ISSUE TITLE
Can't accept or decline federation share using mobile phone

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#1785]
### Steps to reproduce
1. From OC server share a file/foder to another server's user
2. Using phoenix and as a receiver try to accept the federated share. But you can't accept or decline the share as the dialog is not shown properly.
![2](https://user-images.githubusercontent.com/34328907/62931322-e04bd900-bddd-11e9-81c3-d7c86bec3042.png)

### Expected behaviour
```Accept``` and ```Decline``` button must be displayed properly as in the screenshot of OC server shown below:
![3](https://user-images.githubusercontent.com/34328907/62931370-f9ed2080-bddd-11e9-88b6-b2cf2249e3a5.png)

### Actual behaviour
User can't accept or decline the federated share

**Comment by LukasHirt** [comment]
Refs #1505

**Comment by DeepDiver1975** [comment]
closing - dupe
