### ISSUE TITLE
sharing a file to an other user as "Editor" makes the UI unusable

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1788]
### Steps to reproduce
1. share a file to a user as "Editor"
2. login as that receiver

### Expected behaviour
UI should work fine

### Actual behaviour
UI is not usable

the problem is a combination of #1787 and https://github.com/owncloud/core/issues/36025

**Comment by individual-it** [comment]
the UI is still unusable when receiving a share with permission "2" see https://github.com/owncloud/core/issues/36025
Do you want to deal with that in a separate issue? Or wait till the issue in core is resolved?

**Comment by LukasHirt** [comment]
I want to wait first so I see how it will be handled there.
