### ISSUE TITLE
file download does not work on password protected public shares

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1808]
### Steps to reproduce
1. create a public link share of a folder
2. try to download a file from within that folder via public link

### Expected behaviour
file should be downloaded

### Actual behaviour
file cannot be downloaded

### Client configuration
**Browser:**
Chrome

#### Browser log
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
core.bundle.js:75 Error: Unauthorized
    at core.bundle.js:75```

**Comment by VicDeo** [comment]
I can't login to view a password protected share at all...

**Comment by LukasHirt** [comment]
Fixed in #1895 there was missing getter for the password which broke the authorization header. Needed to fix it in order for the other PR to fully work so I went ahead and did it there.

**Comment by LukasHirt** [comment]
> I can't login to view a password protected share at all...
> When I enter an incorrect password I see a message in OC log. When the password is correct OC log is empty but the password popup still reappears.

@VicDeo Hmm, that is strange. Do you get some errors in the browser console? Or the network tab?

**Comment by VicDeo** [comment]
@LukasHirt I sorted it out already, I had a browser a naggy auth popup there that has nothing to do with a real auth page.
