### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by labkode** [owncloud/phoenix#1833]
* Public link deletion does not trigger a popup for confirmation, compared to deleting a file or a user share, restoring the public link is not possible
* Sidebar tranistions (sharing, left menu) are abrupt, harsh to the the end-user experience
* No sortable headers in files view
* Hovering the mouse over the favourite start does not trigger a change in the cursor (probably because it isn't a link), the checkbox does it.
* File creation does not jump created item in the scrollable view
* Updating link fails with an error
* Expiration date input on public link is free form, no calendar pop-up.
* The creation of a public link doesn't show the public link URL, user has to click the chain symbol to get it copied, it is not intuitive.
* The plus (+) button close to the collaborator in the share dialog I clicked it to add a new collaborator and I discovered it is for expanding the collaborator info, therefore a dropdown/chevron icon suits better.

**Comment by felixboehm** [comment]
thanks for the feedback. we will improve the points you brought up.
@LukasHirt please follow up on these points...

**Comment by DeepDiver1975** [comment]
@labkode please share the version you tested. Did you test a local deployment or on phoenix.owncloud.com.

THX

**Comment by labkode** [comment]
phoenix.owncloud.com

**Comment by LukasHirt** [comment]
> Updating link fails with an error
> Expiration date input on public link is free form, no calendar pop-up.
> The creation of a public link doesn't show the public link URL, user has to click the chain symbol to get it copied, it is not intuitive.

Being taken care of in #1827

> No sortable headers in files view

Issue for this - #1854

> The plus (+) button close to the collaborator in the share dialog I clicked it to add a new collaborator and I discovered it is for expanding the collaborator info, therefore a dropdown/chevron icon suits better.

Issue for this - https://github.com/owncloud/owncloud-design-system/issues/473

> Hovering the mouse over the favourite start does not trigger a change in the cursor (probably because it isn't a link), the checkbox does it.

Issue for this - #1645

> Sidebar tranistions (sharing, left menu) are abrupt, harsh to the the end-user experience

Issue for this - #1855

> File creation does not jump created item in the scrollable view

Issue for this - #1856

**Comment by LukasHirt** [comment]
> Public link deletion does not trigger a popup for confirmation, compared to deleting a file or a user share, restoring the public link is not possible

This doesn't happen also for collaborators. Needs to be implemented yet. Do we need plan to have a restore option for them though?

**Comment by labkode** [comment]
Thanks you Lukas for creating the issues.



> This doesn't happen also for collaborators. Needs to be implemented yet. Do we need plan to have a restore option for them though?

Maybe I have not been clear enough, let me correct that :)

After creating a public link, the link is shared using a unique random token, so if you delete the public link any references to it will stop working; even if you create a new one, it will be different.

For this reason, I think warning the user for deleting public links should be encouraged, that references to the public link will no be accessible anymore; if by mistake you click it, you can cause discomfort amongst the recipients of your link.

For user/group shares, removing and re-creating them is not a big deal, as there isn't a unique token that change.

**Comment by LukasHirt** [comment]
@labkode Thanks a lot for clarifying!

**Comment by LukasHirt** [comment]
Created issue also for the confirmation dialog - #1872 Will close this issue now and specific tasks will be taken care of in their related issue.
