### ISSUE TITLE
Files list needs to be sortable

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1854]
## Description
User needs to be allowed to sort the files list. Either having clickable header rows which would sort it or have somewhere a sort by drop (maybe better since on mobile view we hide almost every header row)

**Comment by PVince81** [comment]
In the current design I was expecting to find it under the filter icon on the top right.

**Comment by PVince81** [comment]
even if we don't provide an option yet, at least I think we should properly sort it to have the folders on top, instead of this:
<img width="947" alt="image" src="https://user-images.githubusercontent.com/277525/64876637-dcff7380-d64f-11e9-8446-8345395d7aca.png">

**Comment by PVince81** [comment]
This is the client side JS sorters from the old UI: https://github.com/owncloud/core/blob/master/apps/files/js/filelist.js#L3065

**Comment by PVince81** [comment]
Draft (broken) PR for default sort: https://github.com/owncloud/phoenix/pull/1972

**Comment by LukasHirt** [comment]
I think it would be nice to have as well some advanced sort options in the future e. g. "Shared items first" or "Favourite items first".

**Comment by PVince81** [comment]
Nice idea.

We need to be careful to not overwhelm the user with too many options. We should think about the common use cases and provide a few sorting options for that.

Last time I asked you where to put the sort options and we agreed on using a dropdown instead of clickable columns. This aligns with the idea of providing sort options that do not match specific columns.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/phoenix/pull/3078

**Comment by PVince81** [comment]
- [ ] aria label for sort indicator

**Comment by PVince81** [comment]
- [ ] own vue component for clickable sort column, there's already too much markup...
