### ISSUE TITLE
Jumpy error message in folder creation dialog

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#1906]
### Steps to reproduce
1. Create a folder "test" and validate.
2. Create another folder and type "test" in the dialog

### Expected behaviour
Smooth error message

### Actual behaviour
Error message brutally appears as soon as I hit the last "t" and pushes the whole UI down.
It feels painful when my eyes focus on the field while I'm typing and suddenly it jumps down.

Not sure if adding a smooth animation here would help or whether we push the error message below the field ?

### Version
Phoenix master 2f7b3d781175e63a45291127bb3d2dfc3cfa5153

**Comment by LukasHirt** [comment]
I think pushing it bellow would be a better solution. Also dropping the whole frame and using only a red text + change the border colour of the input to red maybe?

**Comment by jnweiger** [comment]
Suggestion: Put the message next to the [OK] button. It belongs there, as it explains why the button is grayed out. That is also 'below', and nothing jumps up and down any more.
