### ISSUE TITLE
Role interaction not consistent between collaborators and link share

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#1907]
### Feedback
Link share has a radio group for roles and takes a lot of vertical space:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/277525/64350558-2705ab00-cff9-11e9-8e66-ba8fff702b0f.png">

(also see [font size is too big](https://github.com/owncloud/phoenix/issues/1902) issue)

User share has a single line with dropdown that appears when clicked:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/277525/64350639-48669700-cff9-11e9-8dee-64bcd33f836f.png">

To save vertical space, especially on screens like mine, it might be better to always use the "single line role" pattern also for the public link shares.

If we consider that a user is already familiar with how roles work, it might be a good idea to always provide them with the same experience: same controls, same interaction.

### Version
Phoenix master 2f7b3d781175e63a45291127bb3d2dfc3cfa5153

**Comment by wuenschedesign** [comment]
The following Screens show a different approach to create a public link in the sidebar without making a modal.

Screen (1)
User starts creating a public link:

![Sidebar-01](https://user-images.githubusercontent.com/40062503/67412671-ffc26780-f5bf-11e9-9f27-1d2dbc1fe2ce.png)

Screen (2)
Screenview when changing the role:

![Sidebar-02](https://user-images.githubusercontent.com/40062503/67412491-ae19dd00-f5bf-11e9-8eb3-abfaa4a71f12.png)

Screen (3)
A completely filled sidebar including an open date picker:

![Sidebar-03](https://user-images.githubusercontent.com/40062503/67412519-ba9e3580-f5bf-11e9-9ae1-6ee04ee9b46d.png)

Screen (4)
Public Link added in the sidebar:

![Sidebar-04](https://user-images.githubusercontent.com/40062503/67412571-d3a6e680-f5bf-11e9-9da7-7764292a1e93.png)

**Comment by wuenschedesign** [comment]
New drafts for creating public link:

![Links-01](https://user-images.githubusercontent.com/40062503/68395113-6bcfce80-016f-11ea-944d-e5cb9b035df9.png)
![Sidebar-Public-Link-01](https://user-images.githubusercontent.com/40062503/68394638-82c1f100-016e-11ea-9735-b6b6ffafaee7.png)
![Sidebar-Public-Link-02](https://user-images.githubusercontent.com/40062503/68394640-82c1f100-016e-11ea-8afb-15e9fa40d798.png)
![Sidebar-Public-Link-03](https://user-images.githubusercontent.com/40062503/68394642-835a8780-016e-11ea-8dc3-eb887b6a5615.png)
![Sidebar-Public-Link-04A](https://user-images.githubusercontent.com/40062503/68394781-c0bf1500-016e-11ea-9a45-29f5f7f754e7.png)

**Comment by PVince81** [comment]
for email field, let's implement later on: https://github.com/owncloud/phoenix/issues/2422

**Comment by wuenschedesign** [comment]
Additional layout for the public link creation:

Layout:
![List-View-Creating-Public-Link](https://user-images.githubusercontent.com/40062503/69144693-221aa880-0acc-11ea-8db2-f7bd33a98edc.png)

Layout with comments:
![List-View-Creating-Public-Link-comments](https://user-images.githubusercontent.com/40062503/69144692-21821200-0acc-11ea-80fa-c0122f124810.png)

**Comment by wuenschedesign** [comment]
We also need a concept how to define the process of creating a public link.

1) Prompt for informing a user that he is about to cancel the process:
![List-View-Creating-Public-Link-Cancel](https://user-images.githubusercontent.com/40062503/69145514-162fe600-0ace-11ea-9617-4b7a507e8c0c.png)

2) Notification for the user that he has created a public link (even, if he unintentionally clicked somewhere else). Alternatively no link will be created, as long as the user didn’t input any information:
![List-View-Creating-Public-Link-Succesfully-created](https://user-images.githubusercontent.com/40062503/69145532-28118900-0ace-11ea-9ff2-1472e619fb30.png)

**Comment by PVince81** [comment]
Update: we decided to go with the "in-panel" editing where a new panel comes and overlap.

This approach was already used for collaborators and now need to be applied for the public link workflows as well. Please ignore the above mock ups which were part of an older design.

@wuenschedesign did we have updated mock ups somewhere in another ticket ? Somehow I can't find them any more. It's not a big issue as developers can simply align the design of public links with the current one from collaborators (and reuse the existing Vue components like the roles selector)

@kulmann @micbar

**Comment by wuenschedesign** [comment]
> @wuenschedesign did we have updated mock ups somewhere in another ticket ? Somehow I can't find them any more. It's not a big issue as developers can simply align the design of public links with the current one from collaborators (and reuse the existing Vue components like the roles selector)

In which way should they be updated?

**Comment by PVince81** [comment]
@wuenschedesign the mock ups above are outdated as they show the modal approach.

I thought we already had some where the public link panel editing was represented, maybe in some other ticket ?

**Comment by kulmann** [comment]
Any news on this for mockups? ;-) Not necessary, but would still be helpful. @PVince81 @wuenschedesign
