### ISSUE TITLE
Confusing layout in collaborators UI

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#1908]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/277525/64350865-a6937a00-cff9-11e9-9c78-178b38abb6ae.png">

I think we should only ever expand a single collaborator.

Whenever an interaction is not finished, for example the user forgot to save, we should remind and ask "save or cancel" and then collapse that one and open whichever other panel the user just clicked.

An alternative or addition would be a better visual separation, not sure if a [divider](https://getuikit.com/docs/divider) would do, or putting each panel into [cards](https://getuikit.com/docs/card).

### Version
Phoenix master 2f7b3d781175e63a45291127bb3d2dfc3cfa5153

**Comment by PVince81** [comment]
<img width="57" alt="image" src="https://user-images.githubusercontent.com/277525/66812198-bb392b00-ef32-11e9-8252-c277c929d9da.png">

I think we need to reconsider the flow when creating link shares and collaborator shares as a lot of the UI is distracting and confusing.

**Comment by PVince81** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/277525/66814591-2684fc00-ef37-11e9-892f-d81798fe6338.png">

**Comment by PVince81** [comment]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/277525/66814615-3270be00-ef37-11e9-8d29-5b5ff37d80ff.png">

**Comment by PVince81** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/277525/66814650-41577080-ef37-11e9-9216-e7f8336eb9b2.png">

**Comment by PVince81** [comment]
<img width="385" alt="image" src="https://user-images.githubusercontent.com/277525/66814664-49171500-ef37-11e9-8cb6-5812fc60ec82.png">

**Comment by PVince81** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/277525/66814686-516f5000-ef37-11e9-80dd-a606766a90a9.png">

**Comment by PVince81** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/277525/66814699-58965e00-ef37-11e9-9908-31775db56314.png">

<img width="360" alt="image" src="https://user-images.githubusercontent.com/277525/66814710-5e8c3f00-ef37-11e9-96ef-b83ec11831bc.png">

**Comment by PVince81** [comment]
## Second collaborator

<img width="369" alt="image" src="https://user-images.githubusercontent.com/277525/66814747-6e0b8800-ef37-11e9-924b-f6c9f1249353.png">

<img width="354" alt="image" src="https://user-images.githubusercontent.com/277525/66814770-72d03c00-ef37-11e9-9084-faecb05ecc95.png">

<img width="356" alt="image" src="https://user-images.githubusercontent.com/277525/66814786-7794f000-ef37-11e9-82db-5934044c719e.png">

<img width="282" alt="image" src="https://user-images.githubusercontent.com/277525/66814800-7d8ad100-ef37-11e9-960c-3b469e9ba680.png">

- [ ] need confirmation when changing permissions ?

**Comment by PVince81** [comment]
## Removing collaborator

<img width="277" alt="image" src="https://user-images.githubusercontent.com/277525/66814897-a14e1700-ef37-11e9-963f-4281a33da728.png">

**Comment by PVince81** [comment]
- [ ] when navigating away with pending changes, need warning

**Comment by wuenschedesign** [comment]
<img width="1440" alt="Collaborators-01" src="https://user-images.githubusercontent.com/40062503/67267179-15e20200-f4b2-11e9-9c9d-860d00e17c30.png">
<img width="1458" alt="Collaborators-02" src="https://user-images.githubusercontent.com/40062503/67267180-15e20200-f4b2-11e9-931f-2dfbe66a7993.png">
<img width="1458" alt="Collaborators-03" src="https://user-images.githubusercontent.com/40062503/67267181-15e20200-f4b2-11e9-8f4f-6fadfa06583a.png">
<img width="1458" alt="Collaborators-04" src="https://user-images.githubusercontent.com/40062503/67267182-167a9880-f4b2-11e9-9c7b-9c68d2cc270f.png">
<img width="1458" alt="Collaborators-05" src="https://user-images.githubusercontent.com/40062503/67267183-167a9880-f4b2-11e9-9dfb-ff1e4e5b914b.png">
<img width="1458" alt="Collaborators-06" src="https://user-images.githubusercontent.com/40062503/67267184-167a9880-f4b2-11e9-93ec-afbe9f97d658.png">
<img width="1458" alt="Collaborators-07" src="https://user-images.githubusercontent.com/40062503/67267186-167a9880-f4b2-11e9-964a-ab56b5d4d694.png">
<img width="1458" alt="Collaborators-08" src="https://user-images.githubusercontent.com/40062503/67267187-167a9880-f4b2-11e9-8bc0-75148ba5766b.png">
<img width="1458" alt="Collaborators-10" src="https://user-images.githubusercontent.com/40062503/67267693-1e870800-f4b3-11e9-8e5c-644997b6a298.png">
<img width="1458" alt="Collaborator-11" src="https://user-images.githubusercontent.com/40062503/67267784-51c99700-f4b3-11e9-87a9-30fc57fa4d88.png">

**Comment by wuenschedesign** [comment]
![Collaborators-Add-Collaborators](https://user-images.githubusercontent.com/40062503/67268956-0795e500-f4b6-11e9-8e6f-10780767d770.gif)

**Comment by PVince81** [comment]
With @pmaier1 @wuenschedesign and @LukasHirt we reviewed the above proposal.

Discussion result:
- modal looks fine here for everyone (we got the confirmation that accessibility can be made to work with modals)
- also happy that the accordion is gone
- we need to work on the roles because @wuenschedesign had troubles understanding the mix between selecting a role and additionally picking "can share": @pmaier1 to look into providing additional roles that also include the "can share" permission to get rid of the extra checkbox
- "custom role" confusing for @LukasHirt as it sounds like we are creating a new role: let's rename it to "advanced permissions" or something alike to make it clear that it's not a standard action
- next up @wuenschedesign will provide mock ups for the public link dialogs as a similar modal for next week for review
- we'll need to work on including the roles dropdown into the above design
- also discussed: the concept of unified links and also having a single edit field for creating public links and direct shares => to be deferred for a later point as the goal is to iterate first and have a UI that is one iteration better instead of doing a whole overhaul of the concepts.

I also think that once we have this design in place we should do some usability testing to validate the idea and refine it.

**Comment by PVince81** [comment]
- [ ] another approach to explore:
    - ability to create shares directly in the panel, but in a simplified form with default role
    - then on the row of the collaborators the user can edit the role if they want something different
    - additionally there could be a way to select a role to pick for the collaborators to add
    - expiration date could then also be in the dialog and not in the default view

the above is to be considered because the proposal with the modal introduces an additional click for users to share, which might not be good for something we'd consider a common action

**Comment by PVince81** [comment]
@wuenschedesign please make another proposal for both "public links" and "collaborators" in a full page.

Modals are **no go** according to @felixboehm due to mobile experience and the fact that the contents of the dialog might be extended by apps with more roles and permissions which might blow up the size of the component. So putting this in a separate page should work better.

Might need to think about the route, header, footer, etc for said page.

**Comment by PVince81** [comment]
Futher notes:
- full page would have more space to add more description for every role
- we must keep the flexibility of permissions for users
- in the future we will likely add the possibility for admins (or even users) to manage the list of roles that are displayed

**Comment by wuenschedesign** [comment]
This screen shows an attempt to implement role and custom permission setting
![Add-Public-Link-C-01](https://user-images.githubusercontent.com/40062503/67302045-9162a400-f4f0-11e9-9da8-9654b606354a.png)

**Comment by wuenschedesign** [comment]
Advanced UI for role and permission setting. The user selects a predefined role via pulldown (as implemented right now) and sees a checkbox list with the correspondent permissions ticked:
![Add-Public-Link-D-01](https://user-images.githubusercontent.com/40062503/67302545-53b24b00-f4f1-11e9-962d-55a904e555d0.png)
![Add-Public-Link-D-02](https://user-images.githubusercontent.com/40062503/67302548-544ae180-f4f1-11e9-9625-92f35bfd7db0.png)
![Add-Public-Link-D-03](https://user-images.githubusercontent.com/40062503/67302549-544ae180-f4f1-11e9-8631-b3e5866e3677.png)
![Add-Public-Link-D-04](https://user-images.githubusercontent.com/40062503/67302551-544ae180-f4f1-11e9-973b-67a26a2cb2e2.png)

**Comment by wuenschedesign** [comment]
This UI flow shows how a defined role can be created on the go. 1) The user selected one of the roles in the pulldown. 2) user ticks or unticks additional checkboxes 3) user gets a link for saving the permission setting as a new role 4) Pulldown List contains the new role.

![Add-Custom-Role-01](https://user-images.githubusercontent.com/40062503/67302727-9aa04080-f4f1-11e9-8880-90349e5c032f.png)
![Add-Custom-Role-02](https://user-images.githubusercontent.com/40062503/67302734-9c6a0400-f4f1-11e9-9185-8bd4b3d3a4ad.png)
![Add-Custom-Role-03](https://user-images.githubusercontent.com/40062503/67302736-9d029a80-f4f1-11e9-94cb-3dfc3c7a74e4.png)
![Add-Public-Link-D-07](https://user-images.githubusercontent.com/40062503/67302895-e2bf6300-f4f1-11e9-9df1-27434964d266.png)

**Comment by felixboehm** [comment]
Roles should not be defined on-the-fly while creating a share, as this needs very specific permissions. And Roles are defined system wide, not per user.

There will be a dedicated page to manage roles (later)

**Comment by PVince81** [comment]
Agreed, this is a misunderstanding with @wuenschedesign.

@wuenschedesign maybe for it to be clearer to you, please completely remove any checkboxes you added for roles in the UI. No custom role or anything, just an indication about what permissions are covered by the selected role, like a description text. This might remove some confusion. Then when we're there we can discuss the OC 10 compatibility scenario in the next iteration.

**Comment by PVince81** [comment]
also missing: the name/path of the file/folder for which we are creating the share. Since this is full page the user might not remember what they selected.

**Comment by wuenschedesign** [comment]
The following screens showing, which folder the public link will be created. I am still keeping the additional checkboxes for permissions (like talked about at ownCloud HQ). If not neccessary, they can just be left.

![Add-Public-Link-F-01](https://user-images.githubusercontent.com/40062503/67632731-b61b9a80-f8a7-11e9-8d10-caf6c6848a7a.png)
![Add-Public-Link-F-02](https://user-images.githubusercontent.com/40062503/67632732-b61b9a80-f8a7-11e9-923c-8080fd7a2cdd.png)

**Comment by wuenschedesign** [comment]
New drafts for the collaborators invite:

![Sidebar-Collaborator-00](https://user-images.githubusercontent.com/40062503/68395476-13e59780-0170-11ea-94b1-0fdd52fd4f1e.png)
![Sidebar-Collaborator-01](https://user-images.githubusercontent.com/40062503/68395233-a3d71180-016f-11ea-9a10-2d708dbce3cf.png)
![Sidebar-Collaborator-02](https://user-images.githubusercontent.com/40062503/68395234-a46fa800-016f-11ea-8536-7bbff16eaf2a.png)
![Sidebar-Collaborator-03](https://user-images.githubusercontent.com/40062503/68395235-a46fa800-016f-11ea-84ed-e16b56019b11.png)
![Sidebar-Collaborator-04](https://user-images.githubusercontent.com/40062503/68395236-a46fa800-016f-11ea-99a9-43e52e48d771.png)
![Sidebar-Collaborator-05](https://user-images.githubusercontent.com/40062503/68395238-a46fa800-016f-11ea-8259-07f6be30e697.png)
![Sidebar-Collaborator-06](https://user-images.githubusercontent.com/40062503/68395239-a5083e80-016f-11ea-9163-1852b3b67ea4.png)
![Sidebar-Collaborator-07](https://user-images.githubusercontent.com/40062503/68395240-a5083e80-016f-11ea-9769-51002f06fb9f.png)
![Sidebar-Collaborator-08](https://user-images.githubusercontent.com/40062503/68395241-a5083e80-016f-11ea-8923-433364ab5dbf.png)
![Sidebar-Collaborator-09](https://user-images.githubusercontent.com/40062503/68395244-a5083e80-016f-11ea-96bf-1e771a7f3832.png)
![Sidebar-Collaborator-10](https://user-images.githubusercontent.com/40062503/68395376-e26ccc00-016f-11ea-8d11-628c1b4e4864.png)

**Comment by PVince81** [comment]
draft PR for the new flow: https://github.com/owncloud/phoenix/pull/2450
