### ISSUE TITLE
Missing "empty folder" indicator

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#1910]
### Steps to reproduce
1. Create a new folder
2. Navigate into it

### Expected behaviour
See a message like "This folder is empty" or a nice graphic that tells me I should upload something. (like in the old UI)

### Actual behaviour
File list is empty. The header is there. It looks broken.

### Version
Phoenix 2f7b3d781175e63a45291127bb3d2dfc3cfa5153

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/phoenix/pull/1911

**Comment by PVince81** [comment]
- [ ] when search has no results also need specific message ?
- [ ] should we hide the bulk actions ? should we hide the filter box ? etc...

@wuenschedesign

**Comment by PVince81** [comment]
- [ ] what to do with "used space" indicator ?

**Comment by marcus-herrmann** [comment]
>  when search has no results also need specific message ?

Definetly.

>  should we hide the bulk actions ? should we hide the filter box ? etc...

I understand the intention, but this would lead to a restless UI of some sort. Possibly disable it instead.

> what to do with "used space" indicator ?

It seems that this got resolved already. I got no size information about its contents when visiting an empty folder. The "Used space" indicator *could* be advanced by adding some information that is referring to the whole owncloud installation, though.

**Comment by wuenschedesign** [comment]
### First draft, how an empty folder page could look like:
I would keep the action buttons on the top right NEW and the FILTER (disabled), so that user always see where to find them, even when the folder has got items inside.

![List-View-Closed-Empty](https://user-images.githubusercontent.com/40062503/70169242-bdb23880-16ca-11ea-9548-1fe182bd2d7d.png)

**Comment by wuenschedesign** [comment]
How an empty folder could look like in the sidebar:

Draft with Call-to-Action »Upload Files« | Draft without Call-to-Action 
-- | --
![Sidebar-Empty-Folder-01](https://user-images.githubusercontent.com/40062503/70242983-112b9180-1772-11ea-9855-1fe8040a7fb7.png) | ![Sidebar-Empty-Folder-02](https://user-images.githubusercontent.com/40062503/70242986-11c42800-1772-11ea-92f1-8d25f4fd34a3.png)

**Comment by PVince81** [comment]
New PR here: https://github.com/owncloud/phoenix/pull/2975

**Comment by PVince81** [comment]
note: the most complex issue related to hidden files became obsolete due to #2971 

however, once we bring back this option we'll need to reconsider the message
