### ISSUE TITLE
Adapt  Phoenix to  PWA (Progressive Web Application)

### ISSUE THREAD

**Issue by labkode** [owncloud/phoenix#192]
Hi,

in order to make Phoenix more reactive to the user, following PWA guidelines is a good approach.
The [lighthouse tool](https://developers.google.com/web/tools/lighthouse/) can be used to audit different dimensions of the application for further optimizations.

The results I have got after running, are shown below:

<img width="1151" alt="screen shot 2018-07-10 at 10 49 18" src="https://user-images.githubusercontent.com/5175912/42557942-7a4b48f8-84f8-11e8-8d39-22a8d8124d3c.png">

The aspects identified for improvement are the following:

- [x] Does not respond with 200 when offline (use service workers for serving the shell app)
- [x] Does not provide content fallback when JS is not available (provide HTML alternative)
- [x] Does not redirect HTTP to HTTPS (not a dev task)
- [ ] Page load is not fast enough on 3G networks (reduce the library size)
- [x] Users are not prompted to install the app (create web app manifest)

**Comment by nonasoumy** [comment]
recovering data thanks for help guys

**Comment by OshanIvantha** [comment]
@DeepDiver1975 I will work on the remaining item here so that we can close this issue. Thinking about approaching this by reducing the library size of js-owncloud-client.

**Comment by DeepDiver1975** [comment]
postponing this for now - no idea if this is a real requirement for us
