### ISSUE TITLE
Disable notifications if the apps is not enabled

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1957]
## Description
If the notification app is not enabled it also needs to be disabled. Otherwise we are getting spammed with internal server errors and with fetch errors.

**Comment by PVince81** [comment]
maybe the OCS call to notifications should be done inside the app instead of Phoenix core ?

or if we consider notifications to be a central part, we might want to move it to Phoenix core ?

**Comment by PVince81** [comment]
(central part as in: should be visible/available on every app view in the header)

**Comment by PVince81** [comment]
Ah, I thought you meant the "Phoenix notifications app". I could not find any.

You probably means the core notifications app.

I hope there is a capability for it.

**Comment by PVince81** [comment]
Seems there is a capabilities entry that appears when the app is enabled:
```
        "notifications": {
          "ocs-endpoints": [
            "list",
            "get",
            "delete"
          ]
        }
```

**Comment by PVince81** [comment]
Since I stumbled upon the code I took the opportunity to just fix it: https://github.com/owncloud/phoenix/pull/1970
