### ISSUE TITLE
[QA] File names with trailing dots should be forbidden.

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#1969]
We should handle trailing dots ('.') the same as trailing whitespaces (' '):

Reference: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

Trialing whitespace is currently forbidden. -> so should be dots.

Note that Windows 10 has a different implementation than we: It treats a name with trailing whitespace or trailing dot the same as a name without. (Collision if already exists, or simply creates without. Any number of dots and whitespace is stripped.)

(Also: The blinking red error message is quite distracting when typing long names that contain whitespace or dots. Can we make this appear only after a short delay?)

**Comment by DeepDiver1975** [comment]
Why shall we care about Windows OS file naming restrictions? 
Files live on a Linux server and in the browser and on what ever storage backend.

Any file naming restrictions are defined by the server. Not the client's job.

**Comment by phil-davis** [comment]
> Any file naming restrictions are defined by the server. Not the client's job.

I agree. There have been plenty of discussions in issues in the different client repos over the years. If one client tries to "massage" the file naming rules in a way that changes the file name stored on the server, then it creates problems for other clients (from all different OS...) that have the [real|original] file name.

**Comment by jnweiger** [comment]
I disagree. We already have one such Microsoft rule implemented in the client "trailing whitespace' ' is not allowed" Trailing dot '.' is exaclty the same case.

The external WND storage has this restriction. A client should make nice error messages when hitting this limitation.

Technically, we can do it either place, storage driver or client.

But imho, we should do it in both places:
 - Frontent knows the storage limitation, and assists the user.
 - Backend enforces the storage limitation and prevents havoc.

**Comment by DeepDiver1975** [comment]
Sorry..but the Backend is driving File naming rules for years. We will Not Change this now.
