### ISSUE TITLE
permission / description missmatch for public links

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#1979]
the `Contributor` role is described with `Recipients can view, download and upload contents.` but results in permission `15` read (1) + update (2) + create (4) + delete (8)
the `Editor` role is described with `Recipients can view, download, edit, delete and upload contents.` but results in permissions `5`  read (1) +  create (4)

**Comment by PVince81** [comment]
I have a local fix

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/phoenix/pull/1985
