### ISSUE TITLE
Remove favorite button from file list

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1987]
![image](https://user-images.githubusercontent.com/25989331/64978110-108f0780-d8b5-11e9-9902-8074b9d6fdd1.png)

**Comment by PVince81** [comment]
Alternative proposal: remove star icon from the rows and keep it in the sidebar.

How often does a user mark a file/folder as favorite ? I guess it happens even less often than sharing, so having it "hidden" in the sidebar would be ok.

cc @hurradieweltgehtunter as we talked about star icon this morning

**Comment by LukasHirt** [comment]
> Alternative proposal: remove star icon from the rows and keep it in the sidebar.

@PVince81 I'd be fine with that approach. @pmaier1 @michaelstingl What do you think?

**Comment by LukasHirt** [comment]
> Even though I like that user can get a quick overview in the folder if you have some favourite items in there or not.

Maybe we could achieve this by adding some small icon next to the name same as in iOS app is the shared indicator.

**Comment by PVince81** [comment]
this depends how often the favorite feature is used and whether there is a use case where a user does want to see all favorites within a single folder.

in my case I only use favorites to have them as a shortcut to some folders and use the favorites panel to access them

maybe there are other non-shortcut use cases for favoriting folders ?

**Comment by michaelstingl** [comment]
I don't see the big value of displaying the favourite status in the file list. In the new iOS app, we display the favourite status in the details view, und there is a way to display all favourites.

![favorites-detail-collection](https://user-images.githubusercontent.com/214010/65690201-d1a84100-e06e-11e9-994d-66923f461b0d.jpg)

**Comment by PVince81** [comment]
@wuenschedesign

**Comment by wuenschedesign** [comment]
I tend to show a file in a file list as marked as favourite. I see no reason for not showing it to the user. BUT it’s not neccessary to give possibility to mark a file as favourite in the list overview, this can be done in a detailed view. I recommend to ask users to understand, what they are using the favourite for, so that we can decide to

**Comment by PVince81** [comment]
also proposed: to have the favorite icon to be part of the file actions box

**Comment by PVince81** [comment]
need better concept for indicators

**Comment by wuenschedesign** [comment]
Following the draft how to implement the favourite button. Note: I changed the originally colour yellow to action blue. Reason: yellow has low contrast and is hard to distinguish from background. Also the favorite icon works like a toggle switch and to make the UI more consistent, using grey and blue for toggle switches.

Folder not marked as favorite | Folder marked as favorite
-- | --
![Favourite-01](https://user-images.githubusercontent.com/40062503/70229402-707ba880-1756-11ea-94c9-d600c2fb04ca.png) | ![Favourite-02](https://user-images.githubusercontent.com/40062503/70229404-707ba880-1756-11ea-8397-9d339325c66f.png)

**Comment by PVince81** [comment]
As discussed before, I think we all agreed to remove it from the file list but keep it in the sidebar ?
In the sidebar it must be clickable, need to check if that works.

@pmaier1 @LukasHirt

**Comment by LukasHirt** [comment]
I'd still keep it in the files list just in a different place. It could be e.g. in the Actions dropdown for the resources as "Mark as favourite" action.

**Comment by PVince81** [comment]
actions dropdown sounds like a good plan !

- [ ] remove favorite from file list row
- [ ] add "mark/unmark as favorite" in actions dropdown
- [ ] check that the favorite icon in the context sidebar actually works
