### ISSUE TITLE
Private link for current folder in app bar

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#1988]
Could be for example next to the breadcrumb.

**Comment by VicDeo** [comment]
@LukasHirt should it be implemented as a part of oc-breadcrumb component, like a home icon?

**Comment by LukasHirt** [comment]
@VicDeo implement pls in Phoenix, not ods. For now is fine as an icon. Later on we’ll wrap it also in oc-Button as soon as we have the link version of it
