### ISSUE TITLE
Run acceptance tests against OCIS server

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#1995]
Currently we run acceptance tests against an OC server in CI.

We should also run said tests against an OCIS server there.
Maybe we can introduce tags to specify which tests already work on OCIS and ones that still need server side implementation there.

Not sure if this belong in this repo or rather in https://github.com/owncloud/ocis-phoenix.

Still, the tests are living in the Phoenix repository, so it feels like the right place is here.
One drawback of running them here is that one would need to retrigger the CI tests after releasing a new OCIS server implementation. OCIS server devs might want to see acceptance test results on their PRs.

To be discussed @individual-it @felixboehm

**Comment by individual-it** [comment]
It could work both ways
1. Let the tests here
2. On phoenix PR run them with oC 10 & oCIS
3. in oCIS repo, clone the phoenix repo (I guess we need to do that anyway to install phoenix) and run the same tests there.

So we would keep only one copy of the tests but run them in both CI
Similar is done for oC apps now. e.g. in the LDAP app the core tests are run on LDAP  PRs

**Comment by skshetry** [comment]
Reducing priority as it's in a backlog.

**Comment by dpakach** [comment]
Running phoenix tests with ocis works locally but not in CI because of https://github.com/owncloud/ocis-reva/issues/58. Since we run selenium and chrome in a docker container and the oauth redirect url is always on localhost we cannot run it on CI.

**Comment by DeepDiver1975** [comment]
I wonder if you better use ocis instead of ocis-reva.
We will soon drop the oauth/openid connect procider from ocis-reva. 
Or you start the oidc in addition to ocis-reva ....

just saying

**Comment by individual-it** [comment]
as discussed yesterday, we should be unblocked here so putting it on the current sprint

**Comment by individual-it** [comment]
@dpakach is this finished?

**Comment by dpakach** [comment]
@individual-it Yes, we are running tests on all the scenarios that pass currently.
