### ISSUE TITLE
Support apps/plugins

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#2]
We need a clearly defined mechanisms to allow frontend apps to properly hook into phoenix.

At best we allow to reuse existing web front ends like built in the contacts app as example.

Please make sure the #1 applies in here as well.

**Comment by PVince81** [comment]
The server must have authority about what frontend components/apps can be loaded for the current user. This means the frontend apps don't need to know about each other directly.

**Comment by PVince81** [comment]
This also means that the frontend alone doesn't know anything about installed modules. The frontend brings in some modules in different paths as webpack bundle (one bundle per app/module) and the main page needs to query the server to find out what modules to load.

At development time we could provide a static JSON file on the dev server to be able to load modules for when no backend is available at all.

**Comment by felixheidecke** [comment]
I am still working on an easy way to use vue.js's component system to serve extension points in phoenix. An API needs to tell phx what to load simply by populating an object little data.

Jet there still is the need to deploy frontend code and other assets on the frontend-server as well as backend-code to the core-server.

**Comment by PVince81** [comment]
@felixheidecke please link with tickets / PR related to app loading

**Comment by DeepDiver1975** [comment]
implemented
