### ISSUE TITLE
default expiration date is not set for public links

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2002]
### Steps to reproduce
1. set "default expiration date" in the sharing settings to a value >0
2. create a public link with phoenix

### Expected behaviour
the UI should show and set the "default expiration date" 

### Actual behaviour
the expiration date field is empty

**Comment by PVince81** [comment]
Hmmm... do we also have tests for password enforcement and password rules ? @individual-it

**Comment by individual-it** [comment]
@PVince81 not yet

**Comment by PVince81** [comment]
I've raised https://github.com/owncloud/phoenix/issues/2075 to cover this, please fill in the checkbox list

**Comment by PVince81** [comment]
works for me as well on master, probably outdated
