### ISSUE TITLE
Private Link for files not working correctly

### ISSUE THREAD

**Issue by hodyroff** [owncloud/phoenix#2021]
Alice uses a private link, on login she is briefly displayed the correct behaviour, but then transfered into the home view.
Resolution: Stay with the correct behaviour.

**Comment by jnweiger** [comment]
I sometimes get "error resolving private link" and sometimes a redirect to the top level folder.
In both cases I am with role Owner. 

@hodyroff Please specify "the correct behaviour" 

1) download the file, or
2)  show folder and open the sharing details for the file?

**Comment by jnweiger** [comment]
Tested on INT Version: 0.2.4-63760d1 (1570179040161)

User S0X00024 creates JW/264/New and shares with with S0X00029 as Viewer,
copy Private link. Use a new browser window.
Login in as  S0X00024 -> Link works

copy Private link. Use a new browser window.
Login in as  S0X00029 -> An Error occured resolving private link: Unknown Error

**Comment by jnweiger** [comment]
@hodyroff  Private links currently only for the same user. At least on a WND backend.

Suggested fix: Forget private link. Remove the link icons. Users should communicate full path URLs.

**Comment by DeepDiver1975** [comment]
fixed with #2170
