### ISSUE TITLE
Missing bulk action bar in favorites page

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2055]
### Steps

1. Upload three files
1. Mark all three as favorite
1. Go to "Favorites" file list
1. Select two of them
1. Try and bulk delete

### Expected
Bulk delete is possible from the header bar like in the "All files" view.

### Actual
Bulk delete is missing. I need to delete the files individually and confirm each one of them.

**Comment by LukasHirt** [comment]
Tested with phoenix version `Version: 0.2.7-9fa84171 (1579092217051)` and bulk actions are included in the favorites page - closing.
