### ISSUE TITLE
Acceptance tests default expiration date, password policy, etc

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2075]
We should add acceptance tests for the many scenarios that touch sharing related to:
- [x] public link password enforcement #2489  #2518 
- [x] default expiration date #2529
- [x] enforced expiration date
- [ ] ... others ?

p2 because it's linked with the p2 collaborators feature

**Comment by phil-davis** [comment]
There are plenty of optional sharing settings to test! Look in the admin-settings-sharing page.
e.g. restricting sharing to only users in their groups, by group, to groups, disallow sharing with groups completely, disallow resharing, auto-accept shares (or not)...

**Comment by PVince81** [comment]
yes, we could prioritize to have the most commonly used combinations covered with higher priority

**Comment by individual-it** [comment]
currently blocked by #2372 as that PR partly implements what need to be done here

**Comment by individual-it** [comment]
got unblocked and moving on with the work

**Comment by phil-davis** [comment]
I added to sprint 58 so we notice this.
Finished?

**Comment by individual-it** [comment]
done, see linked PRs
