### ISSUE TITLE
Tests for accessing shared file with private link

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#2084]
## Description
Tests for accessing file which has been shared from other user with private link need to be implemented.

Follow up on #2049

**Comment by individual-it** [comment]
@Talank you have worked on tests for perma-links aka. private links. How much is left to do?

**Comment by Talank** [comment]
@individual-it related to perma-links, I am working on https://github.com/owncloud/phoenix/issues/3096
