### ISSUE TITLE
Link to authorisation at access denied page

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#2102]
There is no "easy" way of navigating back to authorisation page if the user lands on the access denied page. Let's add a simple link to get there.

**Comment by DeepDiver1975** [comment]
I understand that this is specifically annoying for us during development and Testing.
In a real world scenario any further action will Not Help.
The user is authenticated at the idp Level.
Bringing the user back to the logon page will sugerate that there is a was Out. Nur there isnt. 🤷

**Comment by LukasHirt** [comment]
Since you can land on that page in case of any error I think it would be nice addition. E. g. if the token expired and user needs to authorise again. But you have a point there about the way out. Also question is how many of those errors will still be there when Phoenix is "ready" for users.

**Comment by DeepDiver1975** [comment]
Assuming that we will implement PKCE within owncloud oauth this page will usually never be visible in regular use.
