### ISSUE TITLE
[QA] Drag and drop does not work with IE11

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#2119]
Drag and drop a folder does not work. This is fine. Folder upload is disabled for IE11.
Drag and drop a file also does not work

![image](https://user-images.githubusercontent.com/1108546/65992966-8fc53380-e490-11e9-9d1e-9e8477a19eea.png)

We get the same error message when dropping a jpeg file as for a folder.
Expect this upload to succeed.

**Comment by jnweiger** [comment]
Seen with 
![image](https://user-images.githubusercontent.com/1108546/65998057-e0418e80-e49a-11e9-81db-4b7e871c9ac9.png)

**Comment by jnweiger** [comment]
ACL Version: 0.2.4-63760d1 (1570179040161) 
With IE11:
* no more error messages. 
* Instead, the file is opened in the browser (or added as a download), which is normal windows behaviour, when a website does not react to drag and drop.

With Firefox:
* Drag and Drop still uploads (as expected)

@hodyroff is this acceptable behaviour?

As a user I am surprised that IE11 opens its *download* manager, when I try to trigger an *upload* by drag and drop. Somewhat counterintuitive.

**Comment by jnweiger** [comment]
Tested on ACL Version: 0.2.4-4e667ef (1570697905792)
As above. Its a WONTFIX.

@hodyroff Requires Documentation!

**Comment by PVince81** [comment]
@LukasHirt what was the chosen approach in the end ? anything left to do for Phoenix ?

**Comment by LukasHirt** [comment]
@PVince81 At the moment it is completely disabled for ie 11. As soon as the time permits we should look into it deeper and solve the issues there so it's available also in ie11. (needs to be decided what priority it is)

**Comment by PVince81** [comment]
@pmaier1 ^

**Comment by PVince81** [comment]
@pmaier1 do you agree with the decision ?

**Comment by PVince81** [comment]
dropped support for IE11, won't fix
