### ISSUE TITLE
[QA] IE11: Tooltip missing when hovering on greyed out  '+New' Button

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#2127]
Steps:

* Open any folder for which the user has only viewer permissions
* Mouseover over the "+ New" button

While hovering, no tooltip (e.g. "You have no permission to upload!") is displayed. This error only occur with Internet explorer.
The tooltip will be displayed correctly with Google chrome.

EXPECTED: While hovering, a tooltip (e.g. "You have no permission to upload"") should be displayed.

**Comment by DeepDiver1975** [comment]
another ie11 throw back - will have a look ...

**Comment by PVince81** [comment]
dropped support for IE11, won't fix
