### ISSUE TITLE
File viewer and editors

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#215]
Story:
Given a developer want to add an action to open a file in another tool
When the app code registers a file action for text files
Then the action shall be visible on text files

When a user executes the file action
Then app code is to be executed or a given url is to be opened (in another tab)

Tasks:
- implement file action + viewer concept in phoenix files app (3MD)
- implement an app to show (text editor which opens a text file in new browser tab) (2MD)

---

Like https://github.com/owncloud/core/issues/13414.

Provide an extension point of some form where apps can register their own "file viewer" for different formats.
This will tie in somehow with the [file actions](https://github.com/owncloud/phoenix/issues/149)

Please add input as we need to decide on the UX for this.

One proposal was to always have apps open their viewer in a separate page.
This also means the separate page needs to have some layout and styling from Phoenix.

@felixheidecke @DeepDiver1975 @tomneedham @pmaier1

**Comment by tomneedham** [comment]
Random thoughts:

 - Open in new window (new tab if clicked with ctrl+click), no 'inline' editors
 - Back button returns to file list, scrolled to the same location
 - Needs a similar 'registerActions' type handler for mime registration
   - On that thought, as an admin some global preferred handler config might be nice
 - At least how we do it now, each editor should have a route, which accepts a fileid (eg, now I have `/apps/drawio/editor/{fielid}`
 - New persistent locking is most likely needed to give a nice UX
   - Seeing who is currently editing this file (who owns the lock) would be awesome
 -

**Comment by tomneedham** [comment]
> what about additional permissions like "comments only" (Collabora and OnlyOffice)

Like 'review' permissions  - could be cool

**Comment by PVince81** [comment]
also need to make sure file viewer works in public page

**Comment by DeepDiver1975** [comment]
There is a markdown editor in phoenix which shows how an editor can be integrated. closing for now
