### ISSUE TITLE
if no share were send/received "shared with you/others" must not show all files

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2150]
### Steps to reproduce
1. have a user that did not receive or send ever a share
2. navigate to "All Files"
3. navigate to "Shared with me"
4. navigate to "shared with others"

### Expected behaviour
"shared with me" & "shared with others" should be empty

### Actual behaviour
all files of the user are listed

![shares-lists](https://user-images.githubusercontent.com/2425577/66181978-b2269f00-e692-11e9-95f1-92035ad5c5a3.gif)

**Comment by PVince81** [comment]
From what I see, the logic is skipping "LOAD_FILES" action whenever there are no results from the OCS Share call for both views.

It should be modified to actually clear the current file list.

**Comment by PVince81** [comment]
Ok, it seems to use the first entry in the list for `currentFolder` as our current state expects a value for it. So it's not trivial to generate an empty result set there without virtualizing the `currentFolder`.

I don't think the current code is correct. We need to be able to support a flat list of results that do not have any current folder in place, like the list of favorites or shares. The view should be able to work with a `null` currentFolder then.

I'll need to talk with @LukasHirt about a proper solution.

**Comment by PVince81** [comment]
as discussed with @LukasHirt, the first attempt will be at removing the requirement that `currentFolder` is set. might require going through the whole source code...

**Comment by PVince81** [comment]
slightly related to https://github.com/owncloud/phoenix/issues/2077

**Comment by PVince81** [comment]
- [ ] remove requirement for `currentFolder` in file lists
- [ ] add "flat list" mode which it based on whether `currentFolder` is set or not, then allow duplicate file names to fix https://github.com/owncloud/phoenix/issues/1750

**Comment by LukasHirt** [comment]
The base issue is solved in #2280 thanks to the reset of the files array when the folder is being loaded. Still, needs anyway all the mentioned fixes.

**Comment by PVince81** [comment]
this isn't happening any more. I extensively tested such scenario when testing the "empty indicator" for the lists, closing.
