### ISSUE TITLE
draw.io app compile error

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2169]
### Steps
1. Check out master
1. Run `yarn watch-all` and observe the output

### Expected
No compile errors

### Actual
Somewhere in the middle where draw-io app is compiled:
```
ERROR in multi core-js/modules/es6.promise core-js/modules/es6.array.iterator ./src/app.js
Module not found: Error: Can't resolve 'core-js/modules/es6.array.iterator' in '/home/vincent/Private/Work/workspace/phoenix/apps/draw-io'
 @ multi core-js/modules/es6.promise core-js/modules/es6.array.iterator ./src/app.js draw-io[1]

ERROR in multi core-js/modules/es6.promise core-js/modules/es6.array.iterator ./src/app.js
Module not found: Error: Can't resolve 'core-js/modules/es6.promise' in '/home/vincent/Private/Work/workspace/phoenix/apps/draw-io'
 @ multi core-js/modules/es6.promise core-js/modules/es6.array.iterator ./src/app.js draw-io[0]
```

@DeepDiver1975 not sure if we had that when we merged your PR back then

**Comment by DeepDiver1975** [comment]
What is your nodejs version? This is not happening locally or on drone ....

**Comment by PVince81** [comment]
My node version is v10.16.3

Note that the compilation doesn't fail and it just continues

**Comment by PVince81** [comment]
please tell me your node version and I can debug locally if I'm the only one seeing this

**Comment by DeepDiver1975** [comment]
nodejs v10.15.2
yarn 1.19.0

**Comment by PVince81** [comment]
I did a `yarn clean-all` and then `yarn install-all` and now it compiles fine

Probably I missed updating some deps inside the app as I usually just do "yarn install" instead of "yarn install-all".

sorry for the noise
