### ISSUE TITLE
use cucumber-js 6

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2175]
https://github.com/cucumber/cucumber-js/pull/1205 got merged, and version 6 is released https://github.com/cucumber/cucumber-js/commit/d195239cdb9effb811ed70cd549e87ee0d0b7368
so we should use that

**Comment by PVince81** [comment]
@individual-it priority ? something for very soon or much later ?

**Comment by individual-it** [comment]
I would do it rather soon because:
1. we currently using a version from a branch
2. it should not be a big work

**Comment by individual-it** [comment]
the problem is in `cucumber-pretty` let me see if I can fix it

**Comment by individual-it** [comment]
fixed by  #2194
