### ISSUE TITLE
Reusable Vue components provided by Phoenix

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#219]
Challenges:
- how to load these in Phoenix apps ?
    - requirejs ?
    - import at compile time ?

@felixheidecke

**Comment by felixheidecke** [comment]
I just came up with a rather "funky" idea. You can choose to have webpack use a hash as the chunks filename. So if this hash would actually be the checksum of the file, and we whould have multiple files with the same name thus only having one of them, dumping/overriding the others would solve the problem.

If still find that … kind of weired :-P

**Comment by DeepDiver1975** [comment]
we will introduce the first own components with #433 and we will take care that these components are available for all app.
