### ISSUE TITLE
Get rid of private link icons

### ISSUE THREAD

**Issue by butonic** [owncloud/phoenix#2207]
Some feedback from customers: no one knows the privat link feature. End users are just copying the url in the browser to paste it into emails: `Ctrl + l`, `Ctrl + c`, `Alt + Tab`, `Ctrl + v` . That works in oc10 because it contains the fileid.

I propose to get rid of the icon and rely on a url that can be copy pasted. We can either:
1. use a path that includes the username, eg the path from the dav/files endpoint
2. use a file id (which might consist of a storage id and a fileid ... should be treated as an opaque string, probably base62 encoded for url safety)

I think this aligns with https://github.com/owncloud/phoenix/issues/1307 and also fixes https://github.com/owncloud/phoenix/issues/2095. It fits the idea of having one url / reference to pass around

**Comment by PVince81** [comment]
@pmaier1 @michaelstingl @LukasHirt @DeepDiver1975

**Comment by michaelstingl** [comment]
Desktop and mobile clients don't have the "always visible" URL when browsing the directory structure, the need an icon/button/something… Web UI should also have it (aligned to the other clients) for consistency.

**Comment by LukasHirt** [comment]
> Desktop and mobile clients don't have the "always visible" URL when browsing the directory structure, the need an icon/button/something… Web UI should also have it (aligned to the other clients) for consistency.

For this could work the "copy private link" action that's supposed to be in Links tab in sidebar as specified in requirements by @pmaier1 and also as iOS app does it

**Comment by labkode** [comment]
The feedback we get from our clients is that the URL on the browser should be same url used as the sync client and the same url on the filesystem, like that you have the same view independently on the user-agent.

**Comment by PVince81** [comment]
This is not possible with the current shared mount structure, because the path that users see is not always the same for all users. In OC 10 the workaround is adding the file id in the URL, so when present it will use that instead of the path.

**Comment by PVince81** [comment]
if we have agreement about moving the private link to the "Links" section, I can cancel all current efforts to fix the current icon
