### ISSUE TITLE
Don't load anything from the Internet

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#228]
We should bundle everything:
- material icons, etc

Currently it connects to remote sites like google for downloading these.

@felixheidecke

**Comment by michaelstingl** [comment]
- https://fonts.googleapis.com/icon?family=Material+Icons
- https://fonts.gstatic.com/s/materialicons/v41/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2

**Comment by DeepDiver1975** [comment]
@tempelgogo we need a solution which fits into theming as well. Themes can change icons ....

Which one of the proposed will work?

**Comment by tempelgogo** [comment]
> @tempelgogo we need a solution which fits into theming as well. Themes can change icons ....
> 
> Which one of the proposed will work?

All three proposals will include the font files & related stylesheets as static assets, while webpack will bundle them on phoenix build to a big, tree-shaked & compressed stylesheet.

The only option for theming, without rebundling the whole phoenix, is to use a separate theme-related stylesheet, which includes additional font files & extends the base bundle.

All three proposals can offer this, as they are only ways to manage the material icon package version.

The webpack plugin is able to manage all Webfonts offered from google, but this is only relevant if we are interested in some more google fonts.

In light of the fact that we only need material-icons and PR https://github.com/owncloud/phoenix/pull/127 is already prepared, I fully agree with @felixheidecke to use the npm-maintained version of the material icons.

**Comment by DeepDiver1975** [comment]
Easiest and best to maintain approach is something webpack based I assume. @tempelgogo please choose and submit a pull request. THX
