### ISSUE TITLE
the oidc-callback.html does not work for the OAuth2 implicit flow

### ISSUE THREAD

**Issue by butonic** [owncloud/phoenix#2288]
According to https://tools.ietf.org/html/rfc6749#section-4.2 the implicit flow must use the url fragment, so the browser will not send the access token back to the server (it would show up in logs and proxies).

The query mode for `id_token token` is explicitly forbidden in https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Combinations

> id_token token
>   When supplied as the value for the response_type parameter, a successful response MUST include an Access Token, an Access Token Type, and an id_token. __The default Response Mode for this Response Type is the fragment encoding and the query encoding MUST NOT be used.__ Both successful and error responses SHOULD be returned using the supplied Response Mode, or if none is supplied, using the default Response Mode.

OpenID Providers following the standard will send an auth response with a redirect like this:
```
Location: http://localhost:8300/oidc-callback.html\#access_token\=IW09aAO1AJCpJ7fsK63_8J63lWJkYbpfRfkaUnq-oz8.Pj-ZlXlU4-oTgp00fF5Nq-rYVd2RxEh-xneIRlP7mzg\&expires_in\=3599\&id_token\=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdF9oYXNoIjoiVHBIXzl3S1REc3I1dUJ4NDBub2VOUSIsImF1ZCI6WyJwaG9lbml4Il0sImF1dGhfdGltZSI6MTU3MTM0MjE0MywiZXhwIjoxNTcxMzYzNzQzLCJpYXQiOjE1NzEzNDIxNDMsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MTAwMDAiLCJqdGkiOiJmMWJmOGFlNy1jMzQ0LTQzY2YtOGI5NS1mNTRiNmI0MjI4YzIiLCJub25jZSI6ImRlNDBkNjYyM2IyMjRjMDE4ZmE2MzNkZjVlZDY4MmE0IiwicmF0IjotNjIxMzU1OTY4MDAsInN1YiI6IjRjNTEwYWRhLWM4NmItNDgxNS04ODIwLTQyY2RmODJjM2Q1MSJ9.F2vtbpoBtgwu4bm3LRUr3_CyR1il5zB7OAL8P-7HbcPy1fFit5iy4tB0AFef__2XikqqirMzStP71-rSoEU5o-DWiE-42Jr4PZoxL7fpzIc_3LVJlwaJfbf8ocbwYKGM4fqh_3xDFzPLGxh-p_VdbaiNjhkW3HypEpMp4BMl8U7pAp-5ileAojhz1-KvaGewWwQ2RgT22vvs7NutBVdk5ep5I7PL3kFoAkkSiKtXZqx2amDAI89QF46jEOMYs0ISrSCvbLHS6dCH5VqkpOqVlQnGE5jwicq74gnOtF9Mj44FGHTcQWt6lnSnYVrFZs4MNRkBr2WAjlLlxHYUeSy0pA\&scope\=openid%20profile%20email\&state\=8c9e7f12aacc42768c2c779e1bf36718\&token_type\=bearer
```

The oidc-callback.html js snippet will take the url query into account (which is used for the autorization code flow), but not the url fragment. As a result, the redirect to the `"index.html#/oidc-callback" + window.location.search;` forgets all auth fragment encoded response parameters, the login fails and the user is redirected back to the login page.

**Comment by DeepDiver1975** [comment]
Generally speaking we should NOT use implicit flow at all - implicit flow is inscure.
We should only use auth code flow - as replacement for implicit flow for native client auth code flows with PKCE shall be used.

In which setup did you face this implicit flow? @butonic
