### ISSUE TITLE
Automated changelog updates

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2302]
Check how how it's done in https://github.com/owncloud/core and apply the same tooling here.

It will require developers to create additional changelog files for every pull request and be more thoughful about having proper descriptions.

Changelog will then be generated periodically or on-demand during releases.

**Comment by LukasHirt** [comment]
@PVince81 @DeepDiver1975 Do you have some experience with this? https://github.com/release-it/release-it Could be worth looking into it a bit more.
