### ISSUE TITLE
Missing translations in Transifex

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2340]
On the accessDenied.vue page there are several texts that are not present on Transifex https://www.transifex.com/owncloud-org/owncloud-phoenix/translate/#de/core/174141213

I didn't find any sync jobs in the drone files, so maybe sync is missing ?

Otherwise maybe there's an issue when parsing those HTML tags that have "v-translate", or the file is not processed at all.

**Comment by PVince81** [comment]
Likely related: https://github.com/owncloud/translation-sync/issues/24.

**Comment by PVince81** [comment]
Idea for later: add some monitoring for the core repo that detects whenever the last transifex commit is too old.

**Comment by DeepDiver1975** [comment]
translations did arrive - https://github.com/owncloud/phoenix/commit/7efa5f6346dfed9ac3193737bd022e6bb9e2d593
