### ISSUE TITLE
Move tokens from local storage to session storage

### ISSUE THREAD

**Issue by mrkwenzel** [owncloud/phoenix#2407]
### General information
Currently the tokens provided by the OpenID Connect to authenticate a user are stored in the local storage.
So even if a browser is closed the user has the ability to use the system if he reopens it.
It would be better to store these tokens at least in the session storage to require another auth flow.

### Solution
Store the tokens in the session storage instead of localstorage.

**Comment by PVince81** [comment]
Hmm, I thought we already did this ? https://github.com/owncloud/phoenix/pull/2049

@LukasHirt

**Comment by mrkwenzel** [comment]
Possible solution? https://github.com/mrkwenzel/phoenix/commit/1b9aa1af93e371d1f447e9801f1cd211c58c07cc

Did I miss something?

**Comment by LukasHirt** [comment]
> Hmm, I thought we already did this ? #2049
> 
> @LukasHirt

Mentioned PR was only about the link before authorisation. The user and capabilities are still stored in the local storage.
