### ISSUE TITLE
creating share with user and group having same name is not possible

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#2419]
### Steps to reproduce
1. Cretate two users ```user1``` and ```user2```. And create a group ```user1```
2. Add ```user2``` to group ```user1``` and share some file ```abc.txt``` with group ```user1```
3. Now try to share the same file ```abc.txt``` with user ```user1```. Here ```user1``` is not displayed in the sharing autocomplete list.
### Expected behaviour
It must be possible to share file with user and group having same name
### Actual behaviour
Sharing with user and group with same name is not possible

**Comment by phil-davis** [comment]
core issue https://github.com/owncloud/core/issues/35488 was similar.
The sharing API was fixed in https://github.com/owncloud/core/pull/36359

Does that fix help Phoenix to work?

**Comment by HariBhandari07** [comment]
Nope core is fixed but phoenix is not yet fixed. I have just added acceptance tests for this issue here https://github.com/owncloud/phoenix/pull/2386
