### ISSUE TITLE
Nightly tests are failing on IE11

### ISSUE THREAD

**Issue by dpakach** [owncloud/phoenix#2420]
### Tests are failing on IE11
Tests are failing on the nightly IE11 build. 
https://drone.owncloud.com/owncloud/phoenix/6285/24/14

The cause for this problem might be file upload by mounded volumes on selenium added in https://github.com/owncloud/phoenix/pull/2361
This needs to be investigated.

Last passed nightly build - https://drone.owncloud.com/owncloud/phoenix/6147

**Comment by PVince81** [comment]
making that p1 as consistently failing tests will hide other test results

**Comment by dpakach** [comment]
The PR https://github.com/owncloud/phoenix/pull/2446 should have fixed this problem. We will check this on tonight's nightly build and close this.

**Comment by dpakach** [comment]
Passing Now after #2446
