### ISSUE TITLE
Add acceptance tests for federation sharing

### ISSUE THREAD

**Issue by dpakach** [owncloud/phoenix#2477]
### Acceptance tests for federation sharing
Looks like federation testing through phoenix is possible now. But there are no tests for federation testing in phoenix.
Implement tests  for federation sharing in phoenix.

- [x] - Add drone configuration for setting up a federation server for testing federation sharing. (#2502)
- [x] - Implement the tests for federation sharing as per the feature file. (#2720) https://github.com/owncloud/phoenix/blob/master/tests/acceptance/features/webUISharingExternal/federationSharing.feature

**Comment by PVince81** [comment]
unblocked by #2569
