### ISSUE TITLE
file path is not displayed in shared with others page

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#2480]
### Steps to reproduce
1. Share a file "file.txt"
2. Share another file with the same name , located inside a folder. For eg, "Folder/file.txt"
3. Browse to ```shared with others``` page.  Here, there is  no mechanism to distinguish which file is which. A path for a file is not displayed.

### Expected behaviour
File path should be displayed in shared with others page

### Actual behaviour
File path is not displayed in shared with others page

**Comment by PVince81** [comment]
closing in favor of more generic ticket https://github.com/owncloud/phoenix/issues/2925
