### ISSUE TITLE
Add tests for the features that have been implemented in phoenix but not covered in acceptance tests

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#2482]
### Description
Features are implemented in phoenix every day, but still, many features are not covered by the acceptance tests. Add as many acceptance tests to cover all the implemented features and remove the duplicate acceptance tests.

**Comment by dpakach** [comment]
### Implemented Features that require tests
- [ ] Accounts page

**Comment by individual-it** [comment]
@HariBhandari07 @dpakach what is left of this task?

**Comment by HariBhandari07** [comment]
@individual-it we have covered enough tests for different pages. So, this issue is closed.
