### ISSUE TITLE
Test: Make helper functions handling paths lexically

### ISSUE THREAD

**Issue by skshetry** [owncloud/phoenix#2499]
Currently, we are using a mix of `trim()`, `slice()` , `split`, `substr`, `path.resolve()`, `replace`, etc for working with paths in acceptance tests. Most of the functions are repetitive and the breadth of functions that are being used is purely personal preference.

We need to abstract that out to a few functions that are uniform, easy to understand and readable.

Some utilities to implement (not everything is required at the moment):
- [x] `normalize` (#2535)
- [x] `resolve`/`abspath` (#2535)
- [ ] `basename`
- [ ] `dirname`
- [x] `parts` (#2592)
- [x] `join` (#2535)
- [ ] `ext`
- [x] `filename` (#2592)
- [ ] `filename without extension`.
- [ ] `check that path is inside parent`
- [ ] `is_absolute`
- [ ] `is_relative`
- [ ] `match` (based on `regex`/`glob`)
- [x] `relativeTo` (#2592)
- [ ] only change suffix of filepath
- [ ] only change name of filepath
- [ ] common path between two

### Goals:
1. To be purely lexical (so, no relation with filesystem. Use `path` for those cases)
2. No support for up-level references (i.e. `..` and `.`).
3. Root has no meaning at all here. Or, the path without root (`/` at the start) is same as without one.

P.S. We could implement these as per requirement.

**Comment by individual-it** [comment]
some work has been done, closing for now
