### ISSUE TITLE
don't use assertions in page objects

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2508]
in the acceptance tests we party do assertions in the pageObjects, but they only should return data of the page and the context should decide what to do with that data. So we need to move all the assertions to the context files.

**Comment by individual-it** [comment]
> The tests, not the PageObjects, should be responsible for making assertions about the state of a page
> A PageObject need not represent an entire page. It may represent a section that appears many times within a site or page, such as site navigation.

https://github.com/SeleniumHQ/selenium/wiki/PageObjects

**Comment by phil-davis** [comment]
Looks like this is still in progress, so I added it to the current sprint.

**Comment by individual-it** [comment]
done, see linked PRs
