### ISSUE TITLE
Autocomplete not showing in federated share

### ISSUE THREAD

**Issue by dpakach** [owncloud/phoenix#2509]
### Steps to reproduce
1. In Share input try to enter a federated user id (eg. `admin@http://localhost/owncloud` or `user@http://owncloud-server`)
( The id should not include IP address or any sub domains with dot ( . ) notation such as `example.com`)

### Expected behaviour
The federated user should appear in the autocomplete list.

### Actual behaviour
No users are listed in the autocomplete list.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/phoenix/pull/2569

**Comment by PVince81** [comment]
@dpakach fixed. you should be unblocked on the tests now
