### ISSUE TITLE
cannot delete the expiration date when default expiration date is set for public links

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2532]
### Steps to reproduce
1. set default expiration date for public links but do not enforce it
2. start creating a new public link
3. try to clear the expiration date

### Expected behaviour
there should be a way to clear the expiration date, as its not enforced

### Actual behaviour
no way to clear the date

**Comment by PVince81** [comment]
@kulmann did you observe / fix this when working on the expiration date field ?

**Comment by kulmann** [comment]
@PVince81 yes, this is fixed. Enforced expiration date -> no option to remove the date. No enforced expiration date -> input field has a little X on the right side, like the password field, which clears the date.
