### ISSUE TITLE
breadcrumb is not seen one level below the root directory if rootFolder is set

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/phoenix#2538]
### Steps to reproduce
1. Set ```"rootFolder": ""``` in ```dist/config.json```
2. Now restart phoenix server and browse inside some folder, for eg: ```simple-folder```
3. Here, breadcrumb for ```simple-folder``` is not shown.
But if you create child folder for eg, ```simple-child``` and browse inside, breadcrumb for this child folder is visible.
### Expected behaviour
Breadcrumb for folder one level inside of root directory should be shown even if ```rootFolder``` is set.

### Actual behaviour
Breadcrumb for folder one level inside of root directory is not shown when ```rootFolder``` is set.

**Comment by LukasHirt** [comment]
Pls, doublecheck after #2280 is merged. Seems the issue is gone.
