### ISSUE TITLE
Expiration date field for regular shares

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2543]
Same as https://github.com/owncloud/core/pull/36324 but for Phoenix

- [ ] If the capability `files_sharing.user.expireDate.enabled` is set, show expiration field
- [ ] Fix expiration field + date picker (currently hidden and broken)
- [ ] Consider enforcement fields/capabilities as well

**Comment by jvillafanez** [comment]
In case there are doubts, users and groups have different capabilities which could have different values.
As it's written in the description, it seems that either there is no capability for group sharing or it uses the same information as the user's one. Just remark there is `files_sharing.group.expireDate` capability for the groups, with the same information than the users (although the values can be different)
