### ISSUE TITLE
Fix vuejs browser extension

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#257]
The chrome browser extention can currently no be enabled.

reason: vuejs is bundled into core.bundle.js

**Comment by felixheidecke** [comment]
Browser extension only works in dev-mode.
Running `webpack --mode development --config webpack.dev.js` solves that problem.
If you like, I can create a simple npm command for that.

**Comment by DeepDiver1975** [comment]
this shall be added to the npm run watch command - this is what devs are using.
same for the make runs command - it also runs webpack in prod mode which is :hankey:

**Comment by DeepDiver1975** [comment]
thx for the hint - PR welcome ;-)

**Comment by tempelgogo** [comment]
pr merged — `npm run watch` now available
