### ISSUE TITLE
Embed core's settings page into iframe

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2598]
Since the settings page will take a while to port over (if ever), let's try embedding it from OC 10 using an iframe.

**Comment by PVince81** [comment]
- core PR: https://github.com/owncloud/core/pull/36506
- phoenix PR: https://github.com/owncloud/phoenix/pull/2599

@DeepDiver1975 @LukasHirt FYI

**Comment by michaelstingl** [comment]
@PVince81 Why embed in iframe and not open the full page in a new tab?

**Comment by PVince81** [comment]
@michaelstingl because we don't want the OC 10 top header.

The goal of the iframe is to keep Phoenix' navigation and top bar in place while displaying the OC 10 content in the bottom frame.

**Comment by PVince81** [comment]
See how it looks like ![image](https://user-images.githubusercontent.com/277525/69978891-83f7fb00-152d-11ea-8102-52ad1a5c134e.png)

**Comment by PVince81** [comment]
if that doesn't work out in the end, another alternative idea as follows:
- package the Phoenix header bar and navigation bar as web components
- embed those web components inside of OC 10 to achieve the same look

**Comment by DeepDiver1975** [comment]
>     * minor con: URL will switch between Phoenix and OC 10 domains

this can be ignored from an UX perspective from my pov



>     * package the Phoenix header bar and navigation bar as web components (possibly also using iframes there)

we will need this anyhow with the multi url approach and more elaborate apps/integrations

**Comment by PVince81** [comment]
Next up: I'll prototype with the latter alternative.
This would likely help bypass potential troubles with route rewriting that would be needed for iframes.

**Comment by PVince81** [comment]
Not a viable solution as it requires rewriting links.

A better solution is rather importing Phoenix web components into OC 10: https://github.com/owncloud/phoenix/pull/2620

I'll close this ticket and the experimental PRs.
