### ISSUE TITLE
Embed legacy app in Phoenix frontend

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2600]
Goal: people should not leave the Phoenix UI.

Since many of the legacy apps (like calendar, contacts) will need to be ported over to the Phoenix UI, in the meantime we need a way to use these legacy apps without leaving the Phoenix UI.

Such apps should be embedded inside an iframe, where the header is removed.
For the legacy settings page, see https://github.com/owncloud/phoenix/issues/2598

### Simple approach

It could be in the form of "one extension per legacy app" that can be built using a template.
This has the drawback that every app needs to have such wrapper in place.

### Complex approach

Have a single compatibility extension that detects **all** the installed legacy apps that have navigation items registered in the OC 10 navigation bar. This would require some additional APIs in core to be able to read that information.

Then for each of such app, add an entry into the Phoenix navigation.
Then have a generic app wrapper take care of routing.

## Potential issues

- how to handle URLs and routing inside that app, those that refresh the whole page ?
    - Router wrapper in core that rewrites the URLs to Phoenix URLs ? how to map Phoenix URLs to app URLs ? (hopefully should be seldom for single page apps anyway)
    - might need some JS magic to catch URLs and redirects and communicate with postmessage??

In the worst case we'd need to add some hacks in the given apps to handle for such corner cases.
Best would be to write the wrapper first to try out and see how far we can go...

**Comment by DeepDiver1975** [comment]
I'd go for the mutli url Micro framework approach Here as well.

**Comment by PVince81** [comment]
Superseded by https://github.com/owncloud/phoenix/pull/2620 which brings Phoenix parts as Web Components into the OC 10 layout.
