### ISSUE TITLE
Separate app switcher from app specific navigation

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2650]
Currently the left sidebar contains both app switch links and app specific navigation

As we intend to make the top bar reusable by any OCIS frontend app, we need to separate them.

- The app switcher will become part of the top-bar component.
- The app specific navigation will become part of the design system, and be used directly by the future phoenix-files app.

~~See https://github.com/owncloud/owncloud-design-system/pull/532 for a possible design~~

## Tasks
- [ ] Update design system page with icon for the new look: https://github.com/owncloud/owncloud-design-system/pull/568
- [ ] Implement the menu separation in Phoenix: https://github.com/owncloud/owncloud-design-system/pull/568

**Comment by PVince81** [comment]
Also see the [micro-frontends](#2473) ticket as this falls into the same category.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/phoenix/pull/2669

**Comment by DeepDiver1975** [comment]
config has bee specified already in #2573 - first section

**Comment by PVince81** [comment]
okay. at first I had a separate file and I remembered a discussion about having it "in the config", but maybe I misunderstood. Having it in a separate file / endpoint is fine, I can bring this back.

**Comment by PVince81** [comment]
next steps: https://github.com/owncloud/phoenix/issues/2746
