### ISSUE TITLE
file type icons

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#267]
Story:

Given a user is logged in 
When different files are uploaded
Then file type icons depending on the mime/type will be displayed

Give a developer is writing a theme
When the theme is holding custom file type icons
Then they need to be used

Tasks:
- Choose default file type icon set (source?) (0.5MB)
- Implement display of icons based on mime type (0.5MD)
- Respect Themability !!!! (0 MD)

**Comment by DeepDiver1975** [comment]
fixed with #406

**Comment by tempelgogo** [comment]
The theming requirement is not fulfilled, but actually our theming is more branding than theming.

**Comment by DeepDiver1975** [comment]
> The theming requirement is not fulfilled, but actually our theming is more branding than theming.

good point - I'll open a new ticket for this ... THX
