### ISSUE TITLE
separate the sidebar completetly into an own pageObject

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2677]
Noticed while working on fixing tests for #2515
The sidebar xpath and work is scattered in different pageobjects: filesPage, filesList, appSideBar

consolidate and combine it all in a single object. Maybe we even need multiple objects for the different tabs.

This should be done on top of #2515 , because that PR changes the sidebar a lot

**Comment by individual-it** [comment]
blocked by #2515

**Comment by individual-it** [comment]
@kiranparajuli589 @swoichha @HariBhandari07 how far are we with this? Is it done?

**Comment by kiranparajuli589** [comment]
Page Objects splitted so far:
1.appSideBar
2.versionsDialog
3.collabratorsDialog
4.publicLinksDialog
5.fileActionsMenu
6.expirationDatePicker

We can have more splits on public link and collaborator dialogs like making separte PO for dialogs to view shares log and forms to add shares.

**Comment by individual-it** [comment]
Then lets close for now, more splitting is not priority currently
