### ISSUE TITLE
Cleanup of scaffolding including docs, blog and stuff.

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#268]
Story:
Give a developer want to work on Phoenix
....

Tasks:
- Final decision on vuetify vs uikit
- Cleanup of naming (uppercase function names - WTF) - partially addressed in oauth pr
- Cleanup on template language, script language and style language (keep it simple? html + ecma5 + css)
- Introduce style tools into drone - eslint

Total effort: 2 MD

**Comment by tempelgogo** [comment]
Regarding the "Final decision on vuetify vs uikit":
https://github.com/owncloud/phoenix/issues/1#issuecomment-430546243

**Comment by tempelgogo** [comment]
Regarding to your _Introduce style tools into drone - eslint_ task:
Do we prefer [https://standardjs.com/](standardjs) or [https://github.com/airbnb/javascript](airbnb) style guide?

The initial fix could make some trouble - we can use the eslint autofix feature, but it's a big commit which is incredible hard to merge if the files are changed elsewhere.
Do you want us to autofix all source files to fit into the eslint style ?

Do we want to use git commit hooks to auto-lint before commit :) ?

**Comment by DeepDiver1975** [comment]
> Do we prefer [https://standardjs.com/](https://standardjs.com)

I'd go for this one ... no semi-collon ... really ....

@PVince81 ^

**Comment by PVince81** [comment]
@DeepDiver1975 I like my semicolons... but if everyone votes against I'm fine

**Comment by scramb** [comment]
The one without semicolon would be my choice.

**Comment by DeepDiver1975** [comment]
okay - lets got for standardjs.com then.

Please add the style + check on drone + one time fix the style on the code base
no auto fix on commit or something - devs have to learn ;-)

**Comment by tempelgogo** [comment]
outsourced blog task into #464 

So it seems, that all requirements of this issue are fulfilled.
 I therefore take the liberty of closing this issue; please reopen it at any time if necessary.
