### ISSUE TITLE
Public link share

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#270]
Story:
Given a public share link was sent to a user
When the user opens the link in the browser
Then the shared content has to be displayed

Questions:
A share link as generated by owncloud backend (e.g. via api from the mobile client) as of today points to the backend server core.own.cloud/index.php/s/123456789
But with phoenix in place the link needs to point to phoenix.own.cloud/#/file-share/123456789

Solution:
When the backend is generating the share link the phoenix base url has to be applied - needs own config value

Tasks:
- change link generation in core (1MD)
- provide proper public share webdav api https://github.com/owncloud/core/pull/29369 (3MD)
- single file public share (1MD)
- read only folder public share (1MD)
- full access folder public share (1MD)
- Upload only public share (1MD)
- password protected links (1MD)

**Comment by PVince81** [comment]
prerequisite: we need to know how the UI / UX looks like when opening a public link:
- same as logged in user ?
- completely different UI ?
- integrate with file viewers / editor somehow ?

**Comment by LukasHirt** [comment]
Closing this since the tasks and discussion has been moved here #1307
