### ISSUE TITLE
Sharing feature

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#272]
Tasks:
- redesign sharing side bar to phoenix and adapt (?MD) (estimate depends on design)
- use js-owncloud-client to integrate (2MD)
- share indicator in file list ?

**Comment by PVince81** [comment]
I think @felixheidecke already has a vuejs mock-up for the sharing side bar. the item sounds like we're copying the old code. I think the sharing side bar is a full rewrite: wire up the mock ups to the APIs

**Comment by PVince81** [comment]
@felixheidecke @pmaier1 we'll need to schedule some time to revive the mock ups and finish the new design

**Comment by PVince81** [comment]
note: js-owncloud-client doesn't have share autocomplete so might need to add it

**Comment by PVince81** [comment]
@felixheidecke please check in the mock ups somewhere so we can have a look. Could be on a branch here or something.

cc @michaelstingl @DeepDiver1975

**Comment by DeepDiver1975** [comment]
we should use this ticket: #583  - I'll close this open as this was more of a general reminder.
#583 is the explicit action in the current sprint
