### ISSUE TITLE
Trashbin Support

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#273]
Story:
Give a user is logged in
When the user opens 'deleted files' (UX to be defined)
Then deleted files are displayed with the information: name, old location, file size, file mtime, file icon and actions to restore and to permanent delete the file

Tasks:
- display trahsbin (1MD)
- add functions to js-owncloud-client to list the trahsbin (2MD)
- add public webdav api to allow access to the trashbin (including acceptance tests): https://github.com/owncloud/core/issues/15646 (4MD)

**Comment by PVince81** [comment]
core ticket for trashbin api for Webdav: https://github.com/owncloud/core/issues/15646
