### ISSUE TITLE
Create new file + extension point

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#274]
Story:
Given a phoenix plugin registers a new file action for text files
And a user is logged in
When the user clicks on new file action (UX to be defined)
Then a dialog/context pops up which lists new files including for text files

When the user enters the new file name and hits enter
Then phoenix core creates the file
And the app code is triggered which opens the file in some editor

Related to #215 

Tasks:
same as with #215 
- Additional effort in phoenix core (1MD)

**Comment by DeepDiver1975** [comment]
- creating new files is already done
- handler registration to open the file right away is missing

**Comment by PVince81** [comment]
We're also missing the extension point to allow for apps to provide additional file types.
For example:
- create text file
- create ODT document
- ...

**Comment by PVince81** [comment]
- [ ] add extension point for other apps to register their types
- [ ] automatically open the file after creation, if the type is known

**Comment by PVince81** [comment]
From a design POV, for now the easiest is to append whatever registered file types are available directly into the dropdown. Any other UX would be more time costy and require thinking about maybe selecting the file type inside the dialog prompt, or something else.

**Comment by DeepDiver1975** [comment]
is this what we want to have? @PVince81 @pmaier1 @LukasHirt 

![Screenshot from 2019-09-27 11-49-26](https://user-images.githubusercontent.com/1005065/65760240-e8a56c80-e11c-11e9-8725-1c7e765210f0.png)

**Comment by LukasHirt** [comment]
I'm not really a fan of how huge is the dropdown becoming but as @PVince81 wrote

> Any other UX would be more time costy

For now 👍 from me. Let's invest more time later to find a better way.

**Comment by DeepDiver1975** [comment]
The way we are building this has an impact on the api on how apps register themselves ... as far as I can tell ...
So we need to accept some duplicate effort here ....

**Comment by PVince81** [comment]
We could also raise the priority for getting design input on this item before desigining the API.

From my POV it will mostly be about registering an icon, a text and an action handler.

**Comment by DeepDiver1975** [comment]
the text will be interesting - in case of menu entry (like above) - the api requires a function which returns the translated full text.
'New Microsoft Word document..' -> 'Neues Microsoft Word Dokument...'

We cannot translate only parts of the text.

In case we go for a different approach the text appears in a different context and might look totally different.

**Comment by PVince81** [comment]
Indeed. But to prevent blocking ourselves we could call this extension point "beta" or "tech preview" to have no stability guarantee but still allow prototyping. The text is likely the least difficult part.

**Comment by DeepDiver1975** [comment]
with #2111 being merged - can we close this - or am I missing anything? THX
@PVince81 @LukasHirt

**Comment by LukasHirt** [comment]
> can we close this

IMO yes
