### ISSUE TITLE
Progress / spinner for all file operations

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#275]
nice to have

**Comment by PVince81** [comment]
needs design @felixheidecke

**Comment by PVince81** [comment]
@pmaier1

**Comment by pmaier1** [comment]
> nice to have

I would even call it a hard requirement for all actions that can take some time. IMO this is a must-have for that the user knows that something is happening.

**Comment by DeepDiver1975** [comment]
we have this almost everywhere -> lets close this
