### ISSUE TITLE
IE tests randomly fail with "Loading folder failed ... Object doesn't support property or method 'finally' "

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2754]
### Steps to reproduce
1. see IE nightly tests

e.g. 
https://app.saucelabs.com/tests/c0b8f35836ea451cb5b262ff4f382180
https://assets.saucelabs.com/jobs/c0b8f35836ea451cb5b262ff4f382180/0010screenshot.png

or
https://app.saucelabs.com/tests/8430d138f0cd44ca88975991e3b02049#124
https://assets.saucelabs.com/jobs/8430d138f0cd44ca88975991e3b02049/0035screenshot.png

**Comment by PVince81** [comment]
I didn't find any reference to "finally" in facf93ebde3becf837cfe8f18753e49e5fc591dc from virtual scroll. So perhaps this is coming from yet another merge in-between.

I'll have a look.

**Comment by PVince81** [comment]
References of `finally` on master:
```
apps/files/src/components/PublicLinks/FilesDrop.vue|139 col 10| }).finally(() => {
apps/files/src/components/PublicLinks/PublicLink.vue|94 col 10| }).finally(() => {
apps/files/src/components/FileInfoVersions.vue|68 col 10| }).finally(_ => {
apps/files/src/components/PrivateLink.vue|45 col 8| }).finally(() => {
apps/files/src/components/FilesAppBar.vue|322 col 10| .finally(() => {
apps/files/src/components/FilesAppBar.vue|378 col 12| .finally(() => {
apps/files/src/store/actions.js|290 col 10| }).finally(() => {
apps/files/src/store/actions.js|329 col 8| }).finally(() => {
apps/files/src/store/actions.js|361 col 8| }).finally(() => {
apps/files/src/store/actions.js|393 col 8| }).finally(() => {
apps/files/src/store/actions.js|684 col 8| .finally(() => context.commit('LINKS_LOADING', false))
apps/files/src/store/actions.js|731 col 8| .finally(() => context.commit('LINKS_LOADING', false))
apps/files/src/mixins/collaborators.js|98 col 10| .finally(_ => {
tests/acceptance/helpers/backendHelper.js|47 col 5| } finally {
```

the last one only runs on the test runner, not the browser.

**Comment by PVince81** [comment]
the screenshot shows the "all files" list as I don't see a "deleted time" column (ref https://app.saucelabs.com/tests/8430d138f0cd44ca88975991e3b02049#124)

so this means the error happened exactly here:
https://github.com/owncloud/phoenix/blob/master/apps/files/src/store/actions.js#L290
 
if it did reach that block, it means that catch() was also executed and it was executed properly
which tells us that the Promise was present and not absent
so maybe it's the polyfill for the Promises's finally that failed

I saw some references to the p-finally library while grepping.

maybe that lib got updated recently ?

**Comment by PVince81** [comment]
the file list did load properly in a former page refresh
https://app.saucelabs.com/tests/8430d138f0cd44ca88975991e3b02049#41

I suspect that sometimes on page load the p-finally polyfill has not been applied properly.

**Comment by individual-it** [comment]
tests are not run on IE11 currently see #2757 
- [ ] enable them again https://dzone.com/articles/open-letter-from-an-ignored-test

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/phoenix/pull/2821 to log more info

**Comment by individual-it** [comment]
IE support dropped :tada:
