### ISSUE TITLE
Refactor test scenarios used for filter feature

### ISSUE THREAD

**Issue by jasson99** [owncloud/phoenix#2787]
The test scenarios written for the filter feature contains then steps which do not seem to clarify the actual results. Those actual steps present now should be refactored with the expected steps for more clarification of the steps

### Expected steps
1. Then all shared-with-me files and folders containing pattern "simple" in their name should be listed on the webUI
2.  Then all trashbin files and folders containing pattern "simple" in their name should be listed on the webUI
3. Then all shared-with-others files and folders containing pattern "simple" in their name should be listed on the webUI
4. Then all favorite files and folders containing pattern "simple" in their name should be listed on the webUI

### Actual steps
1. Then all files and folders containing pattern "simple" in their name should be listed in the shared-with-me page on the webUI
2. Then all files and folders containing pattern "simple" in their name should be listed in the trash on the webUI
3. Then all files and folders containing pattern "simple" in their name should be listed in the shared-with-others page on the webUI
4. Then all files and folders containing pattern "simple" in their name should be listed in the favourites list on the webUI

**Comment by jasson99** [comment]
@phil-davis Can you please help me with the steps(language) so that they would be more clear?

**Comment by phil-davis** [comment]
The "expected steps" look good to me.
