### ISSUE TITLE
User profile is overlapped with the functional elements such as filter button

### ISSUE THREAD

**Issue by jasson99** [owncloud/phoenix#2790]
# Steps to reproduce
1. Login as a user
2. Browse to the files page

### Expected behaviour
The user profile should not overlap with any functional elements when page is opened in the maximum screen size

### Actual behaviour
User profile is overlapped with the filter button when the files page is opened in the maximum screen size

![Screenshot_2019-12-24 ownCloud](https://user-images.githubusercontent.com/40829116/71396127-fe093480-2640-11ea-89c1-4f8d29803122.png)

**Comment by LukasHirt** [comment]
Fixed in #2783
