### ISSUE TITLE
split test suites into smaller parts

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#2874]
some suites take up to 1h to complete, would be good to split them into smaller parts

**Comment by individual-it** [comment]
reopening because the "files" suite takes also over 1h to run
CC @jasson99

**Comment by phil-davis** [comment]
Need to review the run-time of the suites after PR #2893 that was just merged.
See drone https://drone.owncloud.com/owncloud/phoenix/7745

**Comment by kiranparajuli589** [comment]
Latest drone build: https://drone.owncloud.com/owncloud/phoenix/8033/21/1
@swoichha @Talank 
suite `SharingPubic` is taking runtime over 42 minutes...
you can split it too...

**Comment by kiranparajuli589** [comment]
Observing time taken for suites in _Latest drone build:_ https://drone.owncloud.com/owncloud/phoenix/8085 seems fine
@individual-it
