### ISSUE TITLE
See resource owner in share panel

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2898]
- Story: https://github.com/owncloud/enterprise/issues/3773

- [x] show resource owner for direct share: https://github.com/owncloud/phoenix/pull/2915
- [ ] show resource owner for share inherited from parent resource (with "via"): https://github.com/owncloud/phoenix/pull/2918
   - [x] REQUIRES: #2894 
   - [ ] "via" icon must use "redo" icon
- [ ] REQUIRES: additional info field also for owner and resharer: https://github.com/owncloud/core/issues/36823
- [x] reuse branch "share-indirect-info" for some attempts at buildling the UI. We could reuse this and populate with real data.

**Comment by PVince81** [comment]
## Direct share
<img width="957" alt="image" src="https://user-images.githubusercontent.com/277525/72891573-cf03e280-3d14-11ea-924b-e7806b4eda85.png">

## Reshare

Logged in as Dave.
Received a reshare from Bob where the resource owner is Alice.
<img width="958" alt="image" src="https://user-images.githubusercontent.com/277525/72891528-b693c800-3d14-11ea-88a2-f1d2658ce883.png">

## Indirect share through parent

Same as the "Reshare" scenario but showing indirect owner when inside a subdirectory.

<img width="957" alt="image" src="https://user-images.githubusercontent.com/277525/72891646-f955a000-3d14-11ea-8a42-a1dabbcdaf39.png">

@pmaier1

**Comment by pmaier1** [comment]
Very cool :ok_hand: the "via" part in the third screenshot feels still a bit strange to me but maybe this is because of the strange folder name :)

**Comment by PVince81** [comment]
yes, this is just a rough mock up to illustrate the idea.

we'll need to ellipsize the name

**Comment by PVince81** [comment]
@pmaier1 the proposed design above cannot work as there are scenarios where multiple resharers exist for the same resource:

1. "alice" share "test" with user "bob"
1. "alice" shares "test" with user "charlie"
1. "bob" shares "test" with user "dave"
1. "charlie" shares "test" with group "dave-group" (where dave is member).
1. log in as "dave" and query the incoming shares for "test"

=> The API will deliver two incoming share entries:
- shared with dave by bob (user share)
- shared with dave by charlie

Our solution for this is to display owner and all reshares as separate collaborator entries.
