### ISSUE TITLE
Add a nice screenshot in README

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#29]

**Comment by DeepDiver1975** [comment]
![bildschirmfoto von 2018-03-14 17-28-06](https://user-images.githubusercontent.com/1005065/37416039-20817b4c-27ad-11e8-9f14-cbe12936fd64.png)
![bildschirmfoto von 2018-03-14 17-27-40](https://user-images.githubusercontent.com/1005065/37416040-20ad906a-27ad-11e8-8a56-ad5f824743a0.png)
