### ISSUE TITLE
Remove separation of Users and Groups in Collaborators panel

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2900]
- [ ] Merge the "Users" and "Groups" sections in the collaborators panel into a single list
- [ ] Adjust the sorting based on how it's done in OC 10 (not sure if it's sort by type first and then name or name first)

**Comment by kulmann** [comment]
In oC10 it's not sorted at all. I would decide for sorting by name then. Doesn't make sense to lose the separation and then still sort by type.

**Comment by PVince81** [comment]
@pmaier1 are you ok with this decision ? ^

**Comment by pmaier1** [comment]
Yep, let's try this (alphabetical, sorted by share type) :+1:
