### ISSUE TITLE
Shared with column in "Shared with others" should contain multiple users

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2924]
### Steps

1. Create three users "Alice", "Bob" and "Charlie"
1. Login as "Alice"
1. Share a folder "test" with both "Bob" and "Charlie"
1. Open the "Shared with others" panel
1. Look at the "Shared with" column for the "test" folder

### Expected result
Both "Bob" and "Charlie" appear there, separated with a comma.
If more than three users or groups, show an ellipsis for the fourth one (check product requirement there)

### Actual result
Only "Charlie" appears.

The network response does contain two entries so it's a frontend issue.

@pmaier1 FYI

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/phoenix/pull/3049

**Comment by PVince81** [comment]
I went a bit overboard... I've noticed that link shares are now also included so I went a bit further and tried to add some distinction.

In my first attempt (the before last commit), shows share indicators:
![image](https://user-images.githubusercontent.com/277525/74680962-72d09900-51c2-11ea-83c7-b0e775850014.png)

Please note that we cannot show indirect shares there due to performance reasons.

And another further attempt (last commit) with the collaborator list:
![image](https://user-images.githubusercontent.com/277525/74680807-081f5d80-51c2-11ea-837c-901b0a5bb21b.png)

I don't think I'll go further there but we can use this as input for further designs.
As the goal was to just fix the list of collaborators, I might split this PR into "current fix" and "future stuff".

@pmaier1 @LukasHirt

**Comment by LukasHirt** [comment]
It feels a bit weird seeing the link in collaborators column but I understand that it needs to be there 🙈

**Comment by PVince81** [comment]
next iteration here, looks a bit better now with avatars: https://github.com/owncloud/phoenix/pull/3049#issuecomment-591456921
