### ISSUE TITLE
ESLint enforce method order in Vue components

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2926]
Do we want to have a specific format and order for the JSX files, including a specific order for the Vue component sections like "methods", "computed", etc ?

If yes we should research tooling like ESLint to see if this can be enforced and auto-fixed.

@LukasHirt @kulmann 

brought up by @kulmann

**Comment by LukasHirt** [comment]
There was already once discussed using the [vue style guide](https://github.com/owncloud/phoenix/issues/1867) which contains also rules about the order. It was just missing some actual progress.

ESLint is easily capable of taking care of the order. If we'd want to follow all parts of the vue style guide then ESLint can take care of that as well just by changing the level to recommended.
