### ISSUE TITLE
translation-sync is broken

### ISSUE THREAD

**Issue by dschmidt** [owncloud/phoenix#2935]
https://drone.owncloud.com/owncloud/translation-sync/1418/31/4

### Expected behaviour
Translations can be synced

### Actual behaviour
phoenix pipeline fails every day making the whole job fail

**Comment by DeepDiver1975** [comment]
nodejs needs to be updated

```
error husky@4.0.7: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.12.0"

**Comment by dschmidt** [comment]
https://github.com/owncloud-ci/transifex/pull/2

**Comment by dschmidt** [comment]
https://drone.owncloud.com/owncloud/translation-sync/1419 

fixed!
