### ISSUE TITLE
Animations broken on adding/deleting public links or collaborators

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#2937]
When a public link or collaborator is added or removed, the `transition-group` on the respective list can't do it's job (sliding in the new list item / out the removed one) because the links/shares receive a `LINKS_LOADING` / `SHARES_LOADING` state in the store. I think we're overusing the mutation - the animation would already do the job of showing a change in the respective list UI. Triggering the loading progress bar through the mutation is a) not necessary and b) (more important) disrupts the UI, as the whole panel is hidden while the loader is shown.

I would like to remove the mutation on adding and removing links/collaborators. Thoughts and concerns about this?

**Comment by PVince81** [comment]
As discussed, we can remove the progress bar for "save" operations as we already have a spinner in the edit form.
