### ISSUE TITLE
Share indicators appear delayed

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#2973]
### Steps

1. Create a folder "test"
1. Share "test" with link or a collaborator
1. Refresh the page and observe closely the progress bar and the indicators

### Expected result
Indicator appears immediately after the progress bar disappears.

### Actual result
First the progress bar disappears, the file list appears, and then after a second the share indicator appears

### Version
v0.3.0

This is a regression as it used to work when I worked with sharing indicators.
The code that loads the share indicators was designed to happen while the progress bar is still shown. In other words, the progress bar should show as long as neither file list nor indicators have finished loading.

Could this be related to your changes @LukasHirt ?

cc @kulmann if you want to look into this

**Comment by LukasHirt** [comment]
It probably is related to my change (#2928). The component with the indicators is now separated. The load process might need to be adjusted because now indicators wait for the list to be loaded which can cause the delay.

I'd maybe suggest moving the display logic of files list into components where it's used instead of FilesList component.

**Comment by PVince81** [comment]
@Julian1998 any update ? Please unassign if you don't intend working on this as you're blocking other people who might want to take over. Thanks.

**Comment by Julian1998** [comment]
@PVince81 Still working on it.... just need to figure out some vue things first.
As discussed with @LukasHirt I need to seperate the share indicator loading process from the file list loading process.... but it is not really synced then. I am searching for a workaround
