### ISSUE TITLE
Pure web frontend

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#3]
Phoenix should be a pure web frontend / web client.

In an ideal world we drop the front end into a web space for hosting and a config parameter (json file?) points the client to the existing owncloud backend instance.

**Comment by tboerger** [comment]
A json file is the only option without a build step... Or SSI which is only supported by a few Webservers and should be a no-go

**Comment by PVince81** [comment]
@SamuAlfageme pointed out the fact that such frontend code could be used by mobile apps as well in a web view

**Comment by DeepDiver1975** [comment]
This is implemented -> close
