### ISSUE TITLE
Delete file from search result

### ISSUE THREAD

**Issue by Talank** [owncloud/phoenix#3043]
### Steps to reproduce
1. Upload a file named "a1.txt" given that there is no such file with the same name existing anywhere.
2. in the search box search for the file "a1.txt"
3. from the search result, delete the file "a1.txt"

### Expected behaviour
1. The file should be disappeared from the search results 
2. And the pop up window should disappear after selecting `CANCEL` or  `OK`

### Actual behaviour
1. The pop up is still visible
2. And the file is not removed from the search list until refreshed.
![out-3](https://user-images.githubusercontent.com/27364813/74635196-9d542f00-518d-11ea-920c-8359e6e37b25.gif)

### Server configuration
**Current core master**
**Current phoenix master**

**Comment by individual-it** [comment]
@Talank do we have tests that demonstrate that issue?

**Comment by Talank** [comment]
There is a test for https://github.com/owncloud/phoenix/issues/3044 which is similar to this issue, but we do not have any test written to demonstrate this issue.
