### ISSUE TITLE
File do not disappear from search result after deleting it.

### ISSUE THREAD

**Issue by Talank** [owncloud/phoenix#3044]
### Steps to reproduce
1. Given that there is a file with the name "a1.txt" in the trash bin.
2. Upload a file named "a1.txt" 
3. In the search box search for the file "a1.txt"
4. From the search result, delete the file "a1.txt"

### Expected behaviour
The file should be disappeared from the search results.

### Actual behaviour
The file "a1.txt" does not disappears from the search results.
![out-7](https://user-images.githubusercontent.com/27364813/74636834-e78adf80-5190-11ea-8af4-d202394e418b.gif)

### Server configuration
**Current core master**
**Current phoenix master**

**Comment by PVince81** [comment]
I suspect that the model/collection that is used to back the search result list is different than the one from the main file list.

Upon deletion of an entry (or modification), we should adjust the entry also in the search result list.

@Talank a similar case to test/report: can you check if the sharing indicator (person/link icon in the row) appears/disappears when creating/deleting shares from the search list ?

**Comment by Talank** [comment]
@PVince81 the sharing indicator and the link icon also does not appear/disappear when creating/deleting shares from the search list.
