### ISSUE TITLE
Overwrite dialog wording

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#3047]
### Steps

1. Upload a file "test.txt"
1. Upload it again

### Expected

- if versions app enabled, the text should say "Create new version"
- otherwise it should say "Overwrite"

cc @pmaier1

**Comment by LukasHirt** [comment]
In product used to be written that when versioning is enabled it should create a new version directly without the confirmation. Was this changed or should I add a todo into the code? @pmaier1

**Comment by PVince81** [comment]
If not too complex to do I guess we could go directly with the "no dialog prompt".

**Comment by kulmann** [comment]
I would suppose that many users don't want to deal with the concept of versions (until they need it). So for easy UX the way to go would be, not to ask the user about it and just create the new version.

**Comment by LukasHirt** [comment]
> If not too complex to do I guess we could go directly with the "no dialog prompt".

Well, if I remember correctly there were plans for some changes in the upload logic, wasn't there? I think something about moving them to sdk. If it's still the plan then I'd prefer to implement some bigger changes afterwards.

**Comment by PVince81** [comment]
Nice how GDrive does it, it does overwrite the files but shows a warning, and the upload popup gives you the option to still split the file:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/277525/75024462-bb75a400-5499-11ea-9464-a0ad9fc22703.png">
