### ISSUE TITLE
fix error message test-code

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#3055]
The step `Then an error message "..." should be visible` only checks for a message inside the popup, so better rename that step.
Also the corresponding xpath is called `@fileAlreadyExistAlert`, what is a bit narrow

**Comment by individual-it** [comment]
maybe we can get rid of the step completely and use `the error message {string} should be displayed on the webUI dialog prompt`
https://github.com/owncloud/phoenix/blob/e6847f24ae5cca8eea4ff7fb10f86e315a85cc0c/tests/acceptance/stepDefinitions/generalContext.js#L47

**Comment by kiranparajuli589** [comment]
#3059 has been merged! closing this...
