### ISSUE TITLE
fix confusing error message step wordings in test-code

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#3062]
we have two similar steps
`Then('the success/error message {string} should be displayed on the webUI', function (message) {`
and
`Then('the following success/error message should be displayed on the webUI', function (message) {`

the first one checks only the header of the error message and accepts only one line of input, the second one checks the whole error message and accepts PyString as input. We need to rename one to distinguishes them more.
e.g. add some words about "header" in the first one

**Comment by kiranparajuli589** [comment]
@individual-it requested changes have been addressed!

**Comment by individual-it** [comment]
in which PR?

**Comment by individual-it** [comment]
fixed by  #3064
