### ISSUE TITLE
write more tests for private links

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#3096]
after #3072 more tests should be written to test more scenarios of the private links

- [ ] navigating to private links as the owner
- [ ] navigating to private links as a collaborator
- [ ] navigating to private links as a user, that does not have permissions to see the file

**Comment by jasson99** [comment]
@Talank work on this when you are on the similar issue

**Comment by Talank** [comment]
@individual-it the feature `tests/acceptance/features/webUIPrivateLinks/accessingPrivateLinks.feature` already tests for the scenario where user navigates to private links as the owner.
