### ISSUE TITLE
Redirect url with query parameters

### ISSUE THREAD

**Issue by C0rby** [owncloud/phoenix#3285]
This is important to get the logout finally working.
After a user logs out the oidc provider sends a redirect to `https://localhost:9200?state=`.
If the user tries to login again it won't work because the url is incorrect. The query parameter must be placed to another position.

### Steps to reproduce
Logout of phoenix

### Expected behaviour
The page gets redirected to login and the url looks like this
`https://localhost:9200/#/login?state=`

### Actual behaviour
The page gets redirected to login and the url looks like this
`https://localhost:9200/?state=#/login`

### Client configuration
**Browser:**
Any browser

**Comment by C0rby** [comment]
Some things I found:
https://github.com/vuejs/vue-router/issues/2125

**Comment by C0rby** [comment]
I think the easiest way would be to set `baseUrl + '#/login'` as the redirect uri.

**Comment by individual-it** [comment]
reopening and adding QA-team label to add tests

**Comment by Talank** [comment]
It looks like the pattern of redirect uri is not fixed. I tried to reproduce the issue using the current phoenix build with ocis backend. I am still being redirected to `https://localhost:9200/?state=#/login`

**Comment by C0rby** [comment]
Can you provide more context? Are you doing the logout manually?
The fix was working fine with ocis so I'm a bit suprised.

**Comment by Talank** [comment]
When I do log out manually, then it takes me to `https://localhost:9200/#/login?state=` but when I try to go to `https://localhost:9200?state=` it takes me to `https://localhost:9200/?state=#/login`

**Comment by C0rby** [comment]
Why would you like to go to `https://localhost:9200?state=`?. I mean why do you need the state attribute? It's only needed for the openid flow.

**Comment by individual-it** [comment]
> Why would you like to go to `https://localhost:9200?state=`? I mean why do you need the state attribute? It's only needed for the openid flow.

because that is what the issue says :

> Steps to reproduce
> Try to open https://localhost:9200?state=

is there an misunderstanding?

**Comment by C0rby** [comment]
Ah right, sorry....
I totally didn't get that.. Yeah the issue description is incorrect.
Let me change that

**Comment by individual-it** [comment]
@C0rby :+1: THX for clarification
@Talank lets just add UI tests where the user logs out using the UI and then tries to login again, if that works in all the environments we test automatically we should be fine

**Comment by dpakach** [comment]
tests done in #3572
