### ISSUE TITLE
Repo description has a broken link

### ISSUE THREAD

**Issue by dschmidt** [owncloud/phoenix#3289]
Repo description is `Next generation frontend for ownCloud https://phoenix.owncloud.com/custom/phoenix/index.html#/login` 

Link points to a 404 error page. https://phoenix.owncloud.com/ lets me login to demo.owncloud.com :)

**Comment by kulmann** [comment]
Correct url would be `https://phoenix.owncloud.com/index.html#/login`

**Comment by dschmidt** [comment]
well I am automatically redirected to that from /.

**Comment by dschmidt** [comment]
Yeah, who can edit the repo settings? I don't have the needed permissions :)

**Comment by LukasHirt** [comment]
> Yeah, who can edit the repo settings?

@PVince81 I guess should have the perms. But we'll need to wait until he's back from vacation. Otherwise would need to ping admin team.

**Comment by PVince81** [comment]
I've now adjusted the repo description to point to https://phoenix.owncloud.com which anyway redirects to the login page.
