### ISSUE TITLE
Click on public link share indicator is broken

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3324]
### Steps to reproduce
1. run phoenix from current master 
2. click on the `link` share indicator of a folder in the files list
3. it opens the sidebar, but has the first tab active, not the public links panel.

### Expected behaviour
Sidebar should open in the `links` panel

### Actual behaviour
Click opens the sidebar, but has the first tab active, not the public links panel.

### Client configuration
**Browser:** Chrome 80.0.3987.163

**Operating system:** macOS 10.14.6

#### Browser log
Javascript console shows
```
client.js:270 PROPFIND http://host.docker.internal/px1/remote.php/dav/meta/undefined/v 404 (Not Found)
```

**Comment by PVince81** [comment]
tagging as regression, would be good to fix soon

**Comment by PVince81** [comment]
the PROPFIND seems to be from the versions tab

**Comment by individual-it** [comment]
same issue for the collaborator indicator
looks like we should have a test for that

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/phoenix/pull/3420
