### ISSUE TITLE
Error at command "yarn dist" when have "src" folder name in path

### ISSUE THREAD

**Issue by JarCz** [owncloud/phoenix#3338]
When I'm try to compile "phoenix" with "src" folder name in path I'm had a error:

```
"export 'default' (imported as 'wgxpath') was not found in 'wicked-good-xpath'
 @ multi whatwg-fetch ./src/phoenix.js

ERROR in ./node_modules/owncloud-design-system/dist/system/system.css (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./node_modules/owncloud-design-system/dist/system/system.css)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (/home/dev/src/phoenix/node_modules/css-loader/dist/cjs.js!
.....
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/vue-resize/dist/vue-resize.css:
    Entrypoint mini-css-extract-plugin = *
     [0] (webpack)/buildin/harmony-module.js 631 bytes {0} [built]
    [93] (webpack)/buildin/global.js 475 bytes {0} [built]
        + 119 hidden modules
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Done in 131.70s.
```
### Steps to reproduce
1. make dir "src"
2. go to "src" folder and work with tutorial: https://reva.link/docs/tutorials/phoenix-tutorial/
3. after command "yarn dist" you will have "error 

or short steps
```
cd ~
mkdir src
cd src/
git clone https://github.com/owncloud/phoenix
git clone https://github.com/cs3org/reva
cd phoenix/
cp ../reva/examples/oc-phoenix/phoenix.oidc.config.json config.json
yarn install
yarn dist
```
### Quick fIx:
rename folder "src" to another name

### Expected behaviour
Can compile and work when have "src" folder name in path

### Server configuration
1. tested on nodejs: v10, v12, v13
2. npm 6.4.14
3. yarn 1.22.4
4. fresh version of "reva" and "phoenix" from github clone

**Comment by DeepDiver1975** [comment]
maybe you are missing the yarn install-all command - see https://github.com/owncloud/phoenix#building-phoenix

**Comment by LukasHirt** [comment]
> maybe you are missing the yarn install-all command - see

That should run as part of the `dist` command. If not then need to be also debugged.

**Comment by JarCz** [comment]
I'm work with this tutorial https://reva.link/docs/tutorials/phoenix-tutorial/
and try to compile it in diffirent location:
* for path: "home_folder/src/phoenix" can't compile - have error
* for path "home_folder/projects/phoenix" - works corectly

**Comment by LukasHirt** [comment]
Seems that it was happening because of babel transpiling of node modules. Changed in #3339. @JarCz Could you pls checkout to that branch and see if it works for you now in `src` subfolder? Worked for me now.
