### ISSUE TITLE
make tests accept self-signed SSL certificates for API requests

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#3455]
we want to be able to set `SERVER_HOST` in OCIS tests to `https://localhost:9200` to use the port 9200 everywhere

**Comment by dpakach** [comment]
waiting for some response in https://github.com/owncloud/ocis/issues/301
blocked until then.

**Comment by dpakach** [comment]
tests now work with auto generated ssl certificate while running ocis
