### ISSUE TITLE
Add settings tests

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3491]
As soon as ocis has the settings service available, we can change the drone environment to include ocis-settings. Then a good first test is, to check if the selected language actually changes when modified in the settings ui.

**Comment by PVince81** [comment]
@individual-it

**Comment by dpakach** [comment]
Blocked by https://github.com/owncloud/ocis-settings/issues/37

**Comment by dpakach** [comment]
owncloud/ocis-settings#37 is Fixed. 
Now needs ocis-proxy to be updated in the single binary for the settings to work.
