### ISSUE TITLE
Disable failing upload tests

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#3492]
seems now we have issues again, even with latest reva: https://cloud.drone.io/owncloud/ocis-reva/376/3/11 from https://github.com/owncloud/ocis-reva/pull/221

this is blocking the ocis-reva release, even the one that we had before where CI passed before we unskipped the tests

**Comment by PVince81** [comment]
any reason why we don't  get a nice summary of all failures for Phoenix tests ??

see https://cloud.drone.io/owncloud/ocis-reva/376/3/11 at the end there is no list of failed tests.
however for API there usually is

@individual-it @dpakach

**Comment by PVince81** [comment]
I also don't get how they could be passed in a way that led us to merge https://github.com/owncloud/phoenix/pull/3457

**Comment by dpakach** [comment]
> any reason why we don't get a nice summary of all failures for Phoenix tests ??
> 
> see https://cloud.drone.io/owncloud/ocis-reva/376/3/11 at the end there is no list of failed tests.
> however for API there usually is
> 
> @individual-it @dpakach

@PVince81 it shows the summary ( you can see starting line 5750 in that build)
But since it even shows all the steps in the scenarios it kinda defeats the purpose of the summary.

As for the failures I think its missing some configuration variables here, I am trying it right now.

**Comment by dpakach** [comment]
I have added all missing env variables from that are in phoenix in https://cloud.drone.io/link/owncloud/ocis-reva/tree/refs/pull/223 , If that passes we can quickly merge it and have green CI

**Comment by PVince81** [comment]
fixed through https://github.com/owncloud/ocis-reva/pull/223

thanks a lot!
