### ISSUE TITLE
public links: missing url on public link when clicking the "copy" icon

### ISSUE THREAD

**Issue by labkode** [owncloud/phoenix#3549]
Tested on ocis-latest.owncloud.com

I get:
```
/#/s/TTiAKODzgekN
```
Phoenix should add the hostname.

**Comment by LukasHirt** [comment]
Probably related - https://github.com/owncloud/ocis-phoenix/issues/52

**Comment by PVince81** [comment]
not related to private links

we fixed this already in https://github.com/cs3org/reva/pull/945
