### ISSUE TITLE
Favorite file not working

### ISSUE THREAD

**Issue by scramb** [owncloud/phoenix#357]
### Pull Requests & Issues 
- refs #345

### Steps to reproduce
1. yarn install && yarn run watch
2. login using oauth
3. click star to mark file as favorite

### Expected behaviour
The File where the star is clicked should be marked as favorite

### Actual behaviour
The File is marked temporary but after reload the changes are reverted - no updated to oc-core

#### Browser log
Insert your browser log here, this could for example include:

![2018-11-27-132954_1916x976_scrot](https://user-images.githubusercontent.com/37431066/49081870-70de8b00-f248-11e8-86b3-d0f7b6f3239a.png)

**Comment by DeepDiver1975** [comment]
ah - again the issue with npm packages which are git referenced ...maybe an issue with yarn ... no idea

**Comment by DeepDiver1975** [comment]
yarn cache clean && yarn install fixes this for me ...

**Comment by DeepDiver1975** [comment]
> yarn cache clean && yarn install fixes this for me ...

@scramb @tempelgogo

**Comment by scramb** [comment]
@DeepDiver1975 yes did fix it for me aswell... 
will close this.
