### ISSUE TITLE
phoenix translation sync failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/phoenix#3603]
See issue https://github.com/owncloud/translation-sync/issues/35

Needs someone to investigate.

**Comment by phil-davis** [comment]
@micbar who looks after this sort of thing?

**Comment by micbar** [comment]
any engineer capable of doing it :-)
@lhirt @kulmann ?

**Comment by kulmann** [comment]
It looks like easygettext doesn't support `??` (nullish coalescing operator), which is used in `src/store/modal.js`.

There are two ways of fixing this:
1: fall back to `||`. Need @LukasHirt to clarify, if that is valid or if it breaks his idea of the implementation.
2: add support for parsing `??` upstream, can probably be done similar to this: https://github.com/laget-se/react-gettext-parser/commit/cc9d71d6a21c65f401525d17fd74ab1cbd22da04

**Comment by LukasHirt** [comment]
> 1: fall back to ||. Need @LukasHirt to clarify, if that is valid or if it breaks his idea of the implementation.
> 2: add support for parsing ?? upstream, can probably be done similar to this: laget-se/react-gettext-parser@cc9d71d

There shouldn't be a real issue with using OR operator. The idea was to use the nullish coalescing one since in some modal values it is valid to pass `false`. So it doesn't break anything but simply doesn't look nice when it uses `false` backup value instead of the one that was passed.

**Comment by LukasHirt** [comment]
> add support for parsing ?? upstream, can probably be done similar to this: laget-se/react-gettext-parser@cc9d71d

Easygettext seems to be using acorn for parsing the JS code which should support nullish coalescing operator https://github.com/acornjs/acorn/pull/890 upstream is using some outdated version?

**Comment by phil-davis** [comment]
Still failing - e.g. https://drone.owncloud.com/owncloud/translation-sync/1583/33/5

So no new translations are coming.

**Comment by LukasHirt** [comment]
> Nobody has been assigned to this issue.

I'll take care.

**Comment by phil-davis** [comment]
Translations arrived last night - https://github.com/owncloud/phoenix/commit/cce62d12b94db22537741b512f8a0fe338607480
Works

**Comment by phil-davis** [comment]
Some translation came, but last night: https://drone.owncloud.com/owncloud/translation-sync/1588/33/5
```
tx INFO: Pushing source file (template.pot)
tx ERROR: Could not upload source file. You can use --skip to ignore this error and continue the execution.
tx ERROR: [Errno 2] No such file or directory: '/drone/src/phoenix/apps/files/l10n/template.pot'
make: *** [l10n-push] Error 1
Makefile:81: recipe for target 'l10n-push' failed
```

And `apps/files/l10n/template.pot` does not exist in the phoenix repo.

@LukasHirt or someone ???

**Comment by LukasHirt** [comment]
Agh... I used again the optional chaining operator 🤦 I'll get rid of it. Need to hammer it down my head to stop using them

https://github.com/owncloud/phoenix/blob/41f0791f034a7d94e8076cc02627638fa83a3f1a/apps/files/src/components/LocationPicker/LocationPicker.vue#L215

I'll see if I can get that running upstream with the acorn parser and if yes submit a PR there. It's annoying not to be able to use such nice features.

**Comment by LukasHirt** [comment]
Sync is passing again for the past few days - closing
