### ISSUE TITLE
Role selection button broken with new button style

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3615]
With the new button style, coming in when https://github.com/owncloud/owncloud-design-system/pull/791 gets released and included in phoenix, the "Role selection" button will visually be broken. See screenshot.

### Steps to reproduce
1. Link ODS dependency to https://github.com/owncloud/owncloud-design-system/pull/791 (checkout and run build:system target, then `yarn link "owncloud-design-system"` in phoenix)
2. run phoenix
3. go to public link creation or adding a collaborator

### Expected behaviour
Alignment should be horizontally left and vertically centered.

### Actual behaviour
Alignment is horizontally centered and vertically just off.

### Screenshot with old button style
![Screenshot 2020-06-16 at 11 39 00](https://user-images.githubusercontent.com/3532843/84758726-23f70c80-afc6-11ea-91f7-17ac4a05c2a9.png)

### Screenshot with new button style
![Screenshot 2020-06-16 at 11 08 41](https://user-images.githubusercontent.com/3532843/84758776-2fe2ce80-afc6-11ea-9291-015b43e3e409.png)

**Comment by kulmann** [comment]
cc @LukasHirt

**Comment by LukasHirt** [comment]
For that specific button, it's fixed when updating the ODS in #3621 I'd see this more about creating a real select component still though. There is an issue in ODS about this https://github.com/owncloud/owncloud-design-system/issues/762

Let's close this issue after the mentioned PR gets merged?

**Comment by kulmann** [comment]
fixed
