### ISSUE TITLE
Unneeded services in OCIS pipelines

### ISSUE THREAD

**Issue by phil-davis** [owncloud/phoenix#3635]
e.g. https://drone.owncloud.com/owncloud/phoenix/10123/35/6

The `webUIOCIS*` suites are running services:

`owncloud` - that looks like it is running Apache and just "sitting there"
`install-core` - it does `wget -qO- https://download.owncloud.org/community/daily/owncloud-daily-master-qa.tar.bz2` - why would we need anything from that when testing Phoenix against OCIS?

Maybe we can remove these ffrom the CI when testing OCIS? It will make sure that we are not accidentally depending on some ownCloud10 core thing for OCIS.

**Comment by phil-davis** [comment]
@dpakach or @individual-it ?

**Comment by dpakach** [comment]
Yes I think you can remove those not really required there.
