### ISSUE TITLE
Quick action for adding collaborators creates a JS error

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3674]
![Screenshot 2020-06-25 at 10 26 51](https://user-images.githubusercontent.com/3532843/85684780-b71ef900-b6ce-11ea-8f1c-36c16e2b8584.png)

**Comment by LukasHirt** [comment]
Not really an error coming from quick actions. You can reproduce it also by simply accessing the edit options and the issue is that ocis does not return (yet?) `expire_date` key in user and group sharing.

**Comment by kulmann** [comment]
Thank you for taking care!
Note to self: `environment = ocis` is important info in the issue description. 🤦  Sorry about that.

**Comment by LukasHirt** [comment]
> Note to self: environment = ocis is important info in the issue description. 🤦 Sorry about that.

No worries 😉 I, on the other hand, need to start testing commits also with oCIS and not only oC10 😁
