### ISSUE TITLE
Quick action for adding public links is broken

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3675]
![Screenshot 2020-06-25 at 10 27 42](https://user-images.githubusercontent.com/3532843/85684838-c605ab80-b6ce-11ea-8935-ac1ef218ec87.png)

**Comment by LukasHirt** [comment]
Strange... It's okay to create a public link without passing `permissions` key in oC10 but in oCIS it throws this error. For now, I'll hard code it to `1` since there are no default perms for links.
