### ISSUE TITLE
Inconsistent behavior when clicking on file list row

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#3685]
### Steps

1. Create a folder
1. Click on the row, but not on the name

### Expected result
Sidebar opens.

### Actual result
Sometimes the sidebar opens, sometimes it navigates into the folder.
This is what the end user perceives.

But the actual reason is that the name element is wider than expected:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/277525/85993887-49890a80-b9f7-11ea-93b2-97ef67fb651f.png">

If you click on the empty space inside the name element, it will do as if you clicked on the name.
Since the user doesn't see that element, it is confusing.

### Version
Phoenix 0.11.0

Discovered by @refs 

@LukasHirt FYI

**Comment by refs** [comment]
👏
