### ISSUE TITLE
Sharing sidebar app

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#37]
The sharing sidebar mock up of Phoenix must be moved to a new app based on webpack + vue JS + UI Kit, with everything that we usually need for a marketplace app (Makefile, etc).

The app in question will only contain frontend parts, with additional boilerplate to make sure said frontend still works with ownCloud 10.0.x and can register its panel into the files app sidebar.

**Comment by SamuAlfageme** [comment]
Oh yes - this would ease integrating the sidebar as an Office Add-in greatly:

<p align="center">
  <img src="https://docs.microsoft.com/en-us/office/dev/add-ins/images/dk2-agave-overview-07.png"/>
</p>

ref. https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins#extending-and-interacting-with-office-clients

Basically, bringing all the options in there (sharing, tags, comments, versions...) to the file open on the different office applications.

**Comment by PVince81** [comment]
@SamuAlfageme not so fast. This is only about the "Sharing" tab, not the other ones.

But maybe what you mean is that if the frontend code is completely separate, it could even be used in a "web view" in mobile apps ? If yes, goto https://github.com/owncloud/phoenix/issues/3

**Comment by SamuAlfageme** [comment]
@PVince81 Yeah, I was thinking all the sidebar component will encapsulate the "collaborative" actions (translated into OCS/WebDAV requests). As if you took the sidebar on the browser and just throw it inside the office app (just focused on the actions available on the open file - w/ no chance of navigating to other apps/sections of the frontend). 

But even if they're separate small [web-components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) - we could map each to a different office add-in inside an "ownCloud" office top-bar section.

Imagine a world where an MS Office app could use the (already authenticated) client to request a "nonce" (a one-time-token https://github.com/owncloud/client/issues/633#issuecomment-52024677), use it to authenticate this web component (so the user is logged in transparently) and that MS Word, Excel, PPT... to be reactive to any action performed on the sidebar. I think many users will be interested to live in that world 😃

**Comment by DeepDiver1975** [comment]
I'm closing this - this is unrelated to the tasks for phoenix 0.2.0
