### ISSUE TITLE
UI tests files app

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#373]
Copy scenarios from OC 10.
Check which are not relevant.

Estimate how much to implement them for Phoenix

@DeepDiver1975 FYI

**Comment by individual-it** [comment]
copy from  #498:

-  check what features are available in phoenix currently
-  copy the feature files for the corresponding features from core
-  adapt the feature files where needed

the feature files should describe high level requirements and not the details of the workflow or the UI

this will also be uses to discuss features with PM and other stake-holders

**Comment by individual-it** [comment]
@DeepDiver1975 do you want to add this to the current sprint as you have done with #498

**Comment by PVince81** [comment]
this will move to the Phoenix sprint. backlogged there

**Comment by DeepDiver1975** [comment]
This has been heavily worked on -> close
