### ISSUE TITLE
do not add border to filelist when clicking it

### ISSUE THREAD

**Issue by butonic** [owncloud/phoenix#3747]
### Steps to reproduce
1. click in the white area below the existing files

### Expected behaviour
nothing should visually change

### Actual behaviour
The file list gets a border.

**Comment by PVince81** [comment]
related: https://github.com/owncloud/phoenix/issues/3046

**Comment by kulmann** [comment]
duplicate of https://github.com/owncloud/phoenix/issues/3551

**Comment by kulmann** [comment]
fyi, PR is already here: https://github.com/owncloud/phoenix/pull/3752
