### ISSUE TITLE
[Acceptance tests] Add more acceptance tests for copy and move

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#3750]
#3739 and #3749 covers only basic tests but there is quite a lot more that can be tested. Let's gather possible scenarios here.

- [x] Test a move/copy to a folder where a user hasn't got enough permissions (the folder is greyed out and is not possible to navigate into it)

/cc @individual-it

**Comment by individual-it** [comment]
fixed by #3772
