### ISSUE TITLE
Wrapper to deliver Phoenix as marketplace app for 10.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#38]
We could put the files app component into a separate frontend app that can be delivered over marketplace.

Or should we deliver the whole layout ?

**Comment by DeepDiver1975** [comment]
I'd go for the full layout.

Steps to do:
1. create app phoenix
2. add a public route to /apps/phoenix which will deliver the phoenix webui
3. add navigation entry 'Phonix' which will load the full layout
4. also add alternative login button to the login screen
5. add a ribbbon to phoenix itself to get back to the old ui (basically a link to index.php)

**Comment by DeepDiver1975** [comment]
already implemented
