### ISSUE TITLE
UI test for "Hide search bar" setting

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#3818]
a test is needed for https://github.com/owncloud/phoenix/pull/3817/
the main challenge here will be to edit the config json file from the test step, and maybe a reload of phoenix is needed alsoe

alternatively we can have two separate tests for OCIS & for oC10, with separate config json files as input

**Comment by kulmann** [comment]
Just tested with page reload. In case you start ocis with `PHOENIX_WEB_CONFIG=/path/to/config.json ./bin/ocis server` it actually works **without** ocis restart to edit the config + see the change after a browser reload.
