### ISSUE TITLE
Mediaviewer doesn't react to navigation for video files

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3831]
### Steps to reproduce
1. Create a folder with at least two video files
2. Open one of the video files in media viewer
3. Use the mediaviewer navigation to switch to the next video

### Expected behaviour
The mediaviewer should load the next video file from the folder

### Actual behaviour
The filename of the next video is shown, but the loaded media source is still the same

**Comment by LukasHirt** [comment]
I wonder if having dynamic `key` would be enough or if we'll have to call a `reload` on the `video`

**Comment by kulmann** [comment]
> I wonder if having dynamic `key` would be enough or if we'll have to call a `reload` on the `video`

Yes, it does exactly that 👍
