### ISSUE TITLE
Mediaviewer additional tests

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3842]
Would be nice to have additional mediaviewer tests for:
- [x] https://github.com/owncloud/phoenix/issues/3831 (when navigating from one to the next video, the video playback / loaded video should change)
- [x] https://github.com/owncloud/phoenix/issues/3832 (video playback should also work on public links)

@individual-it

**Comment by kiranparajuli589** [comment]
Additional media viewer tests are added!
