### ISSUE TITLE
Wrong URL for accessing folders from ‘Shared with me’ tab

### ISSUE THREAD

**Issue by ishank011** [owncloud/phoenix#3896]
When accessing a file in a shared folder from the ‘Shared with me’ tab, the request goes to `/#/files/list/folderName`, resulting in an error. It should instead go to `/#/files/list/Shares/folderName` (that would also only work if the share has been accepted and a reference has been created).

**Comment by kulmann** [comment]
This was recently fixed by @C0rby with https://github.com/cs3org/reva/pull/1346 - not a frontend issue.
