### ISSUE TITLE
Input for sharing tab

### ISSUE THREAD

**Issue by pmaier1** [owncloud/phoenix#39]
I want to collect/reference input for the sharing tab in here.

**Comment by PVince81** [comment]
@felixheidecke mind posting a screenshot of the latest mock ups ? we could use these as a reference for discussion

**Comment by pmaier1** [comment]
- Public links: Add a possibility to send link passwords via SMS @hodyroff

**Comment by felixheidecke** [comment]
![bildschirmfoto vom 2018-05-04 09-22-40](https://user-images.githubusercontent.com/12717530/39616638-c15e87ca-4f7c-11e8-875d-80fa50a85fbd.png)

> The users are requesting for the extra click that would provide them with the knowledge that they physically carried out a positive action to share a file/folder.

This is a crucial point of a positive reinfocement and a good user experience. Let the users know that they are in controll of what is going on. Even at the expense of have yet another button to click or any other action to carry out, users greatly appreciate being in control (or at leas feeling like they are).

Rember little children wanting to do everything by them selves (tying shoes, pushing carts, …) and not have their parents do it for them. I would like to go into more detail … another time perhaps :-)

**Comment by felixheidecke** [comment]
I only have this german reference:

> Die Steuerbarkeit ist einer der Grundsätze zur benutzerfreundlichen Dialoggestaltung aus der Norm DIN EN ISO 9241-110.

> Der Nutzer sollte immer dazu in der Lage sein, seine Interaktion mit dem Produkt selbst zu lenken. Er behält die Kontrolle darüber, wann er Aktionen beginnt, unterbricht oder abbricht.

[usability.de](https://www.usability.de/usability-user-experience/glossar/steuerbarkeit.html)

**Comment by DeepDiver1975** [comment]
dup #1186
