### ISSUE TITLE
UX: progress circle when searching is placed in a strange place.  

### ISSUE THREAD

**Issue by labkode** [owncloud/phoenix#3909]
It feels to close to the text

<img width="182" alt="Screenshot 2020-08-06 at 08 47 43" src="https://user-images.githubusercontent.com/5175912/89500149-80ee9200-d7c1-11ea-9122-7da89493ce46.png">

**Comment by kulmann** [comment]
Related https://github.com/owncloud/owncloud-design-system/issues/776

**Comment by pmaier1** [comment]
Which search is that? The file search bar? Can't reproduce, is this still the case?

**Comment by labkode** [comment]
Not reproducible in latest version available at phoenix.owncloud.com
