### ISSUE TITLE
UX: The session should be refreshed without sending users to the login page

### ISSUE THREAD

**Issue by labkode** [owncloud/phoenix#3916]

**Comment by PVince81** [comment]
I thought we fixed this a few weeks ago, at least in OCIS ? @LukasHirt @micbar

**Comment by LukasHirt** [comment]
There was some PR for oCIS but am not sure if it was released and if it affects also oC10.

**Comment by kulmann** [comment]
For oCIS the correct refresh will be released with the upcoming beta9 single binary, progress tracked [here](https://github.com/owncloud/ocis/pull/409). Afaict this was only related to ocis-konnectd, not to phoenix. So it will probably not be fixed for oc10 automagically.

**Comment by pmaier1** [comment]
This issue has been fixed. Please reopen in case you still encounter it with the next release.
