### ISSUE TITLE
FEATURE: store default action for opening files.

### ISSUE THREAD

**Issue by labkode** [owncloud/phoenix#3918]
The "open" dialog that appears in the bottom is a nice concept, but I would prefer to set a default action for 
opening (maybe a checkbox to choose this?)

**Comment by PVince81** [comment]
related https://github.com/owncloud/phoenix/issues/3299

**Comment by pmaier1** [comment]
The "open dialog" on the bottom has been removed recently based on usability feedback and all actions have been moved to the "..." menu. If there's an editor for the respective file type available, it will be used when clicking on a file. If there's none, the file will be downloaded. Changing the default has been discussed to be done as a user setting but is not planned in the short term.

**Comment by labkode** [comment]
@pmaier1 that behaviour is the one our users are exposed to, so far so good.
