### ISSUE TITLE
Random CI failure for copying a file into a folder

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#3941]
There is a random CI failure regarding the breadcrumbs when copying a file into a folder:
https://drone.owncloud.com/owncloud/phoenix/10743/36/11

<img width="655" alt="Screenshot 2020-08-12 at 11 44 34" src="https://user-images.githubusercontent.com/3532843/90001246-7c2e5000-dc91-11ea-9c97-a6a4463c026d.png">

@individual-it any idea why this is happening?

**Comment by jasson99** [comment]
The files page is not loaded completely sometimes, and hence the tests fail.
![Screenshot from 2020-08-13 17-47-27](https://user-images.githubusercontent.com/40829116/90132697-ff34d080-dd8d-11ea-8be3-23587a793151.png)
