### ISSUE TITLE
Use the js-owncloud-client lib to connect ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#4]
https://github.com/noveens/js-owncloud-client

This library allows pure js access to any owncloud instance. CORS is supported in owncloud server since 10.0.4

**Comment by felixheidecke** [comment]
Very nice. I already see this as a phoenix dependency :-)

**Comment by felixheidecke** [comment]
Let's not 4get this https://github.com/owncloud/phoenix/issues/90
