### ISSUE TITLE
Marketplace app

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#40]
Code must be organized in a way that we can bundle Phoenix as a marketplace app.

To be discussed:
- do we only want the files app / individual phoenix apps ?
- or do we want the full frontend, navigation, layout to be able to be installed

In the latter case we need a switch somewhere in OC core to let the app take over the full layout.
Or simply provide a checkbox in the login page to "Login into Phoenix" in which case only Phoenix apps are available at first.

**Comment by DeepDiver1975** [comment]
For the very first release we will have one app in marketplace for phoenix. The contained apps can change over time. For more granular distribution we need to have a closer look how to do it.

**Comment by DeepDiver1975** [comment]
refs #225

**Comment by DeepDiver1975** [comment]
lets close this for the scope of 0.1.0 - app splitt up will be addressed in a future release.
