### ISSUE TITLE
Share received inside `share_folder` cannot be unshared

### ISSUE THREAD

**Issue by dpakach** [owncloud/phoenix#4102]
**Tested with OC10(latest git master)**
By default the shares are received in the root folder. But we can set config `share_folder` to set default share receive folder.
### Steps to reproduce
1. Set share folder for receiving share.
2. Login as a user and share a file to another user.
3. Try to login as the receiver and delete the file.

### Expected behaviour
The delete option should be available

### Actual behaviour
The delete option is not available
![Screenshot from 2020-09-24 11-52-04](https://user-images.githubusercontent.com/19869344/94110933-17a30b00-fe63-11ea-8733-6ae9d50a8b2d.png)

**Comment by LukasHirt** [comment]
Will be fixed in #4255
