### ISSUE TITLE
Authentication layer

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#42]
Before accessing any APIs we'll need a way for all frontend code to ensure that the user is authenticated first.

- [ ] login page / dialog (ideally that can work not only with password but also totp, oauth, etc)
- [ ] some middleware that can catch auth errors on ajax calls and redirect to login flow

@DeepDiver1975 @SamuAlfageme @felixheidecke

**Comment by DeepDiver1975** [comment]
- [ ] catch specific auth errors like: user needs to change password

**Comment by DeepDiver1975** [comment]
- [ ] SSO scenarios need to be taken into consideration - no idea how this will work. maybe we simply need to protect the phoenix hosting webspace and inject the user? @butonic any idea?

**Comment by PVince81** [comment]
@butonic also suggested that every full page app can be completely separate. This would make it possible to even deploy each app on a different server (a bit like Google's apps work, GDrive, Calendar, etc). This would require some kind of SSO where the main bundle (router?) is routing to separate apps using tokens to have the user authenticated there. And then if the user would open one of the apps directly it needs to redirect to the router maybe.

**Comment by patrickjahns** [comment]
Most of SPA work on a auth flow - somewhere the loging is done -> they will get redirected to the original SPA page with the tokens included in the callback url

Since we have oauth now - this could be the way to move forward. If the token in the SPA storage is no longer valid, direct to the login page of ownCloud -> once logged in -> redirect to application page

**Comment by felixheidecke** [comment]
Unfortunately https://github.com/owncloud/js-owncloud-client is not working @ the moment. Its not only [travis](https://github.com/owncloud/js-owncloud-client/issues/47) who is having issues.

**Comment by DeepDiver1975** [comment]
> Its not only travis who is having issues.

what are the other issues you are facing?

**Comment by DeepDiver1975** [comment]
some information to consume:
- https://blog.sqreen.io/authentication-best-practices-vue/

**Comment by DeepDiver1975** [comment]
https://github.com/dgrubelic/vue-authenticate looks reasonable for talking oauth with the server

**Comment by butonic** [comment]
@DeepDiver1975 I'm not sure, but I trust you really are using the jwt as API tokens as described in https://scotch.io/bar-talk/why-jwts-suck-as-session-tokens#toc-how-should-i-use-jwts-

right? .. *right?*

**Comment by DeepDiver1975** [comment]
@butonic no jwt seen anywhere in here ;-) - Phoenix uses OAuth to interact with ownCloud server.
In OAuth the token value has no meaning and in our ownCloud implementation it is random generated data which points to information in the database.

jwt comes into play when we start to talk OpenID Connect ... some day ...
