### ISSUE TITLE
Investigate about the failing webUIPreview tests and webUIMoveFiles test and tag with correct issue

### ISSUE THREAD

**Issue by jasson99** [owncloud/phoenix#4269]
## Description:

Some tests in the `webUIPreview` test suite fail in ocis after the suite was added to run in ocis in CI. In order to make CI green, these tests have been skipped in this PR as:  https://github.com/owncloud/phoenix/pull/4253/files#diff-682824e112efafed7cd7f926e5e006773524a3529f91280a201ace8d3dad1db7R26-R48
However, the issue about the failure needs to be investigated.

When adding the issue tag, the files from the examples table in this skipped scenario: https://github.com/owncloud/phoenix/pull/4253/files#diff-682824e112efafed7cd7f926e5e006773524a3529f91280a201ace8d3dad1db7R35-R48 should be separated and only the failing one should be skipped and tagged with the issue-tag.

Also, a scenario of `moveFiles.feature` has also been skipped as : https://github.com/owncloud/phoenix/pull/4253/files#diff-b51675da3e3cd1e024574a42c3f0a876f88e689fc50f69e02c46d9cb41ad4f0bR73

The failure in CI is as : https://drone.owncloud.com/owncloud/phoenix/11634

Investigate about the failure, and add a proper issue tag to the skipped tests.

**Comment by swoichha** [comment]
Fixed by https://github.com/owncloud/phoenix/pull/4291 and https://github.com/owncloud/phoenix/pull/4299
