### ISSUE TITLE
Tests: Reduce isVisible timeout

### ISSUE THREAD

**Issue by kulmann** [owncloud/phoenix#4312]
https://github.com/owncloud/phoenix/blob/2976b58fd470edaea19afc57537f707728e65dbf/tests/acceptance/pageObjects/filesPage.js#L256
and 
https://github.com/owncloud/phoenix/blob/2976b58fd470edaea19afc57537f707728e65dbf/tests/acceptance/pageObjects/filesPage.js#L275

are taking quite long to return `false` (i.e. when an element is not visible).
Example: `tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature:294`

Since that doesn't take long to load, a timeout of 1 second would probably be sufficient and would allow us to speed up the tests a bit.

**Comment by kulmann** [comment]
@phil-davis I bet this is a super easy issue for you guys :-) do you have an idea and would you like to work on this?

**Comment by phil-davis** [comment]
Assigned myself so that I notice it later today.

**Comment by individual-it** [comment]
we can use `waitForNegativeConditionTimeout` like in https://github.com/owncloud/phoenix/pull/4238
