### ISSUE TITLE
[QA][DOC] Please provide a hetzner instance for documentation

### ISSUE THREAD

**Issue by jnweiger** [owncloud/phoenix#4390]
@hodyroff requested documentation of the new ownCloud Web interface. We have @CSF-JH starting to work on that documentation next week.

@LukasHirt @dragotin can you please organize a setup for him?
I have doubts, that ocis.owncloud.works would be sufficiently stable at the 1.0.0 level.

**Comment by LukasHirt** [comment]
@jnweiger Sure, I can take care of deploying an instance for him.

**Comment by LukasHirt** [comment]
The server is up and running with the latest master. Tomorrow I'll ask for a domain so it can be accessed via ocis-docs.owncloud.works and then will check if all works. Let me pls know if the instance should be automatically updated with new changes froom master or if it's preferred to have an instance which is not changing all the time.

**Comment by jnweiger** [comment]
Thanks! 
It should be updated in a controlled manner. When you have updates that change behaviour or requires new screenshots, then I suggest we have them communicated with a proper changelog. No auto-updates please.

I am striving for proper version numbers to track updates. Compare https://github.com/owncloud/ocis/issues/310

**Comment by jnweiger** [comment]
@hodyroff This is phoenix on pure ocis, is this correct? 
Should the documentation also cover the differences between phoenix-on-ocis and phoenix-on-10.6-via-bridge?

**Comment by jnweiger** [comment]
From @hodyroff : "Both. First 10.6, I'd say."

**Comment by LukasHirt** [comment]
Redeployed with the bridge setup. oCIS is still reachable via the same URL ocis-docs.owncloud.works. oC10 part is then living on oc10-docs.owncloud.works. Thanks to @jnweiger for providing those domains. @CSF-JH you can log in with user `admin:admin`. Feel free to create as many new users as you feel like. I will close this issue now - feel free to reopen it in case something would be missing/not working.
