### ISSUE TITLE
Replace uikit submodule with npm package

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#44]
Any reason we need the UIKit submodule ?

It takes ages to clone. Wouldn't it be simpler to add uikit through npm and then adjust the makefile to make it compile from there ?

@felixheidecke

**Comment by PVince81** [comment]
also I seem to have trouble checking it out:
```
± % git submodule update --depth 1
Cloning into '/home/vincent/work/workspace/phoenix/core/uikit'...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
error: Server does not allow request for unadvertised object 0851278355b83ddedce5d8af41dda187d986c1a9
Fetched in submodule path 'core/uikit', but it did not contain 0851278355b83ddedce5d8af41dda187d986c1a9. Direct fetching of that commit failed.
```

(I added depth 1 to accelerate a bit)

**Comment by PVince81** [comment]
Let's pull uikit from npm and build the ownCloud theme using the same strategy like in https://github.com/owncloud/core/pull/30166 where the theme is first copied in and then the output is copied out to the target directory.

If you agree I can have a look how to make this work.

**Comment by felixheidecke** [comment]
Agreed.

**Comment by felixheidecke** [comment]
I just checked out this repo including its submodule with no hassle. Might the problem be somewhere else?

**Comment by DeepDiver1975** [comment]
killing submodule and adding uikit to package.json is easy ..... but what needs to be done in the Makefile? @felixheidecke let me know and I fix it

**Comment by PVince81** [comment]
as a quickfix the makefile should create a symlink to node_modules/wherever/uikit/is to keep the old expected folder structure

in the future we might need more gymnastics to get rid of the symlink
