### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#482]
### Expected behaviour
- each pull request shall be built and deployed
- each pr is testable on it's own
- after opening a PR the link to the test instance will be put into a comment

**Comment by scramb** [comment]
I got some deployment ready, which is tbd. 
I'm still not in knowledge of the deployment process as is.
 I would rather suggest deploying on a PR basis with docker container to keep the maintenance afford as low as possible. The deployment to the Registry is no big issue; The trouble came up with spawning the Container on a different machine, then the deployment agent. In my opinion the easiest way to provide this functionality is to create a script(allready is created but needs to be adopted to fit to infrastructure) and alllow only the usage of this script and bind it to a ssh-key. 
This would provide the ability to spawn docker container of the same image with a different tag. The cleanup needs to be done by weekly cronjob or similar.
@DeepDiver1975 @tboerger any improvements on this?

DockerScript as example:
```
#!/bin/bash

export DRONE_PULL_REQUEST=$SSH_ORIGINAL_COMMAND

docker run --label traefik.docker.network=web --label traefik.enable=true --label traefik.basic.frontend.rule=${DRONE_PULL_REQUEST}.owncloud.team --label traefik.basic.port=8300 --label traefik.basic.protocol=https --expose=8300  --network="web" --network="default" --rm owncloud/phoenix:${DRONE_PULL_REQUEST} 
```

**Comment by DeepDiver1975** [comment]
I'm totally out of this topic - the servers is @tboerger 's realm ...

**Comment by PVince81** [comment]
we already have CI in place now with acceptance tests.

nice would be to have JS tests as well, separate topic: https://github.com/owncloud/phoenix/issues/2026

closing as done

**Comment by tboerger** [comment]
CD is not done... we have not built any PR deployment so far.

**Comment by PVince81** [comment]
do we want CD on master maybe ? daily ? or is weekly enough together with the weekly tarball release ? @LukasHirt @DeepDiver1975

**Comment by tboerger** [comment]
we already got CD for the master branch at phoenix.owncloud.com, but AFAIK the others also would like to see a lightweight environment for every pull request that gets automatically destroyed later on.

**Comment by DeepDiver1975** [comment]
Yes - the idea was to have all PRs deployed - but I honestly question the effort on this.
In 1 year of development we maybe had 2 or 3 PRs where this would have been valuable.

This can also be done in direct 1-to-1 sessions between dev and who-ever-whats-to-review

**Comment by tboerger** [comment]
Drone is nearby the state to be able to offer that. If there is no need for it i'm fine with that.
