### ISSUE TITLE
Upload Multiple Files

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#484]
### Expected behaviour
- when opening the upload dialog a user shall be capable to select multiple files
- multiple progresses are visible in the upload status - see #483 
- Question: enter file before upload is finished?

**Comment by DeepDiver1975** [comment]
The user can still only select one file in the upload dialog.

**Comment by scramb** [comment]
Is this a requirement? Since for me i'm able to select multiple files and successfully upload all of them.

**Comment by DeepDiver1975** [comment]
Which browser did you Test? I will retest AS well

**Comment by DeepDiver1975** [comment]
works - thx - sorry for the noice
