### ISSUE TITLE
Folder Upload

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#485]
### Expected behaviour
- The user clicks on '+ New' button and a new element is listed: 'Upload folder ...'
- A folder selection dialog opens - user choose a folder
- Upload starts upon hitting okay
- Walk the directory information and create folders and subfolders (including empty folders) and upload files
- Progress shall be visible in the upload progress component
- This option is only available on browsers which support folder upload https://caniuse.com/#feat=input-file-directory
- Rename exiting 'Upload' to 'Upload files'
- Choose a proper icon (maybe add a new icon to ODS)
- As an alternative way the user can drag and drop a folder from the desktop onto the browser

**Comment by scramb** [comment]
1.  the uploaded folder should be created as empty
2.  files in uploaded folder root should be uploaded to the newly created folder and subfolders should be created as empty
3.  files of subfolders should be uploaded aswell
4. repeat at 2. untill there are not subfolders anymore

**Comment by DeepDiver1975** [comment]
moving to backlog - not important ...

**Comment by PVince81** [comment]
- also need to make sure that empty folders are preserved
