### ISSUE TITLE
Do we need sass?

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#540]
As of today we install node-sass and sass-loader - see https://github.com/owncloud/phoenix/blob/00924b98d2f1dfe4e22aa85bedebaa623ff8158f/package.json#L53-L56

Installing node-sass is pulling a hell of dependencies into the docker image during build step:

https://github.com/owncloud/phoenix/blob/00924b98d2f1dfe4e22aa85bedebaa623ff8158f/Dockerfile#L4

Is sass needed anywhere? As far as I can tell: no
Do we need it in the future? No idea.

**Comment by scramb** [comment]
You are right. We would use it for custom scss/sass stylings in future i guess. If we manage to write everything in vanilla css this shouldn't be a problem.
