### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#546]
## Description

We need to support all major/commonly used browsers.

As of today phoenix is not properly running in Edge/IE.

Further browser compatibility needs to be tested.

## ToDo

- define explicit list

**Comment by DeepDiver1975** [comment]
![edge](https://user-images.githubusercontent.com/1005065/51666398-0767c800-1fbe-11e9-8dae-0fc395531a56.PNG)
![edge-console](https://user-images.githubusercontent.com/1005065/51666399-0767c800-1fbe-11e9-828f-9b83588c87be.PNG)

**Comment by DeepDiver1975** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility

maybe some polyfill is needed ..... or bable config ...

**Comment by DeepDiver1975** [comment]
from ie

![ie](https://user-images.githubusercontent.com/1005065/51666989-49453e00-1fbf-11e9-90f4-8afd1c8df19d.PNG)
![ie2](https://user-images.githubusercontent.com/1005065/51666991-49453e00-1fbf-11e9-99f9-27d09aec3541.PNG)

**Comment by tempelgogo** [comment]
I would like to recommend https://browserl.ist/, which uses data from https://caniuse.com/ to generate appropriate configuration for babel transpiler. If properly configured, this stack respect's a browserlist from `package.json`
```
"browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
```
similar to this format, check's the needed polyfill's against the caniuse db (only for the polyfill-able features, of course) & insert's them into babelJS.

If we really want to support old platform's without native ES6 Support, i would recommend to use a Browserweiche to build different bundles for each browser generation;
This way the bundle size for all of our moderen-browser-users won't skyrocket & they can still profit from performance boosts & nice features which ES6 will bring.

Anyway: We need to extend our acceptance-tests with old browser testing, so we're able to detect issues around polyfill's & ES5 browser support.

**Comment by DeepDiver1975** [comment]
edge is working - ie11 is missing and will be addressed in anew issue -> close
