### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#548]
We'll need a replacement for the user settings page, currently implemented here:
- stable10: https://github.com/owncloud/core/tree/stable10/settings/templates/users
- master: new unreleased app https://github.com/owncloud/user_management/

In Phoenix we should add a new frontend for the user management page which talks to the existing APIs.

- [ ] fix APIs on core master to make sure all works correctly in https://github.com/owncloud/user_management/, to make sure that the APIs will be properly usable
- [ ] backport API additions from core master to stable10
- [ ] implement new users page in Phoenix as a full page Phoenix app, using the above APIs
- [ ] acceptance tests, etc

Note. this becomes slightly more important nowadays because the fact that we did not release user_management yet causes trouble with translations backports, see https://github.com/owncloud/core/issues/33454. We could decide to make the user_management app work with both master and stable10, which would require steps 1 and 2 above. Depending how broken the app is, we might rather invest the effort in creating a new users page directly in Phoenix, which will later on also be available in OC 10.

@DeepDiver1975 @michaelstingl thoughts ?

**Comment by DeepDiver1975** [comment]
Current APIs are not following our principles of public api. They are neither WebDAV nor OCS.

I see two ways:
- [ ] use and enhance our OCS provisioning API
- [ ] use and enhance the WebDAV principals endpoint

**Comment by DeepDiver1975** [comment]
This is about user management - right? In the first step user management is seen as an admin task and phoenix is currently scoped for end users only -> closing for now - we can bring this back on day ....

@pmaier1
