### ISSUE TITLE
Separate phoenix scaffold from files_app

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#55]
All apps in `/apps` (especially the files app) should be moved to a separate repo.
Scaffolding in the base folder and core will have a separate Makefile and js dependencies.

@PVince81 apparently doesn't like git submodules, but I suggest adding the shipped apps as submodules in die apps folder. Good or stupid idea?

@DeepDiver1975, @patrickjahns thoughts?

**Comment by felixheidecke** [comment]
[I have a repo, especially for this case](https://github.com/owncloud/files_fe). Not sure if the name files_fe is as nice. Should we name repos that work with Phoenix also something like **phoenix_files**?

Anyway. Let's merge open PRs in the phoenix repo and then imediately move the filesapp the new repo.

**Comment by DeepDiver1975** [comment]
for the time being let's keep the apps inside this repo
