### ISSUE TITLE
Open in handler if only one action is configured

### ISSUE THREAD

**Issue by tomneedham** [owncloud/phoenix#574]
### Steps to reproduce
1. Click on a file

### Expected behaviour
If only one action, just use that.

### Actual behaviour
Little popup at the bottom appears, hard to see, and only one action anyway, so just choose it automatically.

**Comment by tomneedham** [comment]
<img width="408" alt="screenshot 2019-01-31 at 15 04 30" src="https://user-images.githubusercontent.com/660805/52062992-871b0700-2569-11e9-8463-d70196adc333.png">

**Comment by DeepDiver1975** [comment]
I'm not too sure if we should got for the automatic opening - the behavior will then be different depending on the number of available actions ....

Regarding visibility of the popup we can discuss ideas - THX

**Comment by DeepDiver1975** [comment]
kind of fixed - we always have download there as default action now.
