### ISSUE TITLE
Files filter dropdown is squashed

### ISSUE THREAD

**Issue by tomneedham** [owncloud/phoenix#575]
### Steps to reproduce
1. Open phoenix files app
2. Click on filters

### Expected behaviour
Can read options

### Actual behaviour
Options are squished as dropdown is too narrow.
<img width="215" alt="screenshot 2019-01-31 at 15 07 19" src="https://user-images.githubusercontent.com/660805/52063205-0d374d80-256a-11e9-9a94-f14dd4224056.png">

**Comment by DeepDiver1975** [comment]
Putting to backlog for now - filtering needs more love ..... we will see ....

**Comment by DeepDiver1975** [comment]
fixed with #780
