### ISSUE TITLE
Click / touch area of breadcrumb is very small

### ISSUE THREAD

**Issue by tomneedham** [owncloud/phoenix#577]
### Steps to reproduce
1. Open files app in phoenix
2. Nav to a deep subfolder

### Expected behaviour
Can click on breadcrump to navigate

### Actual behaviour
Hard to click / touch as click area is very tight around breadcrumb elements. 

<img width="307" alt="screenshot 2019-01-31 at 15 12 04" src="https://user-images.githubusercontent.com/660805/52063503-b5e5ad00-256a-11e9-91a5-734ae7556718.png">

**Comment by DeepDiver1975** [comment]
THX - next sprint
