### ISSUE TITLE
Remove unnecessary writing from new file/folder dropdown

### ISSUE THREAD

**Issue by tomneedham** [owncloud/phoenix#578]
### Steps to reproduce
1. open files app
2. click 'new' 

### Expected behaviour
Dropdown with options

### Actual behaviour
Text that adds no additional context. 

<img width="465" alt="screenshot 2019-01-31 at 15 13 27" src="https://user-images.githubusercontent.com/660805/52063622-df9ed400-256a-11e9-8bfa-280fdbb57307.png">

Suggest to remove the writing above the options. It adds nothing on top of the options, and the first click which was 'new'.

**Comment by DeepDiver1975** [comment]
This was inspired by Box. Keeping this open for discussion.

**Comment by tomneedham** [comment]
<img width="339" alt="screenshot 2019-02-03 at 21 40 36" src="https://user-images.githubusercontent.com/660805/52182336-07549d00-27f4-11e9-81e3-d898acc30e0d.png">
<img width="438" alt="screenshot 2019-02-03 at 21 40 34" src="https://user-images.githubusercontent.com/660805/52182338-09b6f700-27f4-11e9-9ea7-a6c434c3585e.png">

**Comment by DeepDiver1975** [comment]
@tomneedham like this? Is this better?

![screenshot from 2019-02-14 16-08-22](https://user-images.githubusercontent.com/1005065/52795775-c9b50700-3072-11e9-881f-4b33cc197646.png)
