### ISSUE TITLE
Download file when no other action is available

### ISSUE THREAD

**Issue by tomneedham** [owncloud/phoenix#579]
### Steps to reproduce
1. Open files app in phoenix
2. Click on a .jpg

### Expected behaviour
Opens in viewer if enabled, or just downloads. 

### Actual behaviour
Pop up at the bottom with no options. 

<img width="513" alt="screenshot 2019-01-31 at 15 15 35" src="https://user-images.githubusercontent.com/660805/52063794-2f7d9b00-256b-11e9-8a36-01ad8065c817.png">

Suggest just download. Or at least dont show the popup with no answers.

**Comment by DeepDiver1975** [comment]
Dont Show the popup is the right Thing to so... Thx
