### ISSUE TITLE
Split file list metadata horizontally instead of stacking

### ISSUE THREAD

**Issue by tomneedham** [owncloud/phoenix#580]
### Steps to reproduce
1. Open files app in phoenix
2. Observe list of files and folders.

### Expected behaviour
 - Aasy to spot file based on name (this is why you are here, to locate a file) 
 - Can spot lasted activity, or particular sized file

### Actual behaviour
 - Metadata for files are stacked on top of each other, essentially in one column
 - This makes it hard to scan with your eyes for a particular results
   - See native file browsers -> separate columns
   - See other cloud browsers -> separate columns 
 - Also allows sorting by column. 

 - Column show/hide is another discussion IMO.

Example of stacked (now):
<img width="485" alt="screenshot 2019-01-31 at 15 41 05" src="https://user-images.githubusercontent.com/660805/52066048-ae74d280-256f-11e9-850b-7191a62dbed7.png">

Example of horiztonal (desire, cleaner, easier to find files, more consistent):
<img width="1087" alt="screenshot 2019-01-31 at 15 41 16" src="https://user-images.githubusercontent.com/660805/52066088-c0ef0c00-256f-11e9-9149-bfd5451ccaf6.png">

**Comment by michaelstingl** [comment]
Mobile optimised view could have multi-line layout, similar to native mobile apps. (depending on available space)

**Comment by DeepDiver1975** [comment]
They have been stacked because of in case the sidebar is open the space is better used.

I'm far from happy with the current side bar behavior - this needs UX input ....

**Comment by tomneedham** [comment]
Would rather design a file list that works, than change that, because of another component... :P Seems a bit strange. We can do better! Maybe side bar slides in, and all columns apart from name are hidden

**Comment by DeepDiver1975** [comment]
Absolutely agree. We can do better and we will so better!

**Comment by tomneedham** [comment]
Done with ui kit stuff recently
