### ISSUE TITLE
Sharing SideBar

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#583]
This issue is about defining how the file sharing side bar shall look like and how it shall work.

@pmaier1 let's chat ;-)
@michaelstingl your input is valuable here as well
Andreas is required here as well.

THX

**Comment by PVince81** [comment]
@felixheidecke please share your mock ups / click dummy

**Comment by felixheidecke** [comment]
The sharing mock ups / click dummy was integrated into the old Phoenix version and was about to be extracted into it's own repo: https://github.com/owncloud/files_sharing_fe

I revived an old version of [classic Phoenix](https://github.com/owncloud/phoenix/tree/classic) in here, which shows the concept of a multi-stage sharing process where one could choose between quick share and using more options. Wasn't perfect, but a first draft.

**Comment by DeepDiver1975** [comment]
> I revived an old version of [classic Phoenix](https://github.com/owncloud/phoenix/tree/classic) in here, which shows the concept of a multi-stage sharing process where one could choose between quick share and using more options. Wasn't perfect, but a first draft.

thx - I'll try to revive this and paste screenshots ... unless you have some left @felixheidecke

**Comment by felixheidecke** [comment]
PS: mockups were to be developed as [design guidelines](https://github.com/owncloud/enterprise/issues/2791) evolved to make sure UX would follow global principles.

**Comment by felixheidecke** [comment]
Some old screenshots https://cloud.owncloud.com/index.php/s/MCqRCZGGqicdBva

**Comment by DeepDiver1975** [comment]
![phoenix_classic_share_001](https://user-images.githubusercontent.com/1005065/52936249-e21b6f00-335b-11e9-9943-143b7c4886b0.png)
![phoenix_classic_share_002](https://user-images.githubusercontent.com/1005065/52936248-e21b6f00-335b-11e9-9829-8d14976ecfae.png)
![phoenix_classic_share_003](https://user-images.githubusercontent.com/1005065/52936247-e182d880-335b-11e9-8149-92ad184d2168.png)
![phoenix_classic_share_004](https://user-images.githubusercontent.com/1005065/52936246-e182d880-335b-11e9-9feb-d463beebca12.png)

**Comment by DeepDiver1975** [comment]
related to #1186 

we don't need two issues -> closing this one
