### ISSUE TITLE
Translation adjustments

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#584]
- [x] add pdf-viewer and markdown-editor to l10n
- [ ] make sure interpolated strings get extracted

**Comment by DeepDiver1975** [comment]
@scramb please reference the upstream issue/pull request as soon as you have them - THX

**Comment by DeepDiver1975** [comment]
@scramb any news on the upstream bug fix you have been working on? THX

**Comment by scramb** [comment]
nothing working... hacky as hell and it feels like they forgot about interpolation while building this... feels like a total rework...

**Comment by DeepDiver1975** [comment]
workaround for the time being: move to computed propy -> close
