### ISSUE TITLE
FileactionsTab seems broken

### ISSUE THREAD

**Issue by tempelgogo** [owncloud/phoenix#590]
### Steps to reproduce
1. Open MarkDown file
2. Click 'Markdown Editor'

### Expected behaviour
markdown editor opens
Tell us what should happen

### Actual behaviour
pdf editor opens

### To Do
discuss active File Parameter....
1. Is the open file visible in URI & we force all app's to receive filePath in URI ?
2. Or do we keep the current behaviour & store it in the vuex.

**Comment by scramb** [comment]
broken import. fixed in my ui PR, will adjust requested changes in my PR to fix this asap
