### ISSUE TITLE
folder to small

### ISSUE THREAD

**Issue by theScrabi** [owncloud/phoenix#60]
Hola chicos,

I learned about this design from the blog. I find it nice, but I instantly saw some things I'd like to be better. I found that the file icons are just to small compared to the rest of the UI elements. Example:
![37416039-20817b4c-27ad-11e8-9f14-cbe12936fd64](https://user-images.githubusercontent.com/1891273/37736936-8e9c168c-2d52-11e8-8158-05c4c14f5a46.png)

You can see that the file icons are even a bit smaller than the checkbox beside it. I don't like it, because the meaning of the icon is harder to detect, and ... it just does not look right.

Actually the size of the icons as  they are right now is pretty good I think:

![bildschirmfoto vom 2018-03-21 21-52-22](https://user-images.githubusercontent.com/1891273/37736938-91348366-2d52-11e8-9982-11138635ee81.png)

**Comment by DeepDiver1975** [comment]
Once the full row is connected to one action only the height of the row is relevant and not the icon size.

**Comment by DeepDiver1975** [comment]
refs: https://github.com/owncloud/phoenix/issues/149#issuecomment-423895083

**Comment by DeepDiver1975** [comment]
fixed from my pov
