### ISSUE TITLE
Enable history mode in vue-router

### ISSUE THREAD

**Issue by tempelgogo** [owncloud/phoenix#606]
### Description
as mentioned in #573, we need to to change the phoenix application to history mode to get rid of the hash in the url.

`/#/login` -> `/login`
`/#/files/list/Open_Data` -> `/files/list/Open_Data`

It's supported within our target platform: https://caniuse.com/#feat=history

### Expected behaviour
`/files/list/Open_Data`

### Actual behaviour
`/#/files/list/Open_Data`

**Comment by tempelgogo** [comment]
@DeepDiver1975 is it a requirement that we are able to deploy phoenix in a directory ?
We've got an issue about this... #377 But actually i don't know what's inside our requirements.

**Comment by DeepDiver1975** [comment]
We should support this - yes.
