### ISSUE TITLE
Allow direct access to sharing and other menus from open folder

### ISSUE THREAD

**Issue by hodyroff** [owncloud/phoenix#644]
Existing concept from oC10 which has not been adressed.
When I open a folder, I can't access the menu actions anymore. I need to go to the parent folder and take it from there.
Would recommend such icons as part of the folder menu, on the left of the "+ new" button ...

**Comment by DeepDiver1975** [comment]
moved to backlog until we have ux resources available

**Comment by DeepDiver1975** [comment]
@LukasHirt I'm assigning you to work with the design team on a proper solution

**Comment by PVince81** [comment]
> Existing concept from oC10 which has not been adressed.

Assuming this means "we had some ideas for OC 10 that we never got to implement".

Raised here https://github.com/owncloud/phoenix/issues/2061
