### ISSUE TITLE
Local File Filter dysfunctional

### ISSUE THREAD

**Issue by tempelgogo** [owncloud/phoenix#665]
Local File Filter broken since https://github.com/owncloud/phoenix/pull/623 due to component splitting.

## Related Issue:
- #662 local folder search broken

## Description:
prepared in #666

## ToDo:
- [ ] use event's instead of v-model & inject value into vuetify `input-value`
- [ ] test all filters

**Comment by DeepDiver1975** [comment]
Quick fix: remove it ;-)

This element needs UX anyhow :man_shrugging:
