### ISSUE TITLE
File uploads with chunking and resumable

### ISSUE THREAD

**Issue by PVince81** [owncloud/phoenix#67]
We should look into using http://www.resumablejs.com/ for Phoenix.

Don't pick up the old upload code from core as it uses jquery.fileupload and needs to much hacking around to make it work with our chunking.

**Comment by DeepDiver1975** [comment]
We need to check if this plays well together with offline capabilities ......

ref https://blog.sicara.com/a-progressive-web-application-with-vue-js-webpack-material-design-part-3-service-workers-offline-ed3184264fd1

**Comment by PVince81** [comment]
Depends if we expect uploading to be an offline capability...

**Comment by PVince81** [comment]
Estimate:
- web UI add button + styles: 0.5md
- actual upload without chunking: 3md
- add chunking (PUT of chunks + final MOVE): 4md
- simple progress bar: 0.5md
- acceptance test: 2md ? check with QA

total: 8-10md

**Comment by PVince81** [comment]
From what I see, resumable JS is using POST with multipart, which is not desired and not compatible with Webdav. We'd need to rewrite parts of resumable JS to talk our Webdav chunking protocol.

**Comment by PVince81** [comment]
seems there is a way to set the method to be "PUT".
we also need a way to set headers, maybe need to intercept the XHR object unless there are early callbacks or events for setting them

Also see this old "OC bulk upload" app which was based on resumable.js: https://github.com/fmkaiser/bulkupload

**Comment by scramb** [comment]
Is this still a thing to discuss since there allready is a working upload method by now?

**Comment by michaelstingl** [comment]
@scramb How does uploads work now? Chunked? Do they resume after being offline? Otherwise we should keep it open for a future sprint…

**Comment by DeepDiver1975** [comment]
> Otherwise we should keep it open for a future sprint…

yes - we need to keep this open.

**Comment by kulmann** [comment]
Might be interesting to look into TUS protocol for resumable, chunked uploads. Implementations exist in both Golang and Javascript. Saving this here for later. https://tus.io/implementations.html

**Comment by DeepDiver1975** [comment]
With the plan in mind to use the msgraph API. Please postpone this issue until WE are Set.

**Comment by PVince81** [comment]
We're going to look into the TUS protocol using https://github.com/tus/tus-js-client

For prototyping, let's put the code into Phoenix directly and dynamically override the `this.$client.putFileContents` method when OCIS is detected (capability?)

Later on we could decide to move the function to the SDK once it's ready.

Thoughts: since we're going to pass in extra metadata like "mtime", we should pass those as part of the "options" argument and not as part of the headers, because the way of passing metadata with TUS is different than for the OC 10 approach.

**Comment by PVince81** [comment]
WIP PR for TUS upload: https://github.com/owncloud/phoenix/pull/3345
