### ISSUE TITLE
Cleanup CodeBase & enforce Code Style Guide

### ISSUE THREAD

**Issue by tempelgogo** [owncloud/phoenix#697]
### Description
At the time of creation, there was no style guide. We also did heavy refactoring, there are still some leftovers. The Code Style inside the webpack scripts don't match, so there seems to be some issues with our ESLint config.

Additionally we have configured the webpack build systems individually, confusing enough they differ in their behaviour.
We should at least resolve the same file types in all webpack's, so we can use import's without `.vue` file extension inside the whole phoenix (we need to set filetype explicit in files app, but not in core currently)

### To Do
- [x] repair ESLint to match one setting for core & all apps
- [x] run ESLint auto-fix
- [x] replace (almost) all `"` with `'` in `.js` files (especially apps webpack)
- [x] fix indentation in webpack files
- [x] remove semicolons in (almost) all `.js` files (especially apps webpack)
- [ ] to be discussed: create `webpack.base.js` analogous to `webpack.common.js` for use with `webpack-merge` inside apps, including at least unified resolve extensions

**Comment by DeepDiver1975** [comment]
fixes with #699 ? @tempelgogo

**Comment by scramb** [comment]
>     * [ ]  to be discussed: create `webpack.base.js` analogous to `webpack.common.js` for use with `webpack-merge` inside apps, including at least unified resolve extensions

Not sure if we should do this. We should think about a better solution for exposing components and service-apis like notification or file-actions

**Comment by tempelgogo** [comment]
we need to modify our bundling system anyway...
