### ISSUE TITLE
Build fails in feature/add-ocds

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#791]
Building Phoenix fails on [feature/add-ocds] due to unresolvable modules.

### Steps to reproduce
1. yarn install
2. yarn install-all
3. yarin build-all

### Expected behaviour
Everything works nice and dandy.

### Actual behaviour

Multiple components and files report missing dependency:
```
[…]
[phoenix/apps/markdown-editor/src/store.js] import '@babel/polyfill' was not found.
[phoenix/apps/markdown-editor/src/MarkdownEditor.vue] import '@babel/polyfill' was not found.
[phoenix/apps/pdf-viewer/src/store.js] import '@babel/polyfill' was not found.
[phoenix/apps/pdf-viewer/src/PdfViewer.vue] import '@babel/polyfill' was not found.
[phoenix/src/Phoenix.vue] import '@babel/polyfill' was not found.
[phoenix/src/pages/login.vue] import '@babel/polyfill' was not found.
[phoenix/src/pages/oidcCallback.vue] import '@babel/polyfill' was not found.
[…]
```
Finaly fails on:
```
ERROR in ./src/services/auth.js
Module not found: Error: Can't resolve 'babel-polyfill' in '/private/tmp/phoenix/src/services'
```

### Server configuration
**Operating system**:
macOs 10.14.3
node v10.15.3

PS:
`phoenix/node_modules/@babel/polyfill` is alive and well.

**Comment by DeepDiver1975** [comment]
try to remove this line https://github.com/owncloud/phoenix/blob/87d5af98996b41d7038fc8106621c61bea35c8f6/src/services/auth.js#L2

**Comment by felixheidecke** [comment]
Japp … works. Should I take a look @ the actual problem? Does it work on your os?

**Comment by DeepDiver1975** [comment]
I guess this is related to the node version being used .... I did see this on another dev machine as well

**Comment by DeepDiver1975** [comment]
I guess we need to nail down the node versions we support and do proper ci on them .....

**Comment by scramb** [comment]
As discussed in chat, the fix is the adjustment of the import from `babel-polyfill`to `@babel/polyfill`

**Comment by DeepDiver1975** [comment]
afaik this is resolved -> close
