### ISSUE TITLE
Allow apps to register to a connected event ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#80]
An app wants to start with processing as soon as phoenix is connected to the server.
We might want to add a mixin which allows us to perform actions as soon as the connection is established.

To take care of: how will this work in offline mode?

**Comment by felixheidecke** [comment]
There is an event for that: `OC.$bus.on('phoenix:user-logged-in', () => { magic here })`

Does that suffice?

**Comment by PVince81** [comment]
Connected doesn't mean logged in. In the case of public link shares there is no logged in user.

Maybe internally the js-owncloud-client would anyway need to use the token + link password to login, so the "user-logged-in" event would work.

Maybe an app wants to do something before the user is logged in but as soon as we know the URL to the server ? not sure

**Comment by felixheidecke** [comment]
> Connected doesn't mean logged in.

@PVince81 … hmmm … true.
Then I guess we should get rid of choosing the server you want to connect in the login screen and choose the instance on phoenix startup.

@DeepDiver1975 Instead of waiting for the connection, the app could simply connect by itself instead.

**Comment by DeepDiver1975** [comment]
this is closed from my pov
