### ISSUE TITLE
Node.js vs. native ES6 support

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/phoenix#81]
I am currently weighing using node.js vs the native ES6 support in current browsers. Why? you ask?

Using node would allow us to easily read from the filesystem, scan folders and all the crazy good stuff, such as having the apps simply expose what we need to render it to the right place in the dom. All the scaffolding such as app loading could be done in ES6 and we still could support IE11 since all the crunching is done on the node server. We wouldn't even need Apache, IIS or whatever. Just node. Since the latter is written in JS, it opens up native endpoints in the webserver too.

The native ES6 support in Browsers is very limited. We "only" can load javascript from the filesystem (no reading form the package.json for example) and they would have to be written in a specific way for exposition to work.
This would of course not be supported by IE11.

I am currently working out a way **not** using node and see how much we are able to accomplish using this approach. I'll keep you posted.

@PVince81 @DeepDiver1975

**Comment by DeepDiver1975** [comment]
You are talking about node.js during dev time, right? 
Phoenix shall not use any serverside technology at runtime

**Comment by felixheidecke** [comment]
> You are talking about node.js during dev time, right?

Actually … no, I am talking about production. There is no way, to `require` or `import` (properly) without using node.js. Challenge is, that we have to dynamically load js from apps which we can't do. @DeepDiver1975

**Comment by DeepDiver1975** [comment]
The prime requirement is to have Phoenix pure static.

**Comment by felixheidecke** [comment]
Pro's of node.js:

* Easy installation of frontend code for apps _(no FTP uploading, editing files shenanigans required)_
* Knowledge of all installed apps and their respective states
* Initial authentication thru node <--> core instead of continuous re-auth
* Partially extracting and rendering app elements on a need-to-load basis
* Full ES6 support _(e. g. importing and requiring during runtime)_
* Fully backward compatibility for older browsers
* Caching
* Overall huge speed increase with server-side rendering

**Comment by felixheidecke** [comment]
I added requirejs in my current [app-loader PR](https://github.com/owncloud/phoenix/pull/83). Works quite fine. So FE apps need to be written to work with requirejs wich is fine in my opinion.

**Comment by DeepDiver1975** [comment]
close then?

**Comment by felixheidecke** [comment]
We still haven't decided on the installation process yet.

**Comment by DeepDiver1975** [comment]
> We still haven't decided on the installation process yet.

but this is nothing in scope of node.js server -> closing
