### ISSUE TITLE
Implement acceptance tests

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#844]
- [ ] We have feature which need to be implemented in https://github.com/owncloud/phoenix/tree/master/tests/acceptance/features/webUIFiles

- [x] More tests need to be copied over from https://github.com/owncloud/core/tree/master/tests/acceptance/features - https://github.com/owncloud/phoenix/issues/373

- [ ] New acceptance criteria are to be defined

**Comment by DeepDiver1975** [comment]
>     * New acceptance criteria are to be defined

@pmaier1 @felixboehm can you please link them here? THX

**Comment by DeepDiver1975** [comment]
> @pmaier1 @felixboehm can you please link them here? THX

@pmaier1 @felixboehm ping - THX

**Comment by individual-it** [comment]
I think all relevant features were copied from core, now the functions and the test need to be implemented

**Comment by DeepDiver1975** [comment]
THX!

**Comment by DeepDiver1975** [comment]
this is an on-going task which is take care of nicely by the qa team - devs need to get more involved here -> close
