### ISSUE TITLE
file drop support

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#880]
### Scenario
As a user I want to drag files and folders from my desktop file manager into phoenix

### Expectation
- single files can be dropped
- multiple files can be dropped
- folders can be dropped
- full folder structures INCLUDING empty folders can be dropped
- the dropzone is the whole files app place in the browser

**Comment by DeepDiver1975** [comment]
Possible component to be used: https://rowanwins.github.io/vue-dropzone/docs/dist/#/demo

**Comment by PVince81** [comment]
- empty folders as present in the structure are also accepted and created

**Comment by PVince81** [comment]
also the why: because it's more convenient to upload and replicate complex folder structure than by using the "open and select files dialog" which I believe doesn't even support selecting folders

**Comment by michaelstingl** [comment]
> "open and select files dialog" which I believe doesn't even support selecting folders

Other solutions have one button to upload files and one button to upload folders. They open a slightly different behaving filepicker.

**Comment by DeepDiver1975** [comment]
> Other solutions have one button to upload files and one button to upload folders. They open a slightly different behaving filepicker.

yes - let's see where we are heading to with the upload menu elements - this issue here is only about drag and drop
