### ISSUE TITLE
Can't save edited file with markdown editor

### ISSUE THREAD

**Issue by LukasHirt** [owncloud/phoenix#885]
### Steps to reproduce
1. Edit file with markdown editor
2. Hit the save button

### Actual behaviour
After hitting the save button console throws an error with blocked access to XMLHttpRequest at the ownCloud server

### Server configuration
**Operating system**: Mac OS Mojave

**Web server:** Apache

**Database:** sqlite3

**PHP version:** 7.2.1

**ownCloud version:** 10.1.1

#### Browser log
```
Access to XMLHttpRequest at 'http://127.0.0.1:8888/remote.php/webdav/README.md' from origin 'http://0.0.0.0:8300' has been blocked by CORS policy: Request header field if-none-match is not allowed by Access-Control-Allow-Headers in preflight response.

Access to fetch at 'http://127.0.0.1:8888//remote.php/dav/avatars/admin/128.png' from origin 'http://0.0.0.0:8300' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by DeepDiver1975** [comment]
> Access to fetch at 'http://127.0.0.1:8888//remote.php/dav/avatars/admin/128.png' from origin 'http://0.0.0.0:8300' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

hmmm - not reproducible locally.

What is the server version you are running @LukasHirt

**Comment by LukasHirt** [comment]
@DeepDiver1975 ownCloud 10.1.1 (stable)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 ownCloud 10.1.1 (stable)

running this one locally as well -> works ..... smells like screenshare .....

**Comment by LukasHirt** [comment]
Weird. Could it be maybe because I'm running server via MAMP instead of docker? Or is this too much of conspiracy?

**Comment by DeepDiver1975** [comment]
nobody knows - let's do a screenshare tomorrow morning

**Comment by LukasHirt** [comment]
Ok
