### ISSUE TITLE
Accessibility - support screenreaders and so on

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#89]
refs https://github.com/owncloud/core/issues/25466

this is only a placeholder as of now - needs detailed requirements and specification

**Comment by DeepDiver1975** [comment]
@felixheidecke can you please have a look what vue offers with this regards? THX

**Comment by felixheidecke** [comment]
this is specific to the HTML structure

**Comment by PVince81** [comment]
@felixheidecke did we have this in the docs or is this something to add or clarify ?

**Comment by felixheidecke** [comment]
I did a little research and it's not in the guidelines. I think it was since we have customers that essentially require it.

Good accessibility is achieved by writing good HTML code and should part of the coding-guideline.
This is not specifically related to Phoenix.

**Comment by PVince81** [comment]
Can you add it or at least submit a ticket to the documentation about said guidelines ?

**Comment by DeepDiver1975** [comment]
I expect to see some explicit steps to be taken to ensure we generate proper accessible frontends.
I'm talking about tooling or even CI integrations.

@individual-it @phil-davis @patrickjahns ideas are welcome ...

**Comment by felixheidecke** [comment]
See https://github.com/owncloud/documentation/issues/4062
