### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#891]
refs #753 - hard requirement for customer - needed on dsp/master branch as well as ods

**Comment by tempelgogo** [comment]
Do we use Browserstack or IE11 in our Selenium-Drone tests ?

**Comment by DeepDiver1975** [comment]
IE11 support is moving away further .... https://github.com/styleguidist/react-styleguidist/issues/1264

Here is the issue:
- phoenix uses owncloud-design-system
- ... uses vue-styleguidist (https://github.com/vue-styleguidist/vue-styleguidist/issues/83#issuecomment-482091833)
- vue-styleguidist uses different dependencies which constantly have issues with ie11

The only way to really make this work is to constantly test and fix this. Fix in terms of submitting patches to upstream projects.

**Comment by individual-it** [comment]
> Do we use Browserstack or IE11 in our Selenium-based DroneCI tests ?
> We should integrate it into our test suite before.

running IE in a docker container seems to be possible but difficult to set up and requires licenses https://medium.com/@aandryashin/selenium-on-windows-docker-revolution-f5a7eab205ad
We used to use https://saucelabs.com/ so we can try that and also browserstack.
It might work for now but will be slow or expensive when we create more tests

**Comment by DeepDiver1975** [comment]
I'd say we are done this this so far
