### ISSUE TITLE
ODS-Branch: acceptance tests are failing ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/phoenix#902]
see https://drone.owncloud.com/owncloud/phoenix/2113/14

**Comment by DeepDiver1975** [comment]
I was merging master into develop/ods-3 and acceptnace test are failing now .... most likly related to the missing functionality in the filter menu #900 

assigning @individual-it and @LukasHirt to get knowledge about acceptance testing transferred. THX

**Comment by individual-it** [comment]
PR in #910
