### ISSUE TITLE
file list is not updated after file/folder rename

### ISSUE THREAD

**Issue by individual-it** [owncloud/phoenix#934]
### Steps to reproduce
1. rename a file or folder

### Expected behaviour
the file list should be updated with the new name

### Actual behaviour
file list stays the same, only updated after a reload

**Comment by individual-it** [comment]
the outer `a` element is updated but not the inner human readable `span`
![image](https://user-images.githubusercontent.com/2425577/56033330-19970e00-5d44-11e9-93f5-46475d1b11fe.png)

**Comment by DeepDiver1975** [comment]
sounds like a binding issue within oc-file

**Comment by individual-it** [comment]
please remember to fix/unskip tests taged `@issue-934` after fixing this

**Comment by DeepDiver1975** [comment]
@individual-it I'm missing a step which creates lorem.txt - https://github.com/owncloud/phoenix/blob/ac8eb938f4bc62f53f514244bce726320036c2d6/tests/acceptance/features/webUIRenameFiles/renameFiles.feature#L14

Is this missing in the background? Or some other other step has to run before? THX

**Comment by individual-it** [comment]
it comes from the skeleton folder set in https://github.com/owncloud/phoenix/pull/932 coming from https://github.com/owncloud/testing/tree/master/data/webUISkeleton
I guess it should be documented :see_no_evil:
